### ISSUE TITLE
wrtc cmake problem during CLI install

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2267]
Interesting issue here where it looks like node-gyp was downloading a pre-built binary from someone's github which is exceeding it's account storage limit and failed to fall back to my machine's native build system.
![Screen Shot 2023-01-13 at 12 19 34 PM](https://user-images.githubusercontent.com/3398896/212380485-d3e84548-16f7-436f-8315-2f7a3681d2f4.png)

**Comment by wittjosiah** [comment]
@dmaretskyi thoughts? could we provide our own pre-built binary for @koush/wrtc somehow?
