### ISSUE TITLE
Auto submit bug template filled out from devtools

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2287]
Like in React dev tools
![image](https://user-images.githubusercontent.com/3398896/212745918-b2d1d97c-7d58-42f6-a21e-62aac1c2398d.png)

![image](https://user-images.githubusercontent.com/3398896/212745895-621aac07-0508-448b-b64a-ea76f8ce3c43.png)

**Comment by dmaretskyi** [comment]
Example:
https://github.com/facebook/react/issues/new?template=devtools_bug_report.yml&labels=Component%3A%20Developer%20Tools%2CType%3A%20Bug%2CStatus%3A%20Unconfirmed&title=%5BDevTools%20Bug%5D%20Commit%20tree%20does%20not%20contain%20fiber%20%224543%22.%20This%20is%20a%20bug%20in%20React%20DevTools.&automated_package=react-devtools-extensions&automated_version=4.27.1-47f63dc54&automated_error_message=Commit%20tree%20does%20not%20contain%20fiber%20%224543%22.%20This%20is%20a%20bug%20in%20React%20DevTools.&automated_call_stack=%20%20%20%20at%20updateTree%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A26856%3A21)%0A%20%20%20%20at%20getCommitTree%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A26716%3A20)%0A%20%20%20%20at%20SidebarCommitInfo_SidebarCommitInfo%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A55240%3A42)%0A%20%20%20%20at%20Ri%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A16122%3A7)%0A%20%20%20%20at%20tk%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A17190%3A7)%0A%20%20%20%20at%20kn%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A20548%3A86)%0A%20%20%20%20at%20gn%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A20091%3A11)%0A%20%20%20%20at%20fn%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A20011%3A23)%0A%20%20%20%20at%20Um%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A19991%3A5)%0A%20%20%20%20at%20Wm%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A19795%3A7)&automated_component_stack=%0A%20%20%20%20at%20SidebarCommitInfo_SidebarCommitInfo%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A55220%3A34)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20div%0A%20%20%20%20at%20SettingsModalContextController%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A37690%3A3)%0A%20%20%20%20at%20Profiler_Profiler%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A55516%3A34)%0A%20%20%20%20at%20ErrorBoundary_ErrorBoundary%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A39222%3A5)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20div%0A%20%20%20%20at%20ThemeProvider%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A39394%3A3)%0A%20%20%20%20at%20PortaledContent%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A39424%3A5)%0A%20%20%20%20at%20div%0A%20%20%20%20at%20div%0A%20%20%20%20at%20div%0A%20%20%20%20at%20ThemeProvider%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A39394%3A3)%0A%20%20%20%20at%20TimelineContextController%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A44671%3A3)%0A%20%20%20%20at%20ProfilerContextController%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A44100%3A3)%0A%20%20%20%20at%20TreeContextController%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A31925%3A3)%0A%20%20%20%20at%20SettingsContextController%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A32569%3A3)%0A%20%20%20%20at%20ModalDialogContextController%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A39819%3A3)%0A%20%20%20%20at%20DevTools_DevTools%20(chrome-extension%3A%2F%2Ffmkadmapgofadopljbjfkapdkoienihi%2Fbuild%2Fmain.js%3A56024%3A3)&automated_github_query_string=https://api.github.com/search/issues?q=Commit%20tree%20does%20not%20contain%20fiber%20.%20This%20is%20a%20bug%20in%20React%20DevTools.%20in%3Atitle%20is%3Aissue%20is%3Aopen%20is%3Apublic%20label%3A%22Component%3A%20Developer%20Tools%22%20repo%3Afacebook%2Freact

**Comment by dmaretskyi** [comment]
Also searches for existing issues

<img width="760" alt="image" src="https://user-images.githubusercontent.com/35851437/212748408-eab2632b-e21f-4999-ad62-34ec241e8dec.png">
