### ISSUE TITLE
Friendly error when creating a space without identity

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2406]
- [x] when attempting to `createSpace` before obtaining a HALO identity, client times out
<img width="835" alt="Screenshot 2023-01-31 at 12 34 58 AM" src="https://user-images.githubusercontent.com/3398896/215678839-7f27b447-323d-414c-a731-8031d5da6aa8.png">

Should be:
`Failed to create space.  This device has no HALO identity available. See https://docs.dxos.org/guide/halo`

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/pull/2423
