### ISSUE TITLE
failing invitations should disappear from the invite list properly

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2447]

**Comment by wittjosiah** [comment]
@zhenyasav does "properly" mean automatically or just that remove is currently broken?

**Comment by zhenyasav** [comment]
I think for now we just need to be able to delete them when the delete button is clicked. Automatic removal does not need to happen, but I imagine it can clear (or just not show) failed invites older than a few minutes.

**Comment by zhenyasav** [comment]
this is likely fixed in shell
