### ISSUE TITLE
Add credential mananagement APIs

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#2489]
Add api methods to:

- [x] Save credential to device chain
- [x] Query credentials (with simple filtering)
- [x] Create presentations:
   - Parameters contain a list of credentials (their ids) to be included in the Presentation.
   - Params may contain a nonce.
   - Presentation will be signed by the device key.
   - Device will automatically include it's chain (`AuthorizedDevice` credentials).

Example usage (pseudocode):
```typescript
const kubeAccessCredential = fetch('kube/getAccess')

const { id } = client.halo.saveCredential(kubeAccessCredential)

// later
const nonce = fetch('kube/nonce')

const presentation = client.halo.presentCredential({ id, nonce })

const sessionToken = fetch('kube/auth', { presentation })


// query credentials
const creds = client.halo.queryCredentials({ type: 'dxos.halo.credentials.KubeAccess' })
```

**Comment by dmaretskyi** [comment]
cc @egorgripasov @richburdon @zhenyasav

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/pull/2502
