### ISSUE TITLE
Kai UX

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2492]
## General punch list

- [ ] ~EditableObjectList: hanging "Plus" button doesn't naturally pick up same density as list~
  - Can’t repro, see comment
- [x] Remove frame async load/suspense flickering
- [x] (@thure) Remove custom slots from kai (e.g., ListItem icons)
- [x] (@thure) Root application menu (top right) to replace actions (bottom of Sidebar)
- [x] (@thure) Dense mode variant for all controls
  - [ ] Editable Table frame
- [x] (@thure) Standardize margins/spacing for all controls/lists, etc.
- [x] (@thure) Prefer controlled components (e.g., Dialog)
- [ ] ~(@thure) Standardize scroll container (see Radix)~
- [ ] ~(@thure) Support light/dark mode~
- [x] Settings panel/dialog
- [x] Home button (nav to /)
- [x] Registry jumps when last item remains selected (@zhenyasav)
- [x] Resolve autofocus drama (tooltip)
- [x] errors overflow error dialog
- [x] Input ref (e.g., programmatic focus); use to set focus in NotesTile
- [x] Controlled/uncontrolled Input error (EditableObjectList)

## Shell punch list [@zhenyasav]

- [x] PIN not working?
- [ ] Remove `join as` (single identity)
- [ ] Display username and spacename (not hex)
- [ ] Devmode set fake username
- [ ] Less font size variety
- [ ] Standard padding/header/button row
- [ ] Remove "back to spaces"

## Next

- [ ] Swipeable sidebar
- [ ] Mosaic
  - [ ] Horizontal/Vertical/Grid patterns
  - [ ] Complete kanban

**Comment by richburdon** [comment]
## Settings Panel/Dialog

<img width="819" alt="Screenshot 2023-02-21 at 12 44 01 PM" src="https://user-images.githubusercontent.com/3523355/220420627-817ddd3e-dca5-4393-ae98-547fb62a32c4.png">

**Comment by thure** [comment]
> Controlled vs uncontrolled pattern:
> 
> ```tsx
> const Dialog: FC<{ open, onChange? = (open: boolean) => void }> = ({ open: controlledOpen }) => {
>   const [open, setOpen] = useState(controlledOpen);
>   useEffect(() => setOpen(controlledOpen), [controlledOpen]);
> 
>   ...
> }
> ```

This won’t be necessary, [Radix’s Dialog’s open state is already controllable](https://www.radix-ui.com/docs/primitives/components/dialog). We should either forward all those props or proxy them with `useControllableState`.

**Comment by thure** [comment]
> EditableObjectList: hanging "Plus" button doesn't naturally pick up same density as list

`EditableList` is working as expected, please provide repro steps and screenshots.

<img width="412" alt="Screenshot 2023-02-24 at 16 41 38" src="https://user-images.githubusercontent.com/855039/221326022-e2f39d01-0bb1-4556-ac0f-c01c409d05dc.png">
<img width="422" alt="Screenshot 2023-02-24 at 16 41 29" src="https://user-images.githubusercontent.com/855039/221326023-6fcce417-a05e-482b-91cb-7c006cf92fc9.png">
<img width="402" alt="Screenshot 2023-02-24 at 16 41 01" src="https://user-images.githubusercontent.com/855039/221326024-0b94b867-c6a6-4e10-95ed-aafa369f753d.png">
