### ISSUE TITLE
2023-Q2 OKRs

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2509]
## Objective: Product readiness
> Owner: @zhenyasav 

- [ ] Stabilize API and SDK (#2378)
- [ ] Stable continuous integration, QA, and release process
- [ ] Operational observability and monitoring (logs, metrics, etc)
- [ ] Product observability (usage dashboard)
- [ ] Complete a self-serve onboarding and feedback paths (docs, sample code, discord, GH flows, ...etc)
- [ ] Feedback Triage process

## Objective: Product-market fit
> Owner: @zhenyasav

- [ ] Feedback collected from 10 qualified developers (with intention to build real commercial apps)
- [ ] Stretch: 3 qualified developer building apps with DXOS

## Objective: Developer engagement
> Owner: @zhenyasav 

- [ ] Launch material (blog + video + cross posts)
- [ ] Speak at at least 1 event this quarter
- [ ] Launch a DXOS blog
- [ ] Run at least 1 livestream
- [ ] Reach 500 total unique visitors to our properties

## Objective: Protocols/SDK Stability and Scale
> Owner: @dmaretskyi 

- [ ] Sync bots prototype (able to sync between offline users)
- [ ] MS-1 https://github.com/orgs/dxos/projects/19/views/1

## Objective: Dogfood the platform
> Owner: @zhenyasav 

- [ ] Daily internal use of Composer across team
- [ ] Observability of Composer in production (product usage dashboard)
- [ ] Public launch of Composer
- [ ] Stretch: 5 "active" external users

## Objective: Minimal Viable Team
> Owner: @richburdon @zhenyasav 

- [ ] Recruit Devrel lead
- [ ] Recruit Senior Protocols architect/lead
- [ ] Recruit Senior Apps developer
- [ ] Complete scouting programme

<hr>

### Bin
- [ ] Deploy a showcase of apps (e.g., Kai, IPFS, Notepad)
- [ ] Define a go-to-market hypothesis

### Refs

> https://www.atlassian.com/agile/agile-at-scale/okr

**Comment by richburdon** [comment]
Objective: Validate GTM product hypothesis (USP) for platform [zhenya]
- [ ] 1:1 feedback from 10 expert level founders/executives re SDK (product market fit)
- [ ] 1-3 qualified developer (teams) shipped app with N active users

Objective: Devrel Engagement [jonan]
- [ ] 100 developers using the SDK
- [ ] 100 apps deployed to KUBE
- [ ] 500 developers in Discord
- [ ] NN followers on Twitter/Blog ???
- [ ] presented at 5 events (IRL and virtual)

Objective: Production app (Braneframe) in Beta; explore "superapp" product hypothesis [zhenya]
- [ ] N 7-day active users

Objective: Able to support developer community [egor]
- [ ] support 100 developers/teams (KUBEs, bots)
- [ ] security peer review
- [ ] KUBE uptime SLA

Objective: ECHO Achieves minimal scaling requirements for developer community [dmytro]
- [ ] ECHO supports N peers with M items

**Comment by zhenyasav** [comment]
This is now tracked in a private repo
