### ISSUE TITLE
KAI Demo/QA Manual Testing Script

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#2578]
# QA Process

This can likely be stripped down for testing:

- Launch app: https://kai.dev.dxos.org in a dedicated Chrome profile
  - Reset everything (currently: Clear Cache extension)
- Create identity (first empty space should be autogenerated)
  - Set space name to "Test"
  - Generate test data (AppBar via menu)
  - Switch between visible frames (tabs)
  - Add tasks in Tasks frame (create / update distinct objects)
  - Add lots of tasks in rapid succession (exercise a rate)
  - View tasks in Mosaic and Kanban frames (mosaic, kanban pages also load the same data)
- Click invite (from sidebar)
  - Create and copy invite
  - Paste URL into side-by-side Incognito window and go through join sequence
  - See data replicated
- Go to Documents frame (on both windows)
  - Type a bunch of random text quickly on one line (both sides), then delete characters from another line; highlight and delete paragraph)
- Open Notes frame and create Note, drag it, observe replication both ways (exercises references)
- Open Table frame and select Tasks (type / schema introspection features work)
- Change space name, color and icon 
- test mobile join flows and replication
- test mobile multi-tab apps
- test device join flows (browser-browser, browser-cli)
---
- Open Chess frame (both sides) and create game
  - Left side plays white move (x2)
  - Right side plays black move (x2)
  - Right side enables Chess bot (via Registry)
  - Left side makes move and see automatic response (x2)
- Right side creates invitation and shows QR code
  - Join from iPhone and go through join sequence
  - Go to Documents frame and type text

Requirements to make obsolete:
- [ ] Playwright coverage of storybooks
- [ ] Playwright coverage of app
- [ ] Deployed version "dashboard" (link)

# Future

## Scenario 1

- Install DX Cli
- Join space from CLI
- Query objects

## Scenario 2

- View apps/modules from KUBE web console
- View logs (link to ops) from console
  - View signaling (related to demo)

## Scenario 3

- Deploy and play chess bot from CLI
- View from web observer

## Scenario 4

- Create app from CLI
- Deploy
- Load frame from registry

## Scenario 5

- Create bot from CLI
- Deploy
- Load bot from registry

**Comment by zhenyasav** [comment]
#2668 locates this `docs/docs/specs/v0/qa-script.md`
