### ISSUE TITLE
Reconcile withReactor and withReactorRef

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2627]
Mobx code for reference: https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/src/observer.ts

**Comment by zhenyasav** [comment]
- we resolved to rename this to `reactive` 
- agreed we should just always forward any ref inside this HOC making them one and the same

**Comment by richburdon** [comment]
Rename the HOC or hook (Reactor) or both?

**Comment by zhenyasav** [comment]
both
