### ISSUE TITLE
Composer remounts causing focus loss when others type

### ISSUE THREAD

**Issue by thure** [dxos/dxos#2660]

**Comment by thure** [comment]
Tried to repro, but had trouble connecting to a remote collaborator using local dev environment.

**Comment by thure** [comment]
I've attempted a fix in #2664, but I'm not sure if it resolves the issue.

**Comment by thure** [comment]
Attempted one more fix in #2665.

**Comment by thure** [comment]
And one more attempt in #2669.

**Comment by wittjosiah** [comment]
Resolved by https://github.com/dxos/dxos/pull/2787
