### ISSUE TITLE
Data support for presence cursors in composer

### ISSUE THREAD

**Issue by thure** [dxos/dxos#2662]

**Comment by thure** [comment]
Presence channel in Echo needs to be available to connect with TipTap CollaborationCursor: https://tiptap.dev/examples/collaborative-editing

**Comment by zhenyasav** [comment]
Slight adjustment to existing tiptap presence demo, let's do more what google doc does: show colored cursors with at most a dot on the top of them, and only when hovering (or when they move?) does it show the username label + icon

**Comment by mykola-vrmchk** [comment]
Working on it https://github.com/dxos/dxos/issues/2675
