### ISSUE TITLE
PWA routing on KUBE

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2667]
ok so kube + PWA is pretty broken right now it seems like it's hard for the browser to get the app updated when the service worker is installed and returns an old index.html from cache quickly. that old page will refer to old js scripts etc which will not exist on the server and will be redirected to the new version of index.html resulting in parse errors when e.g. javascript is expected. 

- redirect to `index.html` only when content type expected is `text/html` ?

We're also nesting the service worker toast inside all the providers making it inaccessible until all the other pieces work (it should be as near the top as possible so the user might have an opportunity to get an "update now" toast in case apps break like this.

- promote service worker toast closer to the root to allow apps to update

References:
- This blog from 3 years ago about [how deployment services make this work](https://hidde.blog/how-deployment-services-make-client-side-routing-work/)
- This current nextjs reference on [fallbacks and redirects](https://vercel.com/docs/concepts/projects/project-configuration#redirects)

**Comment by zhenyasav** [comment]
This should address:
- [ ] #2654 
- [ ] #2633

**Comment by dmaretskyi** [comment]
Also causes vault to break: iframe gets served with HALO main page instead of vault page

![image](https://user-images.githubusercontent.com/35851437/223415658-fe7173af-0900-4ec5-ba06-604af3ef8a34.png)
