### ISSUE TITLE
Joining a desktop peer can start it with stale data

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2697]
First user (inviter), followed by what an anonymous window saw upon joining
<img width="1334" alt="Screenshot 2023-03-08 at 6 12 33 PM" src="https://user-images.githubusercontent.com/3398896/223873662-86393944-d64a-45a4-9969-027ec7d90d12.png">
<img width="1334" alt="Screenshot 2023-03-08 at 6 12 36 PM" src="https://user-images.githubusercontent.com/3398896/223873713-aad5493f-3706-4295-9e6a-9c414469609c.png">

**Comment by dmaretskyi** [comment]
We've made a number of improvements to the invitation flow, lets reopen if the problem appears again
