### ISSUE TITLE
Github sync bot

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#2804]
- Syncable objects have a `foreignKey: "https://github.com/dxos/dxos/issues/2721"` property
- Bots scans the space for syncable objects and perfoms two-way sync
- Text document objects can sync to MD files in the repo, or issues, depending on the foreign key URL.
- Issues are synced using github graphql APIs: https://docs.github.com/en/graphql/reference/objects#issue https://docs.github.com/en/graphql/reference/objects#usercontentedit
- Bot can inspect issue edit history and timstamps to determine if the data on github is newer then in ECHO (echo stores timestamp from github).
- If github state is newer, bot should mutate the text in ECHO with mutations to specifically update changed regions of text (github gives us a diff).
- Bot stores the timeframe of the ECHO object in the issue during sync, either in metadata (if possbible), or in text body in `echoTimeframe=<base64EncodedTimeframe>` format.
- Bot can use the timeframe to determine if the state in ECHO is newer.
- If both github and ECHO state has changed since last sync point, YJS can merge the changes (e.g. pull guthub state into ECHO first, and then push the resulting state to github).
- Bot should watch for changes in the database and sync data to github when it's changed.
- Bot should be built in a thread-safe way, with debounce, expecting the objects to be edited live.

echoTimeframe=dGVzdGluZyAxMjMgMTIzIHRlc3Rpbmc=

**Comment by dmaretskyi** [comment]
Metadata (like echo timeframe) can be attached to issues through project items https://docs.github.com/en/graphql/reference/objects#projectv2item

Instead of storing the timeframe in the issue itself, we can store the timestamp of the last sync in ECHO and compare if the issue changed since then.

**Comment by richburdon** [comment]
As discussed, echo objects should have a `meta.keys` array/map with compound foreign keys `{ resolver: string, id: string }`, where the resolver is the DXN of the service.
