### ISSUE TITLE
Invitations failures

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2818]
Will — Today at 7:09 PM (Mar 23)
Are invitations currently broken @here? I'm getting
```
invitations-proxy.ts:107 Uncaught (in promise) AssertionError [ERR_ASSERTION]: undefined == true
    at Object.onAuthenticate (invitations-proxy.ts:107:9)
    at AuthenticatingInvitationProvider.authenticate (invitations.ts:90:26)
    at useInvitationStatus.ts:171:7
```
Seems like the observable’s invitation is undefined somehow…
It's fine for the inviter, but it's undefined for the joiner

**Comment by thure** [comment]
This was possibly caused by calling `acceptInvitation` too early. I'm not sure if “too early” is before there’s an identity on the device or some other moment.

The observable it returned would not fire any callbacks and never define its `invitation`.

**Comment by dmaretskyi** [comment]
@zhenyasav on standup with @thure and @wittjosiah, can we do a quick review of invitation callbacks?
