### ISSUE TITLE
Composer: required value was null or undefined

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2886]
<img width="1556" alt="Screenshot 2023-03-30 at 11 42 57 AM" src="https://user-images.githubusercontent.com/3398896/228891142-6b226aef-1dc4-4b50-8cb4-30907120178b.png">

**Comment by wittjosiah** [comment]
This is caused by a breaking change in the storage protobufs, fix for now is wipe the db, later obviously develop migrations
