### ISSUE TITLE
[react-ui@kai] Typography on iPad isn’t right

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2890]
![](https://cdn.discordapp.com/attachments/837688768872972358/1091031131316568114/image0.jpg)

**Comment by thure** [comment]
This doesn't look like Fira Code, the issue may resolve on its own as we resolve other devops issues.

**Comment by thure** [comment]
We should check if this repro’s in Composer

**Comment by zhenyasav** [comment]
seems to work fine now
