### ISSUE TITLE
[composer-app] Better notifications

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2892]
- Inviter is notified when joiner is ready to input an auth code: When the invites panel is dismissed but someone accepted an invitation and waiting for a veritifcation code, the user should be notified with some kind of notification to bring up the shell with one click
- Remove the ⚠ in the bottom-right

**Comment by thure** [comment]
_Toasts_…

**Comment by thure** [comment]
This was resolved long ago.
