### ISSUE TITLE
Better errors when in an http context

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3047]
This is happening when the app is served over http and SubtleCrypto is not available
![](https://cdn.discordapp.com/attachments/850444891104215091/1097567713469141036/image.png)

**Comment by zhenyasav** [comment]
we can instruct people about how to set up ssh tunnels in our docs and have the error provide a shortlink there

**Comment by wittjosiah** [comment]
https://github.com/dxos/dxos/pull/3084
