### ISSUE TITLE
[composer-app] Github browser extension

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3097]
@wittjosiah 

- [x] composer embedded mode
- [x] pass current url to composer in order to determine object
- [x] integrate content script with page navigation
- [x] handle conflicts in gh naively
  - should be able to detect when gh says the issue text changed
  - should not use issue text to override text of existing documents
  - later we'll look into various ways of handling diffs from gh
- [x] stop using `*` origin
- [x] add instructions

---

@thure 

- [x] space selection
  - need a ux flow for selecting spaces
  - need to store metadata about repo/space mapping, per member in space properties
- [x] improve visual integration of embedded experience
- [x] name documents something helpful
- [x] display stale comment error inside composer
- [x] restore open in composer button?
- [x] join a space if none found/share space button when editing?
- [x] when you’re picking a space, the options are badged by how many members of the space have already bound that space to the current github repo

**Comment by thure** [comment]
I've unassigned myself since the remaining items are complete, please reassign as needed.
