### ISSUE TITLE
composer embedded - join space dialog padding bottom

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3232]
the list of spaces is scrolled to bottom and there is not enough space below "join a space" to clear the fixed overlay buttons (invite, etc)

![Screenshot 2023-05-24 at 1 13 06 AM](https://github.com/dxos/dxos/assets/3398896/fa8aa726-bf24-4f89-a346-d7834728b647)

**Comment by zhenyasav** [comment]
@jessmartin maybe you still need a small thing to fix? this one will give you more tailwind-fu if you're not familiar with it. Lmk thoughts!

**Comment by jessmartin** [comment]
Love me some Tailwind. On it!

**Comment by thure** [comment]
Resolved by #3307
