### ISSUE TITLE
[composer extension] theme alignment with github

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3233]
tune color schemes of embedded mode for default gh editor colors both light and dark

**Comment by zhenyasav** [comment]
Jess says:
if we do go gray, we should use #F6F8FA to match the other subtle gray that's already used in the UI. And #22272E in dark mode.

**Comment by thure** [comment]
Resolved by #3308. I might have chosen slightly different colors from Github’s palette, please reopen as needed.
