### ISSUE TITLE
[composer-extension] Prevent “stale comment” from preventing saving to Github

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3237]
the question is: what to do when someone wants to click save in embedded composer, while others are also in editing mode on the same issue.

Proposal:
the ECHO object tracking the gh issue has a flag on it representing if it's "dirty" or "ahead" of the backing gh issue. 

Using this flag, the save button is either enabled or disabled. Everyone present writes to this flag setting it to true for every change. The saver of the issue sets this to false as soon as possible after the save (or optimistically before it returns). Last writer wins on updating this flag. Saver's calls always succeed because they are API calls to GH with a specific value for the description of an issue or comment. If they fail, we can ignore that and simply set the dirty flag again. 

This design should enable anyone saving at any time and no one to be restricted in any way from editing the issue freely at any time.

The last member with presence in the document can be warned about leaving changes without saving them to GH.

**Comment by zhenyasav** [comment]
Josiah and I discussed automating the "reload the window" trick where we restore state after the reload and are able to save, but it seemed like a can of worms as well.

**Comment by thure** [comment]
Resolved by #3254
