### ISSUE TITLE
[cli] cannot read properties of undefined on fresh install

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3247]
Nathan says: 
my (highly uninformed) sense is that there's some race condition between what is populating the config used in https://github.com/dxos/dxos/blob/main/packages/devtools/cli/src/base-command.ts#L61 and the invocation of such at https://github.com/dxos/dxos/blob/main/packages/devtools/cli/src/base-command.ts#L150
GitHub
[dxos/base-command.ts at main · dxos/dxos](https://github.com/dxos/dxos/blob/main/packages/devtools/cli/src/base-command.ts)
TypeScript implementation of the DXOS protocols, SDK, and toolchain. - dxos/base-command.ts at main · dxos/dxos
dxos/base-command.ts at main · dxos/dxos
wasn't able to figure out where/when that context gets populated with that configDir key

**Comment by zhenyasav** [comment]
Nathan and Jonan encountered this on their machines

**Comment by mykola-vrmchk** [comment]
Need to ask Jonan about repro

**Comment by mykola-vrmchk** [comment]
There is no race condition connected to config init. But there was a bug with config path, fixed it

**Comment by dmaretskyi** [comment]
## Repro steps

1. `npm i -g @dxos/cli`
2. Start daemon

**Comment by mykola-vrmchk** [comment]
@nferch was not able to repro it, but Dima unblocked it

**Comment by nferch** [comment]
@mykola-vrmchk I can still reproduce this one, https://github.com/dxos/dxos/issues/3330 is the one that I believe is fixed

**Comment by wittjosiah** [comment]
Seeing this here as well https://github.com/dxos/dxos/actions/runs/5256973213/jobs/9499069325#step:13:81

**Comment by mykola-vrmchk** [comment]
@nferch This should fix that error https://github.com/dxos/dxos/pull/3475
I tested it with `npm link`, it worked for me as expected

**Comment by nferch** [comment]
@mykola-vrmchk you could try the song-and-dance here: https://github.com/dxos/dxos/compare/main...nferch/npm_cli_smoketest#diff-1a5079bb84ca40f5409a2588a7bb187d5b61d3923704a6025f053ff5a719abc3R32

Also my PR to build and publish main was merged, but tests are failing: https://github.com/dxos/dxos/pull/3440

**Comment by mykola-vrmchk** [comment]
Bug is fixed
