### ISSUE TITLE
[composer] mobile sync failure after returning from 10m sleep

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3290]
had a composer space shared between ios safari and desktop chrome, and the mobile client went out of sync after it resumed from a 10m sleep. It came back from the lockscreen straight into the composer safari tab and was responsive but writes weren't propagating in either direction.

**Comment by wittjosiah** [comment]
Seems likely that webrtc connection is being shutdown when device is asleep and nothing is re-initiating that connection when the device wakes up
