### ISSUE TITLE
[sdk] Sync bug in stacks

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3299]
Able to repro in kai:

Add tasks to stack (the list is a echo object that is part of a stack); the list shows up in both peers, but edits to the list do not -- until another mutation triggers it.

https://user-images.githubusercontent.com/3523355/239028338-2a72d398-6ca5-4d87-a8eb-e6f1833b32a6.mov

**Comment by jessmartin** [comment]
Closing. We've completely replaced Stacks in Composer.
