### ISSUE TITLE
Reconcile config dirs

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3375]
- [x] Gather up all global const/ENV defs (to client-protocols)
- [x] #3516

Current config dirs:

```
~/.config/dx
~/.dx
~/.kube
```

Similar to our global config proto, I propose something like below, based on https://wiki.archlinux.org/title/XDG_Base_Directory

For example something like this:

```
~/.config/
  dx/
    client/
      profile/                        # Selected via DX_PROFILE env.
        default.yml
        test.yml
    kube/
      profile/
```

Notes:
- See https://wiki.archlinux.org/title/XDG_Base_Directory for `.cache`, `.local`, etc.
  - @nferch use `XDG_RUNTIME_DIR` for sockets, etc.? default to `/var/run/dx`?
- Resolve current `~/.kube` conflict with https://devopscube.com/kubernetes-kubeconfig-file/
- Note singular form of `profile` (reconcile for client/kube)
- @egorgripasov related, `/.well-known` in KUBE needs some attention; i.e., should only be used to discover metadata, not be service endpoints; e.g., `./well-knonw/dx/config`.

**Comment by richburdon** [comment]
Remove path from CLI config (default to `.local/store/dx/store`)

**Comment by nferch** [comment]
I think we need to rewind this one a bit. While I think we should strive to be consistent, un-astonishing, rational, and when possible, comply to existing standards and conventions, I think there's enough confusion and unclarity around the purpose and use case of the paths in question that make it difficult to make intelligent improvements around this sort of thing.

Is there any low-hanging fruit that we know is obviously causing problems or confusions that we need to fix right now?

**Comment by egorgripasov** [comment]
> Is there any low-hanging fruit that we know is obviously causing problems or confusions that we need to fix right now?

it feels like `~/.kube` folder collision could cause some issues
Note: it contains not only config, but all other assets that are used by KUBE, e.g. IPFS storage, KV storage used to store app defs, etc
as a starting point, we could just rename / move it to something else
@nferch @richburdon any preferences?
