### ISSUE TITLE
[marketing] set up blog

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3432]
we have a blog plugin on our docs site, we should just decide where we want to host the blog and how we should do the first few posts

**Comment by jessmartin** [comment]
@zhenyasav do you have a preference for how we host the blog? I really don't care at all what tech we use, just that the fonts/colors/etc be consistent with the doc site to avoid a proliferation of different "brand styles."

**Comment by jessmartin** [comment]
@zhenyasav I changed this to be assigned to you, but LMK if you need help.

**Comment by jessmartin** [comment]
Ok, we decided to go with Ghost. A few todos left:

- [ ] Post the remaining post.
- [ ] Embed a "subscribe to get emails with updates" form in the website
- [ ] Add "Blog" to the nav in the website
