### ISSUE TITLE
[composer-embedded] changing any issue metadata while editing kicks composer out

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3480]
when you're editing an issue with composer, assigning a label kicks composer out of the DOM and GitHub goes back to showing the old issue description.

Composer should stay put through any metadata changes

**Comment by wittjosiah** [comment]
@zhenyasav I reproduced this, however this is the current behaviour of github without composer extension as well: if you edit labels it closes the issue editor and goes back to the rendered issue. I'd consider this a bug with github more than the extension as we're just tapping into their existing markup.
