### ISSUE TITLE
Firefox browser does not work

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3551]
**Describe the bug**
It is not possible to use Firefox due to browser limitations.

**To Reproduce**
Try to join an identity or a space in Composer using the Firefox browser.

The invitation flow stalls when a PIN is not generated on the existing device side.

**Expected behavior**
The invitation flow completes and I'm able to join a space in Composer.

**Comment by wittjosiah** [comment]
@nferch thanks for making this, I've been using https://github.com/orgs/dxos/projects/20/views/5?pane=issue&itemId=24688358 to track firefox support so far. Until a couple weeks ago it didn't support module workers so the vault didn't work and I've not yet had a chance to try that out and look into any potential further issues.

**Comment by nferch** [comment]
@wittjosiah thanks for linking that. Do you think it's likely that there's other issues such that I should convert this one to an epic and link that other one, or should I remove this one and link to the other one directly?

**Comment by wittjosiah** [comment]
@nferch Not sure how many other issues there might be. We try to run unit tests for most of the packages in the monorepo in firefox so generally we should be a good shape. Clearly there's at least one other issue besides the shared worker though because it doesn't seem to be working today even if you upgrade.

**Comment by nferch** [comment]
https://github.com/dxos/dxos/issues/3564

**Comment by jessmartin** [comment]
Firefox browser works now, (except in private mode, where it will never work because they don't support storage). 

Will update docs.
