### ISSUE TITLE
Devtools improvdements

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3595]
- [ ] Reset sometimes doesn't work (see below)
- [ ] Catch and display errors (e.g., above)
- [ ] Remove "waiting" indicators/circles
- [ ] Pre-select first space for selectors
- [ ] Standard padding in content panels (e.g., around tables)
- [ ] Items table (ID, type columns; remove text content)
- [ ] Simple table for signal info
- [ ] Highlight selected row in master/detail panels
- [ ] Render JSON buffers with just length (e.g., credentials)

## Aurora bugs
- [ ] search box border when highlighted (e.g., items)
- [ ] selector popup is transparent (e.g., feeds)

![Image](https://user-images.githubusercontent.com/3523355/250391152-fc13c2d2-b817-4b04-8349-e3ed4bfb70f5.png)

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/issues/4701
