### ISSUE TITLE
[composer] opening link to a space I am not in leaves blank screen

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3597]
this is a link to composer.dev which opened with my non-work browser profile and should have yielded some kind of 404 but is just blank
![Screenshot 2023-07-03 at 9 51 33 AM](https://github.com/dxos/dxos/assets/3398896/9dd6c885-05f1-451d-a320-50671bd0232f)

This is another one where prod composer opened with my non-work profile and shows spaces but not one document selected and state is kind of undetermined. It should instead show either "loading" or "404".
![Screenshot 2023-07-03 at 9 52 15 AM](https://github.com/dxos/dxos/assets/3398896/740d359d-9765-4b82-ba15-0a84a72e749f)

**Comment by wittjosiah** [comment]
@zhenyasav closing this as it's very old and I believe this case is now handled by better fallbacks.
