### ISSUE TITLE
[apps] Apps fail to load in an incognito window

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3608]
**Describe the bug**
When someone uses the app and opens it in Incognito, it fails in surprising ways.

![image](https://github.com/dxos/dxos/assets/27258/6b305675-d0b6-427b-8735-606a990fc026)

**To Reproduce**

- Open a DXOS app in an Incognito window
- Open the console. there ya go.

**Expected behavior**

DXOS apps should be able to work in Incognito. But maybe there's a technical limitation to accessing IndexedDB? I'm not sure if it should even work, so maybe we need better error messages.

**Additional context**
Add any other context, screenshots, hypothesis, etc. about the problem here.

**Comment by wittjosiah** [comment]
@jessmartin @zhenyasav I think this is resolved now, could you confirm?

**Comment by jessmartin** [comment]
Works for me in Chrome (Arc) and Safari. Closing.
