### ISSUE TITLE
Make more of our Discord public

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3636]
Rich and I talked about the idea of making our Discord feel more active (and transparent) by making most of our development channels public.

## Motivation

Our Discord is pretty active... if you're on the DXOS team. Our goal with the "open" nature of this project is to appear to be, from the outside, an active and vibrant project in order to give people confidence that the project is moving forward. We also need to "work in public" to create a larger engagement surface area that allows for people to selectively engage (pull) when they're interested.

Much of what we're talking about could easily be public and is of interest to people following along with the project. Let's open things up a bit!

## Proposal

Here's a first-cut suggestion.

### Private/Team
- monologues (except for Rich, who prefers public)
- #team 
- #alerts 
- #recruiting 
- #dev-null (I assume this is some kind of shared pasteboard?)

### Public
- #announce (announcements!)
- #general (greet people and introductions)
- #feedback (it's a forum)
- #events (it's a forum - should we just delete?)

**Functional Areas** (maybe we shake these up?)
- #ops 
- #devops (how is this diff from #ops? collapse #ops into #devops?)
- #devrel 
- #protocols 
- #kube 
- #hardware 

**Fun**
- #interesting
- #random
- #design
- #music
- #ai

**Comment by nferch** [comment]
### Private/Team
- monologues (except for Rich, who prefers public)
- #team (with perhaps apps and protocols specific-topics as threads?)
- #feed (we seem to be moving toward putting updates in the board, but people still use this, and i like the distinction between status updates and actual team issues)
- #leads (rename #strategy)
- #recruiting 
- #dev-null (I don't understand the purpose either)

### Public
- #announce
- #general (should rename this to #introductions? most of the "meaty" conversations tend to scroll off pretty quickly)
- #feedback (change to normal channel and pin Github issue form? or just remove completely in favor of #questions)
- #questions (why was this removed? it seems the most active)

**Functional Areas**
- #apps-sdk-plugins (could see separating, but in general I think fewer is better. and maybe "#apps" encompasses them all?)
- #platform
- #devrel (or #outreach? #community?)
- #ops (move alerts here. don't particularly like the name, #runtime or #prod doesn't seem much better. over time i'd like this to be discussion for everyone to discuss running and using the platform, not just operation of our infra.)

**Fun**
- #interesting
- #random
- #design
- #music
- #ai

--
Some other random thoughts:
* We should link or include the code of conduct from our repo
* Roles/names/avatars are also public
