### ISSUE TITLE
UI framework feedback

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3667]
## Bugs

- [ ] #3765
- [x] https://github.com/dxos/dxos/issues/3758
- [x] #3742, Cannot click "create space" icon after dismissing the "join space" dialog with escape

## Cosmetic

- [ ] Text "jiggles" on first render of large documents as if CSS were late to load/be applied [see below]
- [ ] Text "jiggles" when highlighting (from other user); don't change highlight color per user
- [ ] Select control error if set value to undefined after it is initially defined.
- [ ] Value visible in Select control "jumps" (not aligned) when popped up (should remain in place). [See devtools Feeds]
- [ ] Select popup doesn't scroll when runs offscreen.
- https://github.com/dxos/dxos/pull/3847
  - [ ] Select control fixed width
  - [ ] Larger base font size for mobile
  - [ ] Toolbar (see Playground controls and AlertDialog)
  - [ ] Button icons should resize based on density (remove custom `getSize()` class defs througout)
  - [ ] Button ghost variant vs. elevation
  - [ ] Surfaces and factoring out colors
  - [ ] Defaults: e.g., remove is-full for input, no-shrink for checkbox
  - [ ] Allow theme plugin to configure base color (e.g., primary/secondary button color)

## Feature Requests

- [ ] Standardize main plugin window (e.g., gutter, header, scrolling -- see below)
- [ ] Popup panel to rename object; make it extensible
- [ ] Auto-resize TextArea; with minimal border
- [ ] Prevent drag of certain graph nodes (e.g., Debug item always at the bottom)
- [ ] Enable drag between spaces
- [ ] Network status indicator (e.g., green dots)
- [ ] Settings panel (e.g., user settings and debug settings)
- [ ] #3708
- [ ] Scroll areas with styled scrollbars (how to do this for plugin main page?) radix? e.g., see Threads
- [ ] Deferred visibility of fallback waiting icon; replace with minimal progress line
- [x] Sidebar title ellipsis/wrapping is non-stable (switches based on other renders) in sidebar
- [ ] Add icon to Input (e.g., Searchbar)

## Design

- [ ] Alt UX libs that use radix (e.g., augment or remove dependency on internal components)
  - [ ] E.g., should we be recreating Button and Input components? (e.g., https://www.youtube.com/watch?v=CLkxRnRQtDE&t=3512s https://catalyst-ui.com/docs/select [this might be different])
- [ ] Rather than wrapping dnd-kit could we extend it to preserve their user base?
- [ ] Reduce boilerplate classes from aurora? (e.g., define common higher-level themed components -- e.g., toolbar)
  - no classes required for button, text, etc. 
  - e.g., https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-kanban/src/components/KanbanMain.tsx#L43
- [ ] Standard colors (panels, text)
  - See hack: https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-theme/src/styles.ts

## Plugins

- [ ] Additional sidebar in SplitView for threads
- [ ] File plugin for threads (chooser)
- [ ] DND for Kanban/Drawing
- [ ] DND for drawing (file plugin)
- [ ] Presenter plugin (full screen surface)
- [ ] Markdown preview plugin (with split screen)

### Standard gutter/header for main content -- and position for sidebar open button

![Image](https://github.com/dxos/dxos/assets/3523355/83e13bec-2cc2-4848-a272-9ee8cab82111)

### Jiggling text

https://github.com/dxos/dxos/assets/3523355/170d48f1-1876-4793-bd7a-139882e219a5

**Comment by thure** [comment]
> Reduce boilerplate classes from aurora? (e.g., define common higher-level themed components -- e.g., toolbar)

I can appreciate _reducing_ boilerplate, however many of the styles applied to `KanbanMain`’s `Input.TextInput` are worthwhile non-default layout features, and, other than those, there are only padding details that may not need to move as far upstream as `aurora`.

Going forward, providing as many examples as possible where a certain set of classes are used repeatedly will help motivate a change that moves those styles upstream. If it’s easier, you can provide the string of classes to search for and the number of instances.
