### ISSUE TITLE
[agent/cli] Zhenya's feedback

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#3680]
* `dx halo` and `agent` seem to have amnesia, restarting after installing `@latest` cli reported "identity not initialized" when `dx halo`
reason/fix(@mykola-vrmchk): Probably we introduced breaking changes in the config path and rewrote the path to Echo data, that should be one-time thing, I can not reproduce it
* can't tell if agent is doing anything
* `halo join` hangs after PIN code
reason(@mykola-vrmchk): I suspect it was using the wrong signal server. Needs more investigation 
* `dx agent start` seems to hang, I can't tell if it's going to run in the background or not. After terminating it, `dx agent list` clearly showed it was still running which further supports that `dx agent start` should return quickly and there should be another mode for running the agent on the current shell (as opposed to in the background).

**Comment by richburdon** [comment]
- What version of the dx CLI are your running? From npm install or source?
- Please run `dx config --json` and copy here.
- Please run `dx debug stats --no-agent --json` and copy here.
