### ISSUE TITLE
[agent/cli] Jess's feedback

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#3740]
- ### the fact that the `dx` runs some commands with an agent and others without is a bit confusing. How can we make it clear beforehand that something requires an identity/agent so that users of the CLI aren't surprised?
  - [x] add user-friendly errors `Identity required`
- ### join flow worked great! there was no confirmation when it completed though. Would have expected a congratulations or something.
  - [x] make success message user friendly
- ### `dx halo` outputs an identity key. I would have expected a bit more general information about my HALO: identity name, list of spaces, list of apps, size of data persisted, something like that.
  - [x] remove `dx halo` default command
  - [x] add `dx halo identity` command that returns your identity and profile
- ### `dx space` hangs and never completes.
  - [x] remove waiting for spaces
- ### `dx app list` throws an error trying to connect to localhost: Error: connect ECONNREFUSED `127.0.0.1:80`
  - [x] add user friendly error if kube publisher is not available
- ### the whole `dx plugins` thing is weird. dx plugins tells me I don't have any installed. I can't list my plugins. But dxos plugins -core lists a few possible plugins (which have really weird and non-obvious names).
  - [x] Deprecate most of unused `functions` commands
- ### `dx device list` is confusing. Shouldn't I be able to name my device? What is kind?
  - [ ] Add device metadata
- ### In general, none of the nouns are defined in the `help` command so I'm left on my own to figure out what they are.
  - [x] Improve help
- ### I can't tell if my agent is doing anything. I can list and see it's running, but the inability to inspect it is weird.
  - [x] Add agent status (available in devtools now)
- ### ` --no-agent         Auto-start agent.` ??? shouldn't that be "does not auto-start an agent."?
  - [x] Fix typo in help
- ### Where is my data being synced to exactly? I assume agent is persisting stuff, but where? Where's my credible exit? 😛
  - [x] Add storage path in `dx config` command

[dx-cli-agent-logs.txt](https://github.com/dxos/dxos/files/12179648/dx-cli-agent-logs.txt)

**Comment by mykola-vrmchk** [comment]
cc @jessmartin

**Comment by jessmartin** [comment]
Thanks for creating this issue! Eventually, we should probably split some of them into separate issues as they are more about the CLI than agents. But good to have them all in one place that's not Discord. 😄
