### ISSUE TITLE
Improve Protobuf Code

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#3760]
- Reduce protobuf size
- Fix `Use of eval in "node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.`
- Consider switching to protobuf-ts or protobuf-es

**Comment by dmaretskyi** [comment]
https://github.com/timostamm/protobuf-ts
https://github.com/bufbuild/protobuf-es

**Comment by dmaretskyi** [comment]
- Code splitting
