### ISSUE TITLE
Milestone: The Strange Loop Release

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3768]
**GOAL: Demo awesome stuff at Strange Loop '23.**

**Dates:** September 21-23, 2023

- Focus on a week-to-week plan approaching strange loop
	- countdown to Strange Loop

## Things to launch:

Zhenya:
- Composer + HALO design overhaul
- Low-level APIs
- Plugins SDK (including Aurora)

Jess:
- Sample Apps
    - Tasks
    - Others?
- Docs
- Website?

Nathan:
- Performance
- Stable agents

Rich:
- Plugins

**Comment by zhenyasav** [comment]
closing in favor of #3869
