### ISSUE TITLE
Marketing and Operations Tasks

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3769]
- Help schedule the next three [Tools for Thought Rocks](https://www.youtube.com/c/ToolsforThoughtRocks) events (they're about super apps)
  - (I've facilitated TFT rocks for the last 2 yrs. About 30-50 people show up. The only reason I stopped was admin overhead. We can "sponsor" TFT Rocks events through the use of my time, giving me a chance to give a quick shout-out to DXOS. This is a setup for a launch venue for Composer!) 
  - invite speakers
  - find a time/date that works for all speakers
  - publicize on social media
  - create the luma event
  - post recordings to youtube
  - edit recordings to have appropriate speaker descriptions
- [x] Set up a DXOS Mastodon account
  - pick an appropriate server
  - sign up and add all of the appropriate meta (description, profile photo, links, etc)
  - make it so that typefully somehow posts to mastodon as well
  - follow some initial folks
- Clean up and post DXOS videos
  - update descriptions with chapters and a summary
  - edit the generated transcript
  - post the video to the DXOS blog with generated transcript
    - add a header photo for the blog post
  - schedule Z + J to have another fireside chat
  - handle the post-processing on the video
- For each blog post
  - pick a header image
  - convert to a tweet thread and schedule in typefully
  - post to #announcements in discord? #blog channel?
- Event logistics
  - book lodging for strangeloop
  - book lodging for ACM SPLASH
- design and order swag
  - deliver it to strangeloop for localfirst event
  - deliver care packages to Nick Basile and other early developers

**Comment by jrusshasyourback** [comment]
@jessmartin **I spent a good chunk of time today doing Mastodon research - lots of learnings that I will share + document shortly** 

**From the long list you shared, there were only 2 company (+ 1 person) who had Mastodon accounts:** 
https://mas.to/@tldraw
https://mastodon.world/@tangentnotes@indieapps.space
https://mastodon.world/@taylorhadden@mastodon.social

_Is [Val.town](http://val.town/) run by Sebastian De Deyne? If so, he is the 4th Mastodon account: https://mastodon.social/@sebdd_

**A handful of the companies from the list you shared have an automation like this:**  https://mastodon.world/@rem_note@bird.makeup "This account is a replica from Twitter. Its author can't see your replies. If you find this service useful, please consider supporting us via our Patreon."
_If you want to engage with users on Mastodon, I don't recommend [@bird.makeup](https://bird.makeup/)._

Questions: 
**Which topics from [this list](https://fedi.directory/) are most important to what DXOS does?** Below are some suggestions: 
[Business](https://fedi.directory/tag/business/)
[Linux](https://fedi.directory/tag/linux/)
[Linux Distros](https://fedi.directory/tag/linux-distros/)
[Privacy](https://fedi.directory/tag/privacy/) 
[Software Development](https://fedi.directory/tag/software-development/)
[Tech](https://fedi.directory/tag/technology/)
[Tech New](https://fedi.directory/tag/tech-news/)

**Same question with this list: [Trunk](https://communitywiki.org/trunk). Here are my guesses:** 
[Devops](https://communitywiki.org/trunk/grab/Devops)
[Engineering](https://communitywiki.org/trunk/grab/Engineering)
[Linux](https://communitywiki.org/trunk/grab/Linux)
[Operating Systems](https://communitywiki.org/trunk/grab/Operating%20Systems)
[Ruby](https://communitywiki.org/trunk/grab/Ruby)
[Social Innovation](https://communitywiki.org/trunk/grab/Social%20Innovation)
[Privacy](https://communitywiki.org/trunk/grab/Privacy)

_Check out how easy it is to get verified on Mastodon?!_
<img width="755" alt="Screenshot 2023-08-08 at 12 24 38 AM" src="https://github.com/dxos/dxos/assets/141656370/cc866811-7a05-4a6b-996c-f140062ca644">
