### ISSUE TITLE
ECHO TextModel bugs

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3774]
Issues
- [ ] Text models are "decoupled" from mutation stack when first created (composer only -- not kanban items). On reload they are "live".
- [ ] Implicit vs. explicit `new Text()` construction for `dxos.schema.Text` fields (creates additional object).
- [ ] Text state machine `_subscribeToDocUpdates` is called on each mutation.
- [ ] Multiple text objects are created when a composer plugin is created:

![Image](https://github.com/dxos/dxos/assets/3523355/447d9425-73c8-41d4-a58b-9af22f0af52c)

Repro
- Start `labs-app` from `main`
- Open in incognito and create identity
- Create multiple documents with content
- Content is not saved when switching files
- Copy content into document: after switching additional characters are visible

https://github.com/dxos/dxos/assets/3523355/6802d550-21bd-43c1-8eca-5386f0b09b84

Mutations stop

https://github.com/dxos/dxos/assets/3523355/62280f69-1ce5-4c27-8ce4-35331c05fb50

Frozen object

https://github.com/dxos/dxos/assets/3523355/79c374d2-e1d7-48d0-96cd-a12dcdd290a4

- Separate plugin bug (@thure)
  - Drag content into stack (content is temporarily duplicated)
  - DND in sidebar logs errors with missing items

https://github.com/dxos/dxos/assets/3523355/ed663752-d42e-4831-b900-567d43266004

**Comment by mykola-vrmchk** [comment]
Could not repro "Content is not saved when switching files"

**Comment by mykola-vrmchk** [comment]
Could not repro "Mutations stop"

**Comment by mykola-vrmchk** [comment]
@wittjosiah fixed those ones ^
