### ISSUE TITLE
Performance Benchmarking

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3802]
## Goals

- Determine current performance envelop (e.g., space size, # peers, perf. degradation over time/mutations)
- Product mitigations (e.g., warnings?)
- Automatic agent-based epoch generation

## Active

- [ ] #3826
- [x] #3827
- [ ] #3828
- [ ] Upgrade testbench to systematically test the scenarios above (multi-peer replication) with time-series data
- [ ] Simulate very large spaces with many spaces and peers
- [ ] Upgrade testbench to run with agents configured to automatically create epochs.
- [ ] #3821
- [ ] https://github.com/dxos/dxos/pull/3958

## Backlog

- [ ] Detect node version errors
- [ ] Detect if devtools is detached (agent stopped); poll to restart; show status in sidebar (heartbeat)
- [ ] Browser vs. node tests (run testbench in playwright?)
- [ ] Benchmark filestore and crypto tests in node/browser
- [ ] Access devtools from composer app (need settings plugin: https://github.com/dxos/dxos/pull/3804)
- [ ] Pass LOG_FILTER to agent
- [ ] Rerun tests with epoch monitor (remove from CLI debug generate)
- [x] Add `/profile/` path part to all file locations for CLI/agent
- [x] Open/close space from CLI
- [x] Map feeds to spaces in diagnostics message
- [x] Live agents list
- [x] Add Space list panel to devtools
- [x] Standardize diagnostics across devtools/cli
- [x] Exit CLI immediately after invitation (before sync completes) https://github.com/dxos/dxos/pull/3806
- [x] Make `space invite` consistent with `halo share` invitation command https://github.com/dxos/dxos/pull/3805
- [x] Add labs to prod (set-up CNAME for labs.dxos.org)
- [x] Show status of spaces in `dx space list` (don't wait for ready)
- [x] Random generator CLI command: https://github.com/dxos/dxos/pull/3805
- [x] Add diagnostics tab in devtools
- [x] All CLI commands wait until all spaces are ready (and timeout otherwise). Option for `--no-wait`

## Bugs

- [x] Diagnostics hanging.
- [ ] Stale agent (`dx agent restart --force` doesn't always work -- see grab below).
- [ ] Agent gets stuck with timeout error; restart doesn't help. (space list fails also -- unless "live")
  ```dx space share --no-auth```
  ```Error: Timeout waiting for space to be ready: 60,000ms [still processing?]```
  NOTE: Added `--no-wait` flag as work-around.
  NOTE(mykola): probably space is still replicating, and it is not safe to share it with not ready status

- [ ] Detools Fails to open/close space from devtools; OK after reload.
  ```Error: Request was terminated because the RPC endpoint is closed.```
- [ ] CLI error if agent stopped/restarted during `dx list --live`
  ```Error: Request was terminated because the RPC endpoint is closed.```
- [ ] Constant storage slow warnings.
  ```packages/common/random-access-storage/src/common/file.ts:55 WARN Slow storage operation { type: 'node', operation: 'write', elapsed: 85.43716698884964 }```
- [ ] Timed out (once) while syncing 8 peers
    ```packages/core/mesh/teleport-extension-gossip/src/gossip.ts:60 ERROR Error: Connection timed out
    at Object.onTimeout (/Users/burdon/Code/dxos/dxos/packages/core/mesh/teleport/src/teleport.ts:46:20)
    at /Users/burdon/Code/dxos/dxos/packages/core/mesh/teleport/src/teleport.ts:265:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)```
- [ ] Error if attempt to start agent manually if already running (dx agent start -f --ws=5001)
  ```Error: EAGAIN, Resource temporarily unavailable```
- [ ] CLI timeout running `dx list` if slow to startup (set timeout)
- [ ] Benchmark YJS/other p2p databases?
- [ ] Agent stop replicating with an error 
```packages/core/mesh/teleport-extension-replicator/src/replicator-extension.ts:240 WARN replication stream error {
  extensionInfo: {
    initiator: [33mtrue[39m,
    localPeerId: <PublicKey 049ae4b3>,
    remotePeerId: <PublicKey 04c836ee>,
    feeds: [
      <PublicKey 040e3cae>,
      <PublicKey 046d141d>,
      <PublicKey 04d23b47>,
      <PublicKey 042ee0db>,
      <PublicKey 0484b950>,
      <PublicKey 044aff42>
    ]
  },
  err: Error: Request timeout
      at Peer._onrequesttimeout (/Users/mykola/Documents/dev/dxos/node_modules/[4m.pnpm[24m/hypercore@9.12.0/node_modules/[4mhypercore[24m/lib/replicate.js:339:16)
      at Timeout.call [as _onTimeout] (/Users/mykola/Documents/dev/dxos/node_modules/[4m.pnpm[24m/timeout-refresh@1.0.3/node_modules/[4mtimeout-refresh[24m/refresh.js:25:18)
  [90m    at listOnTimeout (node:internal/timers:566:11)[39m
  [90m    at processTimers (node:internal/timers:507:7)[39m,
  info: { feedKey: <PublicKey 046d141d>, download: [33mtrue[39m, upload: [33mtrue[39m }
}
```
- [ ] Agent restart error.
```
▶ dx agent stop --force
Force stopping agent test-7
Error: Agent is stale (restart with
'dx agent restart --force')

[test-7] Code/dxos/dxos main ✔                10m
▶ dx agent restart --force
Error: Timeout waiting for agent.
    at ForeverDaemon.stop (/Users/burdon/Code/dxos/dxos/packages/core/agent/src/forever/forever-daemon.ts:177:14)
    at ForeverDaemon.restart (/Users/burdon/Code/dxos/dxos/packages/core/agent/src/forever/forever-daemon.ts:185:5)
    at /Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/agent/restart.ts:32:29
    at Restart.execWithDaemon (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/base-command.ts:343:23)
    at Restart.run (/Users/burdon/Code/dxos/dxos/packages/devtools/cli/src/commands/agent/restart.ts:31:16)
    at Restart._run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_d2gyhxeuxd6tnmgqdyixls47tq/node_modules/@oclif/core/lib/command.js:117:22)
    at Config.runCommand (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_d2gyhxeuxd6tnmgqdyixls47tq/node_modules/@oclif/core/lib/config/config.js:329:25)
    at Object.run (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/@oclif+core@2.9.4_d2gyhxeuxd6tnmgqdyixls47tq/node_modules/@oclif/core/lib/main.js:89:16)
```

## PRs

- https://github.com/dxos/dxos/pull/3796
- https://github.com/dxos/dxos/pull/3815

### Build set-up:
- Labs (serve with vault)
- Devtools (target labs: http://localhost:5174/?target=vault:http://localhost:3967/vault.html#/client/diagnostics)
- NPM watch
- CLI
```bash
dx agent stop --all
dx reset --force --no-agent
dx debug diagnostics --json --truncate
dx halo join
```

<img width="1728" alt="Screenshot 2023-08-02 at 5 39 03 PM" src="https://github.com/dxos/dxos/assets/3523355/52d8c65e-5893-42ee-94b0-d813448e2090">

### Labs Debug Plugin

<img width="1728" alt="Screenshot 2023-08-02 at 5 39 20 PM" src="https://github.com/dxos/dxos/assets/3523355/af54bbc1-c06e-4de2-8cc3-9a56c3eeeb74">

### Devtools

<img width="1728" alt="Screenshot 2023-08-02 at 5 39 28 PM" src="https://github.com/dxos/dxos/assets/3523355/98556ae5-b238-4515-903a-a6eb1950734c">

### Errors

<img width="1565" alt="Screenshot 2023-08-06 at 7 48 27 PM" src="https://github.com/dxos/dxos/assets/3523355/ab8d26fa-06fa-432f-8083-9645358bc24e">

**Comment by richburdon** [comment]
## Methodology

1. Open labs
2. Reset and create new identity and space
3. Create a stack with 5 document sections
4. Open the debug plugin page
5. Set the mutation interval to 100ms and start the generator
6. Periodically refresh the diagnostics until it reaches 1000 mutations the stop the generator

<img width="1726" alt="Screenshot 2023-08-02 at 5 55 08 PM" src="https://github.com/dxos/dxos/assets/3523355/5c46b1d8-33ba-4e79-a9a4-cdeacacdb95c">

<img width="1728" alt="Screenshot 2023-08-02 at 5 49 25 PM" src="https://github.com/dxos/dxos/assets/3523355/beabd438-e3ec-40cd-b730-fd5b466fcb4b">

<img width="1728" alt="Screenshot 2023-08-02 at 5 49 12 PM" src="https://github.com/dxos/dxos/assets/3523355/b48fc011-049b-48ce-95f4-e13948d6ce34">

<img width="678" alt="Screenshot 2023-08-02 at 5 49 44 PM" src="https://github.com/dxos/dxos/assets/3523355/d42666b2-e97c-4dff-9777-e214276f690e">

**Comment by richburdon** [comment]
## Uploading

1. Download a space
2. Reset the profile and create a new space
3. Upload the space

Uploading the "DXOS" Space
- 150K file size
- 100 objects (50 documents)
- Upload processing time: roughly 7s
- Startup time after upload: 850ms
- Replication time to new peer: roughly 7s

**Comment by richburdon** [comment]
Syncing between two CLI peers.

https://github.com/dxos/dxos/assets/3523355/db5c0df2-699c-4033-96cd-cb939114ec70

**Comment by richburdon** [comment]
- Pinless and no-auth invitations

https://github.com/dxos/dxos/assets/3523355/62e9f59c-78b2-438e-ac5e-15bfd5c3feee
https://github.com/dxos/dxos/assets/3523355/0c104a30-8562-447f-b936-66f394f5a443

**Comment by mykola-vrmchk** [comment]
# Live table demo
https://github.com/dxos/dxos/assets/36420699/fdba9ea7-cd1e-4a86-abec-c9a5eb9a76e6

**Comment by richburdon** [comment]
### Initial setup:
- Create 8 peers and 8 spaces
https://github.com/dxos/dxos/assets/3523355/5d5cdf3a-bbf4-462b-bbca-25451fed712a
- Join 8 peers (1 per space)
https://github.com/dxos/dxos/assets/3523355/61d23fef-e787-4aae-a8d4-ca035ae6d0f9

### Syncing
- 100 objects per space (100ms interval)
https://github.com/dxos/dxos/assets/3523355/f316aaad-457f-48cc-a5e0-8053632e841b
- 10,000 objects per space (100ms interval) [LOW RES 5m]
https://github.com/dxos/dxos/assets/3523355/c6040976-bee0-410d-927c-263cc54b3ca7
- Fully synced
<img width="1728" alt="Screenshot 2023-08-05 at 11 26 32 AM" src="https://github.com/dxos/dxos/assets/3523355/d0e89c3b-74a9-4037-b43c-80b88b0a0050">

### Startup after 10,000 mutations
https://github.com/dxos/dxos/assets/3523355/2ae4c86e-df9f-4e00-874a-d9ccb5f1425c

**Comment by richburdon** [comment]
- Testing 12 concurrent peers all connected to the same space and writing at the same time.
- 2 out of 12 peers throw a batch timeout.
- should retry.

<img width="1728" alt="Screenshot 2023-08-05 at 3 50 33 PM" src="https://github.com/dxos/dxos/assets/3523355/8117faa2-36e0-4a4b-a0f6-ade02e96c73c">

**Comment by dmaretskyi** [comment]
`batch commit err` shouldn't be related to the network. It's just writing to disk. We could also remove 3 second timeout

**Comment by richburdon** [comment]
Latest test:

https://wormhole.app/vrE0m#_6uz62QMZPGlufDHK3OWpg

- 5,000 mutations
- 100s to replicate
- 1M storage
- average throughput 20K/s

**Comment by richburdon** [comment]
<img width="1728" alt="Screenshot 2023-08-23 at 10 20 25 PM" src="https://github.com/dxos/dxos/assets/3523355/8469d748-f98f-419d-b778-3303149b06f0">
