### ISSUE TITLE
macOS WebRTC deadlock

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3828]
Under certain workloads with multiple peers/swarms, Node will deadlock and the Node eventloop will become unresponsive.

## Repro:
- run the `runTransport` test on `@dxos/kube-testing` with 6 agents and 4 swarmsPerAgent (2 agents / 2 swarmsPerAgent should pass)
- run test on `@dxos/network-manager` (e.g. `nx test network-manager $RANDOM`) on `dmaretskyi/webrtc-hang-test` (COUNT = 20 should pass)

## Issues
- [ ] Unit test with varying connection count using transport testbench
- [x] Research https://www.npmjs.com/package/node-datachannel (reach out? https://www.linkedin.com/in/dogan-murat)
- [x] Research https://github.com/libp2p/js-libp2p/tree/master/packages/transport-webrtc
- [x] Add libdatachannel transport https://github.com/dxos/dxos/pull/3920

**Comment by nferch** [comment]
Forked `@cubicleai/wrtc` (which seems to exhibit the same problems as `@koush/wrtc`) into https://github.com/dxos/wrtc, fixed build, and now single-stepping through newer revisions.

M96 seems to exhibit different symptoms, the `network-manager` test completes sometimes and the `runTransport` throws different error messages before ultimately getting stuck.

**Comment by nferch** [comment]
built up to M100 which exhibits the same problems. revisions beyond M100 have compile/API changes that were not trivial for me to fix, so pausing work on this in favor of building a compatible transport.

**Comment by nferch** [comment]
Ongoing work on https://github.com/dxos/dxos/issues/3978

**Comment by nferch** [comment]
https://github.com/dxos/dxos/issues/3828 merged, which adds the transport, support in the testbench, and a (crude) way to toggle it on within the agent.

Needs more testing and evaluation to fully switch over to.

**Comment by nferch** [comment]
https://github.com/dxos/dxos/pull/4872
