### ISSUE TITLE
[echo] replication broken after mobile sleep

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3861]
I still have loss of replication when the safari window goes to background or the phone sleeps. restoring replication requires reloading both ends of the wire (mobile browser and desktop browser)

**Comment by wittjosiah** [comment]
![Image](https://github.com/dxos/dxos/assets/4529818/a23bcc5e-4c95-4ac3-823c-a90e6349bb7e)

**Comment by wittjosiah** [comment]
logs from desktop browser shortly after phone goes to sleep

![Image](https://github.com/dxos/dxos/assets/4529818/a57d8d69-99fc-4815-a74f-878adc43c596)

**Comment by wittjosiah** [comment]
![Image](https://github.com/dxos/dxos/assets/4529818/65c5dff5-227c-4f06-bfbf-89c29ec34e2a)

**Comment by wittjosiah** [comment]
Another two run throughs I see slightly different connection behaviour:
- Repeated attempts to reconnect
- only one attempt successful between several runs
- continued to try even after a successful connection
- seems like potentially two separate attempts to reconnect ongoing
- the time it made the successful connection, it was replicating the space even though it was still trying to reconnect again
![image](https://github.com/dxos/dxos/assets/4529818/5ca2e76e-61ae-4422-8a4f-cdb1ffd93d4c)
![image](https://github.com/dxos/dxos/assets/4529818/574e6745-bbda-497d-ba82-c1d958d100fc)
