### ISSUE TITLE
[composer] data loss and replication failure

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3874]
Jess reports having data lost in composer more frequently in the last few weeks.

He has many tabs open to composer. Our theory is that some of the tabs may be getting backgrounded by the browser and the webrtc link goes down. 

Data seems to be "reactive" within a single window, but does not replicate to the other windows on the same device. when reloading the window, all changes are lost.

**Comment by dmaretskyi** [comment]
decided to add saving indicator to the app, and also crash when we have disconnected from the worker

**Comment by zhenyasav** [comment]
let's close for now and monitor if this happens again
