### ISSUE TITLE
[shell] fast dismiss when joining a space already a member of

### ISSUE THREAD

**Issue by thure** [dxos/dxos#3886]
i.e. Check if invitation code has space id, _also maybe space name?_

**Comment by thure** [comment]
This is blocked; currently invitationCode must be redeemed & authenticated before the spaceKey becomes available.

**Comment by zhenyasav** [comment]
also we need to ensure the SDK doesn't write duplicate credentials when the APP fails to protect from calling for a repeat invite code:
- [ ] #....
