### ISSUE TITLE
[authoring] text area duplicates

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#3921]
Steps to reproduce:
- change the space and text going into `useTextModel` separately
- observe that when the space changes after the text the view is not destroyed and the content is duplicated

Example:
First observed in composer when migrating to the new graph api, in that case the workaround was to render a placeholder when the space and text are not aligned https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx#L73-L75.

**Comment by thure** [comment]
Can’t reproduce – currently there is no way to reach this state in the UI.

**Comment by wittjosiah** [comment]
@thure iirc you need to modify the code to reproduce this because I added a workaround. However because there's a workaround I don't think this is high priority so much as tech debt.

**Comment by thure** [comment]
De-escalating to P3 for now.

**Comment by wittjosiah** [comment]
Closing since editor code has mostly been rewritten since this was filed. If it shows up again we'll create a new issue.
