### ISSUE TITLE
Plugin API docs

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3938]
## Motivation

We want to help developers get started building plugins quickly

## Finish Line

- [x] Generated API docs for the Graph / Plugin API
- [ ] Some prose to guide the process
- [ ] Instructions for building your own plugin from scratch and importing existing plugins and surrounding it with Composer
- [ ] Short description of Composer with Video of composer in action
- [ ] Link to try out composer / labs

**Comment by jessmartin** [comment]
@wittjosiah can you link to the generated plugins docs, if those are indeed done?

**Comment by wittjosiah** [comment]
@jessmartin they all live in jsdoc at the moment, if we want these generated I think we'd need to add some of these to the package list that apidoc looks at. You can see all the jsdoc I added here https://github.com/dxos/dxos/pull/4014
