### ISSUE TITLE
replication testbench

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3941]
Splitting out Stage 3 from https://github.com/dxos/dxos/issues/3515
* [x] Test replication using ReplicationExtension
* [ ] Test snapshot sync using BlobSyncExtension
* [x] Measure replication throughput in bytes
* [x] Tinker with replication parameters in hypercore to get max throughput

# Definition of done
* test for ReplicationExtension and BlobSyncExtension is complete
* judgement call on amount of tweaking of replication parameters to get better throughput
* determine max message size (before breaks? e.g., large YJS mutation like copying pages of text)

## Current state, 2023/8/22:

- ReplicationExtension is mostly done, need to collect and review outputs
- Need to add BlobSync and get measurements from there
- Unknowns are replication parameters. Will known more tomorrow.

**Comment by nferch** [comment]
WIP: https://github.com/dxos/dxos/pull/3932

**Comment by egorgripasov** [comment]
As a summary of the efforts:

- Replication testbench that is
  - configurable with number of peers, swarms, feeds per swarm
  - configurable with feedMessageSize, and feed load type: either per specified amount of time or per message count
  - analyze each feed throughput across all peers
- Results are:
  - Throughput could be improved by ~20% by increasing `maxRequests` param of feed.replicate()
  - Highest message size results in much better throughput, e.g.
    
    500 bytes -> 957.04 kB/sec
    500_000 bytes -> 37.56 MB/sec 

  - In Node, storage is quite fast with in both RAM and FS cases, with ram ~20% faster

     StorageType.RAM -> replicationSpeed: '1.12 MB/sec'
     StorageType.Node -> replicationSpeed: '967.28 kB/sec'
