### ISSUE TITLE
Shell panel UI update to Figma mocks

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3943]
- https://github.com/dxos/dxos/pull/3931
- https://www.chromatic.com/test?appId=64c18b27fca920629f846e5b&id=64e3aa640b8a74a947336dd9

**Comment by thure** [comment]
Resolved by #3931.

**Comment by jessmartin** [comment]
@zhenyasav where should I leave additional feedback on the shell panels design?

Some notes I took this morning when reviewing:
- bug in invitation shell panels with an X that appears after user joins
- Needs separation (heading) between invites and members in the space to differentiate (they look too similar)
- I think your username should have (me) next to it to indicate it's you, but maybe if we had the "Members" heading and your avatar is the first thing underneath the heading, it would be clear that it's you, who is a member of the space
- Switching to dark mode doesn't switch the shell panel to dark mode
