### ISSUE TITLE
[tracking] connections hang with 8 concurrent agents

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#3951]
# Known failure condition
Run 8 agents on your computer
Some agents fail to join space

# Hypothesis
* Due to connectivity limiting changes
* Due to something else?

# Proposed approach
* Reproduce manually with agents
* Reproduce in testbench
* ???
* Debugging

# Definition of Done

## Option 1
* Timebox to X days of debugging and investigation

## Option 2
* Clarity on what area of the code or change is responsible for the breakage

## Refs
- https://github.com/dxos/dxos/issues/3827

**Comment by egorgripasov** [comment]
fixed with https://github.com/dxos/dxos/issues/4060
