### ISSUE TITLE
[shell] Space invites should append to the end of the current app URL

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#3968]
## Motivation

When sending someone a space invite, the user's desired action is often that the person they are sending the space invitation to would be redirected to the space of object that is being shared or currently viewed. The "web friendly" way to do this is to use a URL that can be routed to.

## Finish Line

Currently, when a Space Invitation is created by Shell, it truncates the URL and doesn't preserve the context of where the user was when they extended the invite.

- Shell should merely append the `?spaceInvitationCode=xxxx` to the end of the URL
- When we clear the `spaceInvitationCode` once the invite flow is complete, we should not clear the entire URL, but merely remove that query param

**Comment by wittjosiah** [comment]
@jessmartin what do you think about the approach in #5105? This isn't preserving the url but gives you a way to redirect anywhere after the invitation. The reason for this approach was that I found if the URL was preserved, the app underneath the shell would attempt to navigate to the object that it doesn't yet have. In that PR the target is encoded into the invitation and passed to the app upon success and the app can then handle the navigation how it chooses.

**Comment by jessmartin** [comment]
@wittjosiah that makes sense to me 👍
