### ISSUE TITLE
WebrtcProxyTransport connections closed by closing tabs seem to be stuck in CLOSING state for couple of seconds

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#3975]
Repro:

1. Create a space with 2 peers.
2. Open devtools for peer 1.
3. Observer swarm connections pannel.
4. You should have 2 browser tabs open for peer 1: orignal labs tab (holds webrtc connection), devtools tab.
5. Close the labs tab. Webrtc conneciton should get closed.
6. Observe connection being stuck in CLOSING state.
7. After a while new connection gets opened from the devtools tab.

**Comment by dmaretskyi** [comment]
![Kapture 2023-08-24 at 14 47 05](https://github.com/dxos/dxos/assets/35851437/f7cf2445-2dbf-42fb-adea-51db22a518f4)

**Comment by nferch** [comment]
@dmaretskyi can repro on main (8d1cf7074), although it looks like you were on something else given that I don't have the label or close reason column?

**Comment by dmaretskyi** [comment]
@nferch Yeah, I've added them to @richburdon 's branch https://github.com/dxos/dxos/pull/3972 . But feel free to cherry-pick those commits if you need them sooner

**Comment by nferch** [comment]
@dmaretskyi don't need them, just wanted to confirm that I shouldn't have been running some other branch that would have affected the reproduction of the issue.

**Comment by nferch** [comment]
@dmaretskyi looks like the issue is due to each Extension close timing out, I guess we need some mechanism to propagate that the nature of the close so it doesn't wait for the bye response (why we do this at all?). when I comment out https://github.com/dxos/dxos/blob/1d5e9f952e75f2027e70eeef09cb29d963c7b160/packages/core/mesh/rpc/src/rpc.ts#L202 it will reconnect straight away.

**Comment by nferch** [comment]
https://github.com/dxos/dxos/pull/4101 seems to fix this particular case, although I saw some other issues, like when one peer doesn't notice that the other has disconnected and still thinks it is CONNECTED (due to the underlying connection being UDP?)
