### ISSUE TITLE
Show app version

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4003]
- [x] Heuristic to group action menu (get hint from action/intent metadata).
- [x] Show version/link.
- [x] Need to scroll menu if overruns page.
- [x] Add share button to header.

Re: https://github.com/dxos/dxos/pull/4002

![Image](https://user-images.githubusercontent.com/3523355/263557047-1c4e1781-452c-4eed-bbc8-47a2a8d6f6c6.png)

**Comment by jessmartin** [comment]
@richburdon it looks like this might be done already? can you update with status?
