### ISSUE TITLE
[composer] no way to close sidebar on mobile

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4021]
testing in chrome with device compat mode (because composer doesn't load on mobile right now) but the drag/swipe gestures don't seem to work and there is no affordance to close the sidebar. Same problem happens on desktop when the window size is narrow enough, the sidebar seems to take over.

<img width="1460" alt="Screenshot 2023-08-29 at 9 22 12 AM" src="https://github.com/dxos/dxos/assets/3398896/ec9fa173-4509-46fd-a1dc-71dc81dabc2d">

**Comment by jessmartin** [comment]
@zhenyasav what happens when you select an item from the treeview? It closes the sidebar for me. But it would be nice to have an explicit close sidebar button, as we discussed in the design.

**Comment by thure** [comment]
Widen scope to include the complementary sidebar
