### ISSUE TITLE
[composer] spaces node not selectable

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4022]
The Local Files node is selectable, but the Spaces node is not. 

All nodes should be selectable in the sidebar. We can show stacks of contents when we encounter the "generic" case (when there is no better presenter for the detail area). For now we can even leave it blank the same way as Local Files is blank.

<img width="288" alt="Screenshot 2023-08-29 at 9 24 26 AM" src="https://github.com/dxos/dxos/assets/3398896/e0809178-0a29-4a26-9e9f-6b9a2f0c2517">

**Comment by wittjosiah** [comment]
Resolved by #4218
