### ISSUE TITLE
Dropdown/select scrollbar

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4026]
The dropdown/select should scroll if offscreen.

![Image](https://user-images.githubusercontent.com/3523355/264177443-d3cec405-12f2-4a22-a1f5-048d37fc398d.png)

**Comment by thure** [comment]
`Dropdown.Content` should be constrained, perhaps at the level of Aurora:
```
max-height: var(--radix-dropdown-menu-content-available-height);
```
Source: https://www.radix-ui.com/primitives/docs/components/dropdown-menu#constrain-the-contentsub-content-size
