### ISSUE TITLE
[composer] presence in top right corner not hooked up

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4054]
- Shows the number of members in the space instead of the number of people viewing the item.
- The tooltip on hover says "Members viewing this item" which is not accurate to what it's currently showing.
- The icons overlap each other in weird ways and I can't tell what the icons actually _are_.

![Image](https://github.com/dxos/dxos/assets/27258/164193e8-16a3-4731-99f5-cc72a9b17296)

**Comment by jessmartin** [comment]
updated the comment with current problems :)

**Comment by jessmartin** [comment]
nice design:
![Image](https://github.com/dxos/dxos/assets/27258/4eeb73ac-dc09-4915-a426-f44b2885d3da)
