### ISSUE TITLE
Race condition when peers concurrently initiate connections with each other

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4059]
This is the case when 2 peers are trying to connect to each other simultaneously, and it seems we have some problems in handling such connections; Before the connection limiter we were most likely "saved" by artificial (small) timeout we put in one peer based on the if (remoteId.toHex() < this.localPeerId.toHex()) condition, so it would wait till the other peer connects first; Now the order is non-deterministic and seems like it happens bit more often, so I would like to make sure we properly manage those connections (seems like some of them might stuck in connecting state and also in connection-limiter)

**Comment by nferch** [comment]
@egorgripasov PTAL and update as you make progress!

**Comment by egorgripasov** [comment]
The progress of fixing simultaneous connections are reflected in https://github.com/dxos/dxos/pull/4037
