### ISSUE TITLE
[composer] Mobile UX punchlist

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4124]
- [x] Scroll popovers.
- [x] Button to close complementary sidebar.
- [x] Larger button sizes.

**Comment by thure** [comment]
Please confirm:

- Popovers scroll on `main`, was the observed issue in an old deploy?
- Buttons for closing sidebars were added in #4166.
- Buttons are observed to be larger on the smallest breakpoints due to the increased `font-size`, does this satisfy the item?
