### ISSUE TITLE
[composer] Extend drag-n-drop to support arbitrary plugins and surfaces

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4135]
Duplicate of [#4155](https://github.com/dxos/dxos/issues/4155)?

## Motivation

For Strange Loop, the primary hero demo is showing off the app interop facilities provided by Composer/Labs around drag-n-drop between different plugin surfaces.

## Finish Line

- drag anything with a `section` into Stacks
- extend Kanban to be a surface similar to Stack that can accept the `card` role
- allow dragging into Threads anything that exposes a `card` role
- drag from Threads back into Stacks, Kanban
- all these are live, interoperable views

**Comment by jessmartin** [comment]
You could _also_ label this as "DevRel" or "Plugins" 🤷

**Comment by zhenyasav** [comment]
we should merge this into #4155

**Comment by thure** [comment]
Most of this is implemented as of the release of `react-ui-mosaic`. At this time, specific scenarios should be captured in separate issues.
