### ISSUE TITLE
[labs-app] DnD feature parity with Composer

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4155]
## Ranked
- [x] Normalize flat/presentational folders across all plugins
- [x] #4163
- [x] Support DND dragging of all objects that support Sections into Stacks (Document, Sketch, File (image), etc.)
- [ ] Integrate DND from sidebar into Kanban.
- [ ] Support DND from complementary sidebar (e.g., Thread block) into Stack.
- [x] Unify IPFS file upload with Stack section

**Comment by thure** [comment]
My understanding is this is not P0 at this time. Since I am the assignee, I am giving this P2 for now, but please feel free to reassign/reprioritize as needed.
