### ISSUE TITLE
Demo Punchlist

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4158]
# Me
- [ ] Thread selector
- [ ] Type ahead selector
- [ ] Data import/export via functions
- [ ] Stickies plugin
- [ ] Chess app/monorepo
- [ ] Auto-create stack (with image) as Getting started (not doc)

# Theme
- [ ] Rough pass looking at Notion, GH, Airtable; use of font sizes, spacing, color, etc.
- [ ] Notion-like flat; white main content; "nicer" gray/neutral; sidebar different from bg.
- [ ] Minimal markdown styles (punchy "Getting started" doc?)
- [ ] Some color (not "grey goo")

# Team
- [ ] DND: [#4155](https://github.com/dxos/dxos/issues/4155)
- [ ] Option to remove visible accessibility borders
- [ ] Mobile (fonts)
- [ ] Treeview menu:
  - [ ] Create button with sorted plugins
  - [ ] Sections
- [ ] Remove "no documents... click to get started"

**Comment by jessmartin** [comment]
updated by Q12024 use cases
