### ISSUE TITLE
space api proposal

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#4171]
```
const spaces = client.spaces.get(); // Required because of MulticastObservable<Space[]> base.
const space = client.spaces.get(spaceKey);
const defaultSpace = client.spaces.default;
const space = await client.spaces.create();
const invitationObservable = await client.spaces.join(invitation);
```

`EchoProxy` should be renamed maybe?

**Comment by wittjosiah** [comment]
@dmaretskyi `spaces` extends `MulticastObservable<Space[]>` so that it keeps parity with current functionality but as you say these methods are just added to the observable rather than having to have a class with the observable in it. Implementation is here: #4173
