### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#4181]
- persisted LogEntries may leak memory by preserving log invocation scope (`entry.meta.S` field) 
- https://github.com/dxos/dxos/blob/b605d47ace1972bf3df808717ef1d48d4a6b33f3/packages/core/mesh/teleport-extension-gossip/src/gossip.ts#L34 [P0]
- https://github.com/dxos/dxos/blob/b605d47ace1972bf3df808717ef1d48d4a6b33f3/packages/core/mesh/messaging/src/messenger.ts#L48
- https://github.com/dxos/dxos/pull/4182
- https://github.com/dxos/dxos/blob/d5a179c432963d1e23e04431f6d2321965c71999/packages/common/feed-store/src/feed-queue.ts#L129
- Memory consumption grows linearly with the number of mutations since the last epoch
- https://github.com/dxos/dxos/blob/c4d3e15b7ae7ab9d49a325e0d2278963bbe89bef/packages/common/feed-store/src/feed-iterator.ts#L85 -- https://github.com/nodejs/node/issues/17469
- https://github.com/dxos/dxos/pull/4188

**Comment by nferch** [comment]
@dmaretskyi status on the board was moved to done, should issue be closed too?
