### ISSUE TITLE
[docs] Stackblitz demo is broken

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4208]

**Comment by jessmartin** [comment]
@wittjosiah it's not working yet.

Had to replace line 13 in `Demo.tsx` with:

```
// TODO(wittjosiah): Why doesn't Stackblitz understand import of just proto directory?
import { Task } from '../proto/gen/schema';
```

**Comment by wittjosiah** [comment]
@jessmartin my apologies. This should be working now, let me know if it's still not working for you. I'll leave it open for you to verify it's working for you as well.

**Comment by jessmartin** [comment]
Hurray, it works! closing.
