### ISSUE TITLE
☂️ Next ECHO features

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#4346]
## Schema

- Unify dynamic and static schema
- Schema version migration (dynamic & static)
- Research cambria + automerge
- Cross-space schemas?

## API

- https://github.com/dxos/dxos/issues/4339
- Refactor proxies
- Filter API discussion

## Graph

- Cross space queries
- Strong references
- Indexing
- Groups/teams
- Space nesting

## Profile/identity

- Globally discoverable identity
- Contact book

**Comment by jessmartin** [comment]
Requests:
- ephemeral feed for cursor sharing, sharing drag positions in TLDraw, etc
- ability to reference past versions of an object and "roll back" to those past versions
- customize epoch behavior on a per-type basis so that losing history is optional

**Comment by zhenyasav** [comment]
more requests:
- simple permissions (owner, reader, writer or similar)

**Comment by jessmartin** [comment]
> simple permissions

LiveBlocks uses:
 - `space:write` - write to the data feed
 - `space:read` - read from the data feed
 - `space:presence:write` - write to the presence feed
 
From: https://liveblocks.io/docs/rooms/permissions/id-token#permissions-types
