### ISSUE TITLE
[composer] clickable links in markdown docs as @mentions

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4368]
## Motivation

Document links could be linked as @mentions of a specific object. This would enable inline links that can link to any object and open up a powerful autocomplete interface.

Inspired by the idea of [mentions in the Embark from Ink & Switch](https://www.inkandswitch.com/embark/#mentions-linking-between-nodes).

https://github.com/dxos/dxos/assets/27258/7cd5ddde-4dcf-4980-a384-8c8dc95d44f9

## Finish Line

- [ ] Extend the Markdown plugin to support inline object links

**Comment by jessmartin** [comment]
Closing in favor of #5152
