### ISSUE TITLE
[shell] Device presence and agent control

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4378]
As a user of the DXOS SDK and shell, I want to be able to 
- [ ] see whether my devices and agent(s) are online 
- [ ] see when devices or agents were last online
- [ ] start and stop a managed agent
- [ ] rename devices

See also:
- #5907

**Comment by nferch** [comment]
First implementation of device names has landed: https://github.com/dxos/dxos/pull/4390

**Comment by zhenyasav** [comment]
@thure this represents the work you're doing on the front end with the device list and agent control buttons. merci!

**Comment by thure** [comment]
It looks like `Device` is
```ts
interface Device {
    deviceKey: ReturnType<(typeof substitutions)["dxos.keys.PublicKey"]["decode"]>;
    kind: DeviceKind;
    profile?: {
      label?: string;
      platform?: string;
      platformVersion?: string;
      architecture?: string;
      os?: string;
      osVersion?: string;
    }
}
```
If this is everything protocol knows about a device, I think I need protocol folks’ help augmenting this to have the requested information.

**Comment by nferch** [comment]
@thure through https://github.com/dxos/dxos/pull/5745 and I think the protocol and API now provide most things needed here for device presence.

There's some placeholder modifications to shell exercise the APIs, but wanted to give you a heads up for when you're ready to make it less ugly.

**Comment by zhenyasav** [comment]
UI exists now, needs hooking up
