### ISSUE TITLE
Mosaic Views

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4389]
# Current
- [x] Reconcile container/path (remove container)
- [x] Wrong position when dragging into the bottom of a kanban column
- [x] Button to test updating graph/echo to demo reactivity
- [x] Tree not working
- [ ] Don't render underlying tile until transition has finished
- [x] Graph demo for Tree view
- [x] Move/Copy
- [x] isDroppable logic
- [x] onDrop handlers:
  - [x] Kanban demo selects schema and `refprop`
  - [x] Update kanban objects by `refprop` on drop
  - [x] Demo dragging external items into Kanban
- [x] Factor common components (e.g., remove Kanban as name and reuse Stack)
- [x] ECHO integration
- [x] Path abstraction

## Next
- [ ] Standardize storybooks
- [ ] Reconcile/factor out testing generator from debug plugin
- [ ] Rename aurora-grid => mosaic (deprecate old, incl. kai)
- [ ] Update README with ontology
- [ ] Purify plugin components
- [ ] Retro fit mosaic

**Comment by wittjosiah** [comment]
**Problems noted during walk-through**
- stack
  - on occasion drops not where placeholder is
  - some animations are faster than others?
- kanban
  - reordering columns in janky depending on what the cursor is over
  - dropping into bottom of column doesn't add to end
  - reordering cards down flickers if there's a number of cards in the column
- tree
  - sometimes weird rendering of placeholders
- demos
  - default
    - glitchy cards when reordering the right column
  - graph/echo
    - kanban issue of reordering cards but even worse

**Comment by thure** [comment]
Marking as pending review — this should be reevaluated and groomed since it seems out of date.

I’d also like to discuss how we handle epic issues at some point, I understand they’re ergonomic for the author but as an assignee I’m having trouble following-up on specific points.

**Comment by thure** [comment]
Removing priority due to inactivity.
