### ISSUE TITLE
[composer] device invite flow succeeds, but requires app refresh to load

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4402]
Seems like some errors are getting thrown after the Device Invite flow that crashes Composer. All seems to work after cmd-R.

Repros:
- Invite another device
- Watch it hang when it succeeds

![image](https://github.com/dxos/dxos/assets/27258/b9601e24-c643-4acf-8d73-c3d4ea54896a)

**Comment by zhenyasav** [comment]
#4847
