### ISSUE TITLE
Documentation docs.dxos.org for agent

### ISSUE THREAD

**Issue by nferch** [dxos/dxos#4408]
- [ ] Installation
- [ ] Automatic startup
- [ ] Upgrading
- [ ] Troubleshooting and diagnostics
- [ ] Minimum system requirements
- [ ] Data backups (manual?)

**Comment by nferch** [comment]
Partially completed in https://github.com/dxos/dxos/pull/4873

**Comment by jessmartin** [comment]
I think the docs are good enough.

Once we have things like upgrade notifications, we can add dos for those as we build them. Closing this.
