### ISSUE TITLE
[composer] revamp Personal and Shared Spaces

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4418]
## Motivation

The Personal Space is currently a bit confusing in Composer. 
- It's the _default_ space that's created automatically buy the SDK when initializing a new identity. But it can be shared via the SDK or in a non-Composer app, resulting in a broken/confusing Composer UX.
- When creating a new Shared Space in Composer, it starts off as _not shared_, and therefore, Personal. Which is also confusing.

Let's clarify this by simplifying and unifying Personal and Shared.

## Idea

- Personal Space becomes Personal Space**s** (with an extra s). You can create as many spaces in Personal Spaces as you would like. They have the same nesting and display as Shared Spaces. 
- As soon as you share a space, or one is shared with you, it moves to the Shared Spaces section.

## Open Questions / Design Challenges

- Should you have the option of "creating a new space" in the Shared Spaces section? As discussed, by default, it's not shared. So it's confusing to have that option be present. Maybe we go from Space creation straight to the "Share Space" dialogue when creating a space in Shared Spaces?
- Once there is an invite created, does the Space immediately move from Personal Spaces to Shared Spaces? How will that jump in the UI feel?

**Comment by jessmartin** [comment]
> It's the default space that's created automatically buy the SDK when initializing a new identity. But it can be shared via the SDK or in a non-Composer app, resulting in a broken/confusing Composer UX.

This has created confusion for at least one user already: 
![image](https://github.com/dxos/dxos/assets/27258/ba893ff8-3243-4bfb-9f52-f751f00ab713)

**Comment by jessmartin** [comment]
@zhenyasav curious for your feedback on this idea

**Comment by wittjosiah** [comment]
I remember our discussion of this featuring some sort of share lock on every space which would be turned on by default on your personal space.
