### ISSUE TITLE
[composer] link opening experience

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4494]
problem:
there is a time spent loading spaces before an entity can be found for a given url. it's unclear to the user if anything is happening and whether their link will be opened or not for a long time.

proposal:
- [ ] show a dismissable toast with an indeterminate progress bar which indicates the thing is being opened. 
  - [ ] show success experience with "go to item" action 
  - [ ] show timeout experience (dismissable "we couldn't load this")
- [ ] modify the "first run" message to reflect the intention to open a thing

**Comment by thure** [comment]
first pass: https://github.com/dxos/dxos/pull/4520
