### ISSUE TITLE
[composer] e2e test fails to replicate data

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#4512]
![image](https://github.com/dxos/dxos/assets/4529818/892ce088-ca42-449a-a0ac-6e243b7fb307)

Reproduction:
1. change test `host and guest can see each others’ changes in same document` from `skip` to `only`
2. run `LOG_FILTER=debug REMOTE_SOURCE=http://localhost:3967/vault.html px e2e composer-app --inspect`

Notes:
- does not seem to fail on macOS

**Comment by nferch** [comment]
pending merge of https://github.com/dxos/dxos/pull/4555 and https://github.com/dxos/dxos/pull/4552
