### ISSUE TITLE
[composer] presence not working

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4712]
composer 0.3.7 candidate on staging

have two windows pointing to the same object, waited a good few minutes, no presence indicators

![Screenshot 2023-11-14 at 5 07 50 PM](https://github.com/dxos/dxos/assets/3398896/8812c065-d26c-4bd5-a751-0b3f87886bc5)

**Comment by wittjosiah** [comment]
#5100

**Comment by wittjosiah** [comment]
Will restore viewers w/ #5174
