### ISSUE TITLE
[composer] closed spaces don't show their names

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4751]
Instead, we see "Loading space..."

re-opening a space works though!

**Comment by wittjosiah** [comment]
This is happening here https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-space/src/util.tsx#L47-L53

From what I can tell inactive spaces which have never loaded in a session don't seem to have their cached properties. This seems likely to be an SDK bug.
