### ISSUE TITLE
Add tests for import/export

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4806]
- [ ] Very important that we create a unit test for this. 
  - https://github.com/dxos/dxos/blob/main/packages/core/echo/echo-schema/src/serializer.test.ts
- [ ] Able to create new space from file (not only import into current space).

https://github.com/dxos/dxos/pull/4805/files#diff-960deb3cd4910f1ea4c3d39184c914f49e9b3f4efe3af484ad3986a2f882fb69R57

RTE when importing a space.

- create new shared space A
- export space to file
- create new space B
- import space into B from file

```
index-60ffb57c.js:173 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'objects')
    at Object.resolver (index-60ffb57c.js:173:25870)
    at async t.dispatch (plugin-CBPJO5NB-cbde7b39.js:1:837)
resolver @ index-60ffb57c.js:173
await in resolver (async)
invoke @ index-60ffb57c.js:173
onClick @ plugin-navtree-d29a37f0.js:1
AV.test.r.<computed> @ ui-31569e56.js:3
Nc @ react-1b66d7d8.js:29
Tc @ react-1b66d7d8.js:29
Lc @ react-1b66d7d8.js:29
oi @ react-1b66d7d8.js:29
Qs @ react-1b66d7d8.js:29
(anonymous) @ react-1b66d7d8.js:29
Eo @ react-1b66d7d8.js:32
vs @ react-1b66d7d8.js:29
Rl @ react-1b66d7d8.js:29
Gu @ react-1b66d7d8.js:29
Kc @ react-1b66d7d8.js:29
```

**Comment by jessmartin** [comment]
Used this a bunch today and it's working well for me!

@richburdon can you confirm that you can reproduce this problem?

**Comment by mykola-vrmchk** [comment]
https://github.com/dxos/dxos/blob/main/packages/core/echo/echo-schema/src/serializer.test.ts

**Comment by dmaretskyi** [comment]
https://github.com/dxos/dxos/blob/4d53036640c7321aab9b459e609c60087d3cf385/packages/core/echo/echo-schema/src/serializer.test.ts#L17

**Comment by jessmartin** [comment]
@richburdon can you review and see if you've got what you want here? If so, please close :)
