### ISSUE TITLE
[table] Bugs

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4822]
- [ ] Can't reliably add new items at bottom of table.
- [ ] Table editor updates the incorrect table metadata when resizing (stale value).
  - Create three tables via debug plugin
  - Adjust width of first column in Projects table
  - Change to Contacts table: first column has resized
  - Open devtools and look at table def (updated correctly)
- [ ] Cannot rename column properties.
- [ ] Currently unable to reset value (i.e., set to undefined).
- [ ] Column resize is REALLY slow.

![Image](https://github.com/dxos/dxos/assets/3523355/ce39e58b-1727-4429-b10d-390e64237571)

**Comment by jessmartin** [comment]
@richburdon I don't think this should be in `2023-12`. M0 focus is Documents + Stacks.

**Comment by zhenyasav** [comment]
removed milestone and priority
