### ISSUE TITLE
[cli] cannot join space from agent

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4824]
- start agent
- dx space share
- join space from browser
- immediately times out

```
 invitation timeout] Object
C @ :3967/@fs/Users/burd…wser/index.mjs:1790
```

**Comment by jessmartin** [comment]
Just tested this. 

Joining the cli-created space from the browser works, you just have to be _very_ fast! It times out quickly. Need to lengthen the time-out.

Also, the space doesn't have a root folder, so you can't add any objects to it from within Composer.
