### ISSUE TITLE
vault topology homologation

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4845]
## Motivation

Browsers are introducing local storage partitioning rules that segregate iframes even on the same domain (subdomains don't work anymore). Therefore, our vault topology has to be colocated under a single domain. As part of that migration, we can eliminate the iframe entirely in order to simplify 

## Finish Line

- remove the iframe
- centralize all of the data under https://composer.dxos.org

**Comment by jessmartin** [comment]
To ship this, we have to move all user data from https://halo.dxos.org to https://composer.dxos.org.

When the new "monolithic" client loads:
- Start the "old" client up alongside the new client
- Pop up an alert and ask if they want to migrate
- Do the device invitation transparently
- On successful device invitation, the data will be migrated automatically

cc: @wittjosiah correct my mistakes here 😉
