### ISSUE TITLE
[composer] e2e tests

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4851]

**Comment by jessmartin** [comment]
@wittjosiah would you mind listing out the e2e tests you think we need here?

**Comment by wittjosiah** [comment]
This was progressed by https://github.com/dxos/dxos/pull/4967 and https://github.com/dxos/dxos/pull/4968 which setup tests for drag and drop in the stack storybook and within the composer application.

The one other test that we need for the composer-baseline is a test to ensure it catches protocol changes as expected. I have this test drafted on a branch and will land it soon.

There are a lot of other e2e tests to write but this is for a baseline. The other tests will be written as we promote experimental stuff to being on-by-default within Composer.
