### ISSUE TITLE
[composer] remove @braneframe namespace

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4854]
## Motivation

The `@braneframe` namespace is increasing complexity and maintenance cost to work around multiple namespaces.

Specifically, the longer we use this namespace, the more users out there are creating entities with type strings that contain these words, the more migration complexity we will have later.

It's also hard to write docs and ship the app framework when all the plugins are in this weird namespace

e.g.: `@braneframe/plugin-markdown => @dxos/app-plugin-markdown`

**Comment by richburdon** [comment]
Please discuss effort with @richburdon first.
