### ISSUE TITLE
[documents] clickable links in documents

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4855]
## Motivation

We want the markdown editor in Composer to be comparable to other well-loved Markdown editor interfaces (GitHub Issues, Obsidian, Bear, etc) while focused on a "modeless" editor - no need for a Preview mode, everything is Edit all the time.

In order to accomplish that, we need Markdown links to present nicely and be clickable / followable.

We also need to be able to link to other Composer content from within a text document to allow for navigation.

## Finish Line

- [x] Links should open in a new window
- [x] Markdown-style links (i.e., `[link](url)`) should be navigable
- [ ] Links should be tappable to navigate on mobile. (If you tap on the link, it should navigate. If you move the cursor into the block by dragging it in, it should be editable)
- [ ] Raw URLs (i.e., `https://apple.com`) should be navigable
- [ ] When the cursor is within a link on desktop, command-enter on the keyboard should navigate to it
- [ ] Links _could_ collapse when the cursor leaves the link, similar to Obsidian. (Obsidian is also built on CodeMirror 6, so this should be possible).

## Obsidian UX

https://github.com/dxos/dxos/assets/27258/29d8a35f-409f-43a1-a1dd-0ddc4c926f53

## Open Questions

How should we handle creating links to other Composer objects? Maybe split out as separate feature in #4368?

**Comment by jessmartin** [comment]
related to #4368

**Comment by richburdon** [comment]
https://github.com/dxos/dxos/pull/4890
