### ISSUE TITLE
[composer] consolidate actions into breadcrumb menu

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4857]
## Motivation

The lists of actions differ between the sidebar and the titlebar. 

## Finish Line

- [ ] Make the lists of actions the same between the sidebar and the titlebar

## Out of Scope

Eventually, we'll probably want to have a "toolbar" or breadcrumb-type thing at the top of the main area. For now, let's just align the actions menus.

**Comment by thure** [comment]
Resolved by #5073
