### ISSUE TITLE
[stack] show cursors in stack documents

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#4862]
## Finish Line

- [ ] markdown docs in stacks should show cursors

**Comment by jessmartin** [comment]
random idea: when someone is viewing a stack, count the topmost stack item in the visible area as the "current" stack item. for other users show the stack viewer's presence indicator in the chrome of that stack item. roughly corresponds to "scroll position" in the stack or "which item are other people looking at."

**Comment by thure** [comment]
I’m stumped, I can’t see how cursors are succeeding in getting displayed in `DocumentMain` but not in `DocumentSection`. If someone more familiar with `awareness` could chime-in, that’d help a lot.

**Comment by thure** [comment]
This is already done.

https://github.com/dxos/dxos/assets/855039/ff0c14ac-b01f-49a3-bf9a-b6c5c630df6c
