### ISSUE TITLE
[Intent Plugin] - Log when no plugin handles an intent.

### ISSUE THREAD

**Issue by ZaymonFC** [dxos/dxos#4885]
When upgrading the app framework plugin template, I ran into a bug wear an intent I was firing was not being handled. Having some basic logging when the intent resolver does not find a plugin to handle the intent would have saved some time.

Suggested log message: `"Warning: no registered plugin handled intent: ${intent name}"`.

**Comment by wittjosiah** [comment]
I like this idea, seems like a useful warning

**Comment by wittjosiah** [comment]
Resolved by #5387
