### ISSUE TITLE
[shell] can't resume device join after closing shell

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#4927]
- open shell
- click "Add device"
- click "Back" or "X" to close the shell
- can't get to the secret / PIN code in order to give to the other party
- have to create another device join link, cancelling the original one

Expected behavior: "Add device" link should change to the status for the active device join link? Rethink this in light of #4848.

**Comment by wittjosiah** [comment]
fwiw the "other party" in the device invitation flow is still yourself. I can see it being a little annoying to have to restart the flow if the dialog gets closed, however I'd also potentially consider the device invitation being cancelled when leaving that screen a security feature (though perhaps the auth code is enough for that purpose?).

**Comment by jessmartin** [comment]
> the "other party" in the device invitation flow is still yourself

True. It's a minor frustration. When we redesign with #4848, this should probably just go away as a problem.
