### ISSUE TITLE
[native] IPFS plugin is causing app to stop working

### ISSUE THREAD

**Issue by mjamesderocher** [dxos/dxos#4978]
After enabling the IPFS plugin, the console shows the error: `Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable`. This is likely caused by a missing config property for the IPFS gateway. [Config file is here](https://github.com/dxos/dxos/blob/f9169736764524296fb76f9025fa73f91d757ce6/packages/apps/composer-app/dx-local.yml#L11)

[Discord conversation for context](https://discord.com/channels/837138313172353095/1180035274345025617/1187031550232113215)

### Steps to reproduce

* Use the code from [this commit](https://github.com/dxos/dxos/pull/4960/commits/5c44b9ce167e723c905d79434907aac3d0fc8feb)
* Build Composer and SSC native app
* Enable the IPFS plugin then quit and reopen the app

@richburdon

**Comment by wittjosiah** [comment]
@mjamesderocher I tried to reproduce this and wasn't able to, is there anything else you did on your machine to make this happen? I was able to turn on IPFS plugin and restart the socket runtime and have the app startup.

**Comment by mjamesderocher** [comment]
I can't replicate it now. I was seeing it on Monday when I was on a call with Rich and yesterday I saw it occasionally the other day while working on the mac app, but it wasn't every time I opened the app. So we can close this and if I experience it again, I will try to see if I can track down more details of what was causing it.
