### ISSUE TITLE
[composer] Framework architectural issues

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#4994]
- [ ] Reconcile Client/Space plugin handling of space join/share
- [ ] Reconcile Layout/Settings/NavTree plugins (e.g., coordination of dialogs)
- [ ] Normalize file structure of app-framework plugins (and other: e.g., props, types, provides)
- [ ] Remove complementary sidebar special case (requires close button for mobile)
- [ ] Universal keyboard navigation (sidebar, stack)
- [ ] react-ui-components (for high level patterns: e.g., List, SettingsValue)

## PRs

- https://github.com/dxos/dxos/pull/4986
- https://github.com/dxos/dxos/pull/4995
- https://github.com/dxos/dxos/pull/4996

**Comment by zhenyasav** [comment]
this looks like an outdated grab bag of random quality of life stuff, let's revisit these when they come up in a prod scenario
