### ISSUE TITLE
[files] export and import to folder

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#5039]
- [x] Add root folder selector in spaces panel in settings
- [x] Commands/hotkeys
- [x] Export documents:
  - [x] preserve folders
  - [x] export comments
    - https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields
  - [x] markdown metadata (Front Matter) 
  
![image](https://github.com/dxos/dxos/assets/36420699/618112a5-6cab-4a9e-b4e0-f25f81a79192)
- [ ] Export svg
- [x] Export space metadata

## Next
- [ ] import space
  - [x] import documents
  - [ ] import Obsidian repos

## Later
- [ ] Generate PDF
  -  https://unifiedjs.com/explore/package/remark-pdf
- [ ] Save PDF to IPFS command (via plugin-ipfs)
- [ ] Print command
- [ ] Generate HTML via remark/rehype
  - https://github.com/remarkjs/remark-rehype
https://github.com/dxos/dxos/blob/3f845e1bc934827287730df1c393b6d0d1b1ecce/tools/apidoc/src/remarkDocumentation.ts#L20
- [ ] Publish spaces as HTML via agent ($$$)
- [ ] https://automerge.org/blog/2023/12/21/merry-commitmas/#updatetext-for-easy-integration

**Comment by jessmartin** [comment]
@mykola-vrmchk are you still working on this? I was just trying out the local files plugin and I have some questions / feedback. Curious what the use case is here.
