### ISSUE TITLE
[authoring] CodeMirror extensions review

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5053]
> comments.ts

What is this signalling with its onUpdate? It looks like that'll update some other UI component (sidebar?) but I couldn't get anything visible to happen. Is doing this with a push callback preferable to trying to integrate it into the regular app update cycle with a pull-style approach? I'm always wary of stuff that triggers further update cycles after an update, since that runs the risk of inefficient cascading, but I guess this probably won't feed back into the editor?

In any case, it might be worth A) avoiding doing any work in the update listener when the doc and selection stay the same, B) comparing the pushed value to the previous one and avoiding signalling anything if they stay the same in all ways relevant to the consumer.

→https://github.com/dxos/dxos/issues/5040

> link.ts

Storing positions in the widgets (and comparing them in eq) is not recommended. It'll cause the widget to be redrawn every time content before it changes size. It should be possible to define widgets in a position-independent way and allow them to stay inert even if they move in the document. You can use view.posAtDOM(widgetDOM) to query their position dynamically in event handlers and such. ✅

This currently runs over the entire document. It seems like it would be preferable to only go over view.visibleRanges. ✅

> tooltip.ts

Any reason this uses a regexp, not the parse tree, to locate links? It currently also triggers for link-like syntax in, for example, a code block. ✅

The positioning of the tooltip seems off. I expect this is due to React async rendering, hiding the actual dimensions of the tooltip from the CM tooltip logic. If possible, I'd recommend just using plain DOM to render these. If not, we'll have to somehow schedule a requestMeasure after React does its thing. ✅ (doesn't reproduce anymore)

> listener.ts

Any reason this isn't just an EditorView.updateListener? ✅

> autocomplete.ts

You seem to be loading the default completion keymap twice at the moment. But the TODOs sound like the plan is to create a custom one at some point. ✅

Using the override option will kill all language-specific completion (say, in code blocks), as well as not combining with other completion sources that try to use it (as in the mention plugin). It's probably better to use markdownLanguage.data.of({autocomplete: ...}) to register this instead. ✅

> highlight.ts

Is this used? The way the decorations are entirely static (not even mapped through changes) seems worrying. ✅

> image.ts

Again can probably create decorations only for the visible text. ✅

> table.ts

Clicking back into the table doesn't work at the moment, since it's non-editable DOM. Could do something simple like putting the cursor at its start, or try to figure out where exactly the user clicked and put the cursor in the proper place. ✅

Again it seems unnecessary to store and compare positions in the widget. ✅

> tasklist.ts

Wouldn't it be better to just leave text spaces for the list indentation? Both to avoid work in the plugin, and to make those editable to the user.

Also does the thing with positions in widgets again. ✅

**Comment by richburdon** [comment]
> comments

Agreed — and your assumptions are correct, but for background: Composer has its own extensibility framework called plugins, which can be independently loaded and arranged in the main layout (directionally like VSCode). E.g., the main text editor (@dxos/plugin-markdown/MarkdownPlugin) can render/edit both DXOS ECHO (p2p replicated data via the SpacePlugin and local files via the LocalFilePlugin. Comments are rendered in a separate (right-side) sidebar via the ThreadPlugin. And comment threads are stored as separate ECHO objects. The editor is currently passed an array of references to these threads, including a relative cursors string (from YJS/Automerge) that is used by the state field reducer to generate the highlight ranges. Clicking on a range (or moving the cursor near one) calls the onUpdate callback (perhaps this should be called onSelect), and creating a new thread calls onCreate. Communication between plugins is done via high-level async application events called intents.

Re A/B. Yes that would be ideal.

Additionally, there should be a notification in the other direction where selecting a thread should scroll the editor to the correct position. I assume via: https://codemirror.net/5/doc/manual.html#scrollIntoView

## Additional work:

- Dealing with delete/copy/past of text that contains comment highlights.
- Dealing with overlapping ranges (e.g., preventing them?)
- ADVANCED: Ability to change ranges once defined.

Attaching here the demo video for comments:

https://github.com/dxos/dxos/assets/3523355/286c2dcb-aa1a-48dd-9293-8cfd3eb8bc24

**Comment by richburdon** [comment]
> links

Yes, neither of these seemed right. I wasn’t sure about the lifecycle, and I had a TODO re visible ranges (which as you point out should be addressed in many of the other extensions).

**Comment by richburdon** [comment]
> tooltip.ts

First, I have now combined this with the link extension.

I haven't looked into this yet, but I wondered if using something like React SSR would allow us to synchronously render the DOM element. I agree that for small components like tooltips, menus, etc. we should just use native DOM and try to reconcile how we style them vs. the TailwindCss definitions we used throughout the system. 

There will be cases though where we might want to show a more complex view (e.g., a popover that displays a rich card view of a linked object). So I think I’d like to a) remove the React callback here; b) motivate an extension that does use React SSR to show more complex information. E.g., I have the beginnings of a “mention” plugin that autocompletes a user — and the popover may be the user’s current status and contact card.

**Comment by richburdon** [comment]
> listener.ts

Nice. Done.

**Comment by richburdon** [comment]
> autocomplete.ts

We need to consider how to unify the CodeMirror and Composer keymaps/bindings — and make them work cross-platform, and make them user configurable (UX issue). Also we have a HelpPlugin that displays all key bindings in a dialog — plus shows hints at the bottom of the display based on the user’s current activity (e.g., when highlighting text it might show the “create comment” shortcut). A short discussion might help here.

**Comment by richburdon** [comment]
> highlight.ts

This is now incorporated into the comments extension.

**Comment by richburdon** [comment]
> image.ts

Agreed and would welcome a PR.

**Comment by richburdon** [comment]
> table.ts

Agreed and would welcome a PR.

I have also experienced a bug in this and other widgets whereby when moving the cursor down towards the table, it jumps back to the beginning of the document. I haven’t completely isolated this yet, but I’ve seen the same problem with other widgets (e.g., Horizontal Rule, Tasklist) when there isn’t whitespace before and after the markdown that generates the widget.

https://github.com/dxos/dxos/assets/3523355/dbcea7ce-58a1-41d7-8840-fae5c4551ea6

**Comment by richburdon** [comment]
> tasklist.ts

A number of things here:

a). You mean spaces rather than CSS indents? Hmmm does that seem intuitively more stable, although it also feels open to inconsistencies (e.g. what does 3 spaces mean?) 

b). Separately, you currently have to press enter multiple times to "end the list". I.e., pressing enter once starts a new bullet, but I'd expect pressing again to end the list, but instead it creates a new line with an orphaned bullet.

https://github.com/dxos/dxos/assets/3523355/ded2531f-9066-4dcb-9a7c-a98408bc7a99

<img width="1728" alt="Screenshot 2024-01-06 at 9 29 59 PM" src="https://github.com/dxos/dxos/assets/3523355/f4c14693-8746-4f2f-850e-04eb5e8d9976">

c). I have also experienced a bug in this and other widgets whereby when moving the cursor down towards the table, it jumps back to the beginning of the document. I haven’t completely isolated this yet, but I’ve seen the same problem with other widgets (e.g., Horizontal Rule, Tasklist) when there isn’t whitespace before and after the markdown that generates the widget.

https://github.com/dxos/dxos/assets/3523355/dbcea7ce-58a1-41d7-8840-fae5c4551ea6

d). Related: I've been wondering how to reconcile with our outliner plugin that will have a richer drag/move and drill-down experience (like LogSeq).

**Comment by richburdon** [comment]
miscellaneous:

1). There's an initial "jitter" when rendering documents where the decorations will replace part of the text. E.g., below. 

https://github.com/dxos/dxos/assets/3523355/de109768-ee27-45d2-ad0f-a62ff93baecd

**Comment by marijnh** [comment]
> a). You mean spaces rather than CSS indents? Hmmm does that seem intuitively more stable, although it also feels open to inconsistencies (e.g. what does 3 spaces mean?)

Whatever it happens to mean in Markdown, I'd say. If the general UI is that of a text editor, and Markdown lists are easily manipulated with text editing, I'd say that's a preferable way than having to provide custom control to lift/sink the depth of these task list items.

> b). Separately, you currently have to press enter multiple times to "end the list". I.e., pressing enter once starts a new bullet, but I'd expect pressing again to end the list, but instead it creates a new line with an orphaned bullet.

Markdown supports both 'tight' lists (no blank lines between items) and non-tight lists (which will, in the output, cause each item to be wrapped in a paragraph). The command @codemirror/lang-markdown binds to enter allows you to press enter once for a tight list continuation, and twice to add a blank line (and three times to clear the list continuation).

> c). I have also experienced a bug in this and other widgets whereby when moving the cursor down towards the table, it jumps back to the beginning of the document.

I did not manage to reproduce this. Your video shows a link, not a table. But trying to create a document similar to what it shows and arrowing down, the cursor enters the link, and doesn't jump.

> d). Related: I've been wondering how to reconcile with our outliner plugin that will have a richer drag/move and drill-down experience (like LogSeq).

Maybe open a separate issue with a more detailed description of what you're thinking of here?

**Comment by marijnh** [comment]
> 2). I've also noticed the absence of scrollbars here. Quite likely something we've overlooked, but since CM virtualizes the viewport I don't think I understand how you handle scrolling.

The default for CodeMirror is to expand to fit its content, which appears to be what's happening here. The scrolling happens on your `<main>` element. I'm not sure why its scrollbar isn't visible.

It is also [possible](https://codemirror.net/examples/styling/#overflow-and-scrolling) to make the editor do its own scrolling.

> 3). Is there a simple way to prevent widgets (like links) from opening up when cursoring up/down through the document?

You mean something like a delay before a link expands?

**Comment by marijnh** [comment]
PRs #5051, #5052, and #5077 implement some of the proposed changes here.

**Comment by marijnh** [comment]
Let's move discussion of comments/threads to https://github.com/dxos/dxos/issues/5040

That leaves the task list indentation question as unresolved in this issue — @richburdon do you agree with the idea of using text for indentation, instead of including it in the widgets, or not?

**Comment by richburdon** [comment]
****
