### ISSUE TITLE
Load spaces as needed

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5086]
- [platform] by default don't open any spaces
- [composer] call open on spaces as they're selected, don't disable selection in tree just because they're closed

**Comment by wittjosiah** [comment]
@dmaretskyi is this still something that would help with app startup time or has that largely been mitigated by no longer waiting for spaces to be ready when initializing the client?

@zhenyasav do you still think this is something worth doing regardless of the answer to the above question?

**Comment by dmaretskyi** [comment]
https://composer.dev.dxos.org/2c5c10a8d82eab3a52b30522c14e3f3e37ea3ead365cd7c74e8d3830d313cdd5

**Comment by wittjosiah** [comment]
superseded by #6558
