### ISSUE TITLE
[devtool] publish latest devtool extension

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5136]
Devtools chrome extension is working, it's just not being published

last version is 0.3.1 from October or 2023

**Comment by mykola-vrmchk** [comment]
![Image](https://github.com/dxos/dxos/assets/36420699/8371d549-2d70-47e4-a332-f54eccf7aa98)

we need a privacy policy page that is compliant with https://developer.chrome.com/docs/webstore/program-policies/privacy/

https://www.freeprivacypolicy.com/blog/chrome-apps-extensions-privacy-policy/

**Comment by jessmartin** [comment]
@mykola-vrmchk here's the link: https://dxos.org/privacy/

 can you move this forward?
