### ISSUE TITLE
[authoring] hide control characters by default

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5150]
Duplicate: https://github.com/dxos/dxos/issues/5346

Equivalent to Obsidian's "Live Preview" mode, all control characters should be hidden unless they're actively being edited.

(See [Obsidian's Markdown reference](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax))

- [x] #5155 
- [ ] Add bullet list rendering
- [ ] **bold**, *italic*, ~~strikethrough~~, `variables`
- [ ] block quotes
- [ ] code blocks
- [ ] Headers
- [ ] horizontal rules
- [ ] we may want to also consider a "View Source" mode which just always shows the plain markdown

**Comment by jessmartin** [comment]
I consider these nice-to-haves, P1, maybe.

Here's how I'd rank them in order of importance, personally:

**P0**
- https://github.com/dxos/dxos/issues/5155
- Add bullet list rendering
- block quotes

**P1**
- code blocks
- headers

**P2**
- view source / raw markdown mode
