### ISSUE TITLE
[comments] no way to close right sidebar on mobile because button offscreen

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5159]
repro:
- open composer on mobile
- toggle the right sidebar in top right
- you cannot close it, even with refresh

(for iOS Safari, the only way out is to delete all data for the dxos.org domain because right sidebar open state is stored in local storage)

**Comment by thure** [comment]
What is “s2”?

**Comment by jessmartin** [comment]
@thure updated!

**Comment by thure** [comment]
fwiw the canonical name for this component is “complimentary sidebar” (I shorten to “c11y sidebar”), but understood 👍

The design for this will substantially change, and this may have already been resolved by #5309.

**Comment by wittjosiah** [comment]
@thure FYI this isn't resolved by the above PR. I still got stuck on dev with this over the weekend. I think it would make sense to resolve this at the same time as #5237 though.
