### ISSUE TITLE
[organization] deleting a folder removes all the items in the folder without a way to navigate back to them

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5165]
## Motivation

One day we will have the ability to discover unlinked content and search and browse dynamically. Until that day, we need undeleted content to remain always visible and navigable from the left sidebar. We support the ability to delete folders; deleting a folder should not hide all of the content inside that folder.

## Finish Line

- When deleting a folder, the content that was inside the deleted folder should be moved to be parallel to the folder that was deleted

**Comment by wittjosiah** [comment]
What's the proposed solution? This almost feels related to "Search" as a way to discover unlinked content.
