### ISSUE TITLE
[organization] remove the upload image button at the bottom of stacks, move to regular action

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5168]

**Comment by wittjosiah** [comment]
This is higher priority because it leads to broken functionality is the default application setup.

**Comment by richburdon** [comment]
how so? this should only be visible when the appropriate plugins are enabled.

**Comment by wittjosiah** [comment]
@richburdon the problem is that currently that's not true, it's visible when stacks plugin is enabled even if ipfs plugin is disabled. This functionality should only be available when IPFS plugin is also enabled.

**Comment by richburdon** [comment]
ok then i'll fix that.
