### ISSUE TITLE
[authoring] CodeMirror tasklist

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5184]
Illustrated in the video below:

- [x] Bug: Cursor jumps when moving down into block (if in first column)
- [x] Bug: Formatting breaks when pressing Enter in front of a bullet that has indented children
- [x] Convert indents to natural spaces
- [x] Remove checkbox widget (convert back to text) when cursor moves into it (popular request; and similar to Obsidian)
- [x] Pressing Enter on an empty last line of the list should end the list (currently have to press Enter three times)
- [x] Restore previous position of cursor after clicking on checkbox

https://github.com/dxos/dxos/assets/3523355/e76f6b22-958d-408f-866b-2ed22a5dd290

**Comment by richburdon** [comment]
I get the point, but I do think the behavior implemented __here__ in this GitHub textbox is more intuitive.

```
- [ ] 1
- [ ] 2
- [ ] 3
- [ ]               << pressing enter here will end the list.
```

**Comment by marijnh** [comment]
One thing I've been considering is to make that command a bit smarter so that, for the first list item you get the current behavior (single-item lists not super common), but then for others it only goes through the spacing of the rest of the items (no blank line if the list is tight, blank line if not), so you can exit it with two enter presses. Does that sound like it's work for you here?

**Comment by marijnh** [comment]
Well, [here](https://github.com/dxos/dxos/blob/main/packages/ui/react-ui-editor/src/themes/default.ts#L166) is the reason your widgets misbehave and break the cursor. Patch 560f82b5d9 , for some reason, intentionally breaks CodeMirror's hack that prevents precisely this.

**Comment by marijnh** [comment]
Upgrading to @codemirror/lang-markdown 6.2.4 should help with `Enter` key behavior. Is bumping a dependency just a matter of updating the relevant package's package.json, reinstalling with pnpm to update the package lock, and committing the result?

**Comment by marijnh** [comment]
@richburdon Please see https://github.com/dxos/dxos/pull/5221, https://github.com/dxos/dxos/pull/5222, and https://github.com/dxos/dxos/pull/5223

**Comment by jessmartin** [comment]
@richburdon the entire checklist is checked off. can this issue be closed now?
