### ISSUE TITLE
[composer] scrolling bug

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5201]
Container doesn't scroll properly when navigating via holding cursor up/down.
- [ ] scroll bars are obscured by s2
- [ ] editor scroll bars end up underneath the header at the top of the screen
- [ ] editor is covered at the top with the header bar

**Comment by thure** [comment]
Can you provide repro steps, or a screen capture?

**Comment by richburdon** [comment]
@thure create a long document: press enter 100 times then key up 100 times in composer.
contrast this with a long document in react-ui-editor storybooks where it works fine.

**Comment by thure** [comment]
I thought this had been resolved a while back…
This has probably since been resolved by #5776 and its predecessors. Closing for now, please reopen if needed.
