### ISSUE TITLE
Airplane mode causes networking to break

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#5209]
See failing test in https://github.com/dxos/dxos/pull/5015

**Comment by nferch** [comment]
@mykola-vrmchk the test is failing due to the MMSTopology rate limiting which seems to be working as intended. Not sure whether if the test failure is the same cause as the airplane mode issue with the WebRTC transport?

**Comment by mykola-vrmchk** [comment]
Problem: peers failing to reconnect after going back online from airplane mode

Repro steps:
1) Start two composer peers
2) Connect them through space invitation
3) Observ normal connectivity/replication
4) Open devtools for one of the peers  and navigate to `devtools#/mesh/signal` panel
5) Press the toggle connection button on devtools signal panel
6) Wait for replication to stop (it should be almost immediate)
7) Make some changes in any composer peer
8) Togle connection back online
9) Observe how peers fail to connect on the first try and successfully connect on some retry (not 100% reproducable now, some times they connect normally on first try)

**Comment by nferch** [comment]
@mykola-vrmchk how frequently were you seeing this break? i tried it five times and it reconnected every time in around ten seconds.
