### ISSUE TITLE
[composer] stop using letters, always use jdenticons

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5231]
jdenticons are unique but not clearly identifiable enough to be useful, especially at the sizes that we usually render them at

**Comment by thure** [comment]
I’m not sure this change is sufficiently motivated — I think it’s an antipattern (in UX design) to _need_ Avatars to be uniquely identifiable when not accompanied by their label, except where you’ve asked the user for content to use.

We should instead focus on carrying out the next designs, which don’t leave avatars representing potentially anonymous entities unlabeled. When consistently labeled, it won’t matter what fallback content Avatars use.

**Comment by wittjosiah** [comment]
@thure I'm realizing now that it's not the letters specifically I was thinking of here but the fact that when using letters it affords a colour, which also matches the cursor. Certainly the labelling is at least as important (and the current presence control does afford tooltips for display names).

The other part of the motivation for this is that after experimenting with the coloured circle letters in presence, the avatars are now inconsistent across the app. So this issue is perhaps more "make the avatars consistent and useful" than strictly "letters fallback".

**Comment by thure** [comment]
> affords a colour, which also matches the cursor.

If the goal is for the user to be able to see a legend for who is behind the cursors in a document, I don’t think this path will be worth the effort. Mainly, as soon as we introduce profile pictures, the color will not always be visible, making the one signal that yields the benefit unreliable. We’re also cutting full avatars from the presence indicator in the next design.

I think we should augment the Viewers feature in the design increment to provide this legend, if we feel a legend is a valuable deliverable.

**Comment by wittjosiah** [comment]
Fair enough! I think we should at least align them for consistency though? If the easiest way to do that is switching presence to use jdenticon until the next design iteration, then I think we should do that.
