### ISSUE TITLE
[composer] navbar doesn't condense content nicely on mobile devices

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5240]
- navbar-end content is missing (screenshot is of personal space, but seems to hold for shared spaces too)
- ideas:
  - allow double height navbar when at top of page
  - only show last breadcrumb on small screens

![Image](https://github.com/dxos/dxos/assets/4529818/b929a102-005c-47df-ba9c-e475f381ea90)

**Comment by zhenyasav** [comment]
i vote showing only the last breadcrumb here
