### ISSUE TITLE
[composer] client plugin startup failure causes navtree plugin to throw

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5258]
we think the client startup should trigger the error boundary directly, right now for some reason the navtree is allowed to continue loading and fails when it doesn't receive a client.

repro steps:
- load composer dev in safari and allow it to load and settle (you will see readme)
- press refresh, reload the app
- the app waits 30s and throws error boundary

**Comment by wittjosiah** [comment]
I think there's likely a gap somewhere in how the plugin host is catching plugin initialization errors. What I think was happening in the scenario you're describing is that something was causing the client plugin to be excluded from the set of available plugins and thus the client context not included. The client plugin is specifically setup to avoid this ever happening by catching any error that occurs during initialization and bubbling it up inside react to trigger the error boundary.

Unfortunately I'm unable to reproduce this specific scenario to try to to track it down. Mykola fix the underlying error that caused this to happen this morning, but even checking out code prior to that I'm seeing a reasonable error in the error boundary

![Image](https://github.com/dxos/dxos/assets/4529818/eae2b85f-a49b-4ac1-935f-74232ee81b1f)

I'm going to mark this resolved for now but if you encounter other examples like this, note them on #4977
