### ISSUE TITLE
[sharing] copy invite link button has indistinct hover signifier

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5344]
when buttons dont have a label, perhaps the tooltip should be a bit more quick to show (~50ms) as opposed to how regular tooltips show (~1-2s).

In addition, the copy buttons (in the invite) should have immediate hover affordances, otherwise they don't feel like buttons.

**Comment by thure** [comment]
(As mentioned in my PR)

In principle, button hover states should conform to [WCAG SC 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html), though this would involve some salient design changes. The result would not be dissimilar from macOS’s hover treatment for menu items.

https://github.com/dxos/dxos/assets/855039/6599176d-33e8-43ae-8d32-4b0487327ff0
