### ISSUE TITLE
[sharing] drop invite code from url when joined successfully

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5347]
i joined, then took a PWA toast, and the reload caused the invitation flow to kick in again. This shouldn't have happened because the invite code should have been stripped.

**Comment by wittjosiah** [comment]
@zhenyasav there is logic to remove the invite code from the url after a successful invitation https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-space/src/SpacePlugin.tsx#L146-L152. I just tested it and it works at least in the happy path. I'm going to attempt to reproduce the issue in a production build when hitting a PWA toast, but if I'm unable to do that I'll label this as `norepro` for now.

**Comment by wittjosiah** [comment]
@zhenyasav I think I know what happened. The code is only cleared on the app callback and that only happens after you click "done" on the welcome screen. The solution to this is likely #4079
