### ISSUE TITLE
[composer] bug: editor settings has a random large, blank text area

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#5349]
Not sure what it is or why it's there.

![image](https://github.com/dxos/dxos/assets/27258/34156b4b-4d07-4c4e-a461-618429d2e324)

**Comment by wittjosiah** [comment]
@jessmartin I'm looking at the code and that text area [is attached to the setting above](https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-markdown/src/components/MarkdownSettings.tsx#L42-L55). Would it make more sense to you if the text area was only shown when the switch is on?

**Comment by zhenyasav** [comment]
it needs a label and yes if it's conditional on an option it should likely appear/disappear with that option
