### ISSUE TITLE
[composer] feedback button for users to send feedback to the team

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#5384]
### Motivation

Make it easy for end-users to send us feedback.

### Finish Line

- button in the UI that brings up a form so that users can send feedback
- could just be a `mailto:` for now
- or send an email or post a message somewhere
- give them the option of including their public key so that we can look for their telemetry (errors, etc)

**Comment by wittjosiah** [comment]
I'd proposed that we use Sentry as the backend here https://docs.sentry.io/platforms/javascript/guides/react/user-feedback/. Optionally we could use their widgets as well but even if we don't want that we could use their user feedback sdk and use Sentry to track and notify the team about feedback.

**Comment by zhenyasav** [comment]
today we had another meeting about this and leaned into sentry user feedback as the right choice
