### ISSUE TITLE
[comments] highlight the top comment scrolled into view when clicking on commented ranges

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5401]
as the sidebar scrolls into view when clicking on commented text ranges, it's unclear which thread is actually related to the clicked range. We need to highlight the thread somehow.

**Comment by thure** [comment]
This was resolved by #5392.

**Comment by richburdon** [comment]
- [ ] Should scroll the textbox (bottom) of the thread into view.
- [ ] Should have "overscroll" area below so that the user can scroll the textbox into the middle of the sidebar vertically.

**Comment by thure** [comment]
Changing priority to reflect that additional refinements are probably not P0. Please reevaluate priority when reopening issues @richburdon.
