### ISSUE TITLE
[composer] telemetry dashboard

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5402]
see spec here https://github.com/dxos/product/blob/main/2024-Q1/specs/composer-telemetry.md

**Comment by wittjosiah** [comment]
Initial step here is helping to land #4454

**Comment by wittjosiah** [comment]
Making this issue dashboard-specific. Instrumentation done with #5641 via #5414, feel free to re-open #5641 or open a new issue if we find missing data from the spec.

**Comment by jessmartin** [comment]
@zhenyasav what say ye
