### ISSUE TITLE
[authoring] when switching from one doc to another (large-ish) doc, editor crashes

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5429]
Duplicate of [#5415](https://github.com/dxos/dxos/issues/5415)

repro steps:
1. create two docs
2. put a lot of content into one
3. switch from the small to large one

![Image](https://github.com/dxos/dxos/assets/4529818/6f493c52-c626-4263-a4c8-ceddf96bb189)

![image](https://github.com/dxos/dxos/assets/4529818/b419421a-332a-443c-b5a5-75a247fdba10)

**Comment by wittjosiah** [comment]
@richburdon in my testing #5520 did _not_ resolve this issue.

**Comment by richburdon** [comment]
Duplicate of [#5415](https://github.com/dxos/dxos/issues/5415)

**Comment by richburdon** [comment]
I can't repro this (in current production app).
