### ISSUE TITLE
[comments] Mosaic tiles containing an `Expando` object aren't displayed properly in the sidebar

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5458]
- [ ] need storybook for different block content (text, json, mosaic objects)

![Image](https://github.com/dxos/dxos/assets/4529818/2f373157-e965-4c36-b81d-146a9918ec77)

**Comment by richburdon** [comment]
See https://github.com/dxos/dxos/pull/5563

`WildcardPlugin`'s `isTileComponentProps` test is failing for the surface provided by MessageContainer

```
<Surface role='card' limit={1} data={{ content: item }} fallback={title} />
```

**Comment by richburdon** [comment]
More by luck than judgment I've moved this forward, but I think we need to do some more work on mosaic at some point soon.

<img width="1728" alt="Screenshot 2024-02-08 at 1 26 08 AM" src="https://github.com/dxos/dxos/assets/3523355/d2c23de5-3dd7-4041-9c00-63c4888ffef6">
