### ISSUE TITLE
[comments] layout issues

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5459]
- ~sidebar close button takes up whole header when search is disabled~ [see comment](https://github.com/dxos/dxos/issues/5459#issuecomment-1920086608)
- [x] scrollbar overlaps with thread content and delete button (leave padding to the right)
- [x] comment/message username should be less prominent that message content

---

- [x] leave overscroll space at bottom of thread so that bottom most comment isn't "glued" to bottom of screen
- [x] bottom of comment thread should scroll into view when comment selected in document
- [x] delete (x) button spans entire height of message

**Comment by thure** [comment]
>  sidebar close button takes up whole header when search is disabled

This needs to be deferred to the feature work of adding Plank headings, which may/should also involve the feature work of implementing the notch & rearranging where other furniture of the app goes.

**Comment by wittjosiah** [comment]
@thure is there some interim solution we can use until bigger layout work? This looks pretty rough:

![Image](https://github.com/dxos/dxos/assets/4529818/5465d4c9-8032-47b6-b6da-4b8ae53ba8d9)

Even just not having it grow might be enough?
