### ISSUE TITLE
[authoring] make pasted links automatically clickable

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5530]
if text matches a URL it should just be clickable (Cmd + Click?)

**Comment by jessmartin** [comment]
I believe this can be simply enabled as an option with CodeMirror 6's markdown lezer-parser: https://github.com/lezer-parser/markdown?tab=readme-ov-file#user-content-autolink

**Comment by zhenyasav** [comment]
bumping to P1 as this is a standard feature users tend to expect by default

**Comment by ZaymonFC** [comment]
As part of this we should also allow pasting links over selected text ranges.
