### ISSUE TITLE
[composer] deleting an item while navigated to it triggers loading spinner

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#5536]
## Repro:

- create an folder sidebar and put an item in it
- navigate to the item
- right click the item in the sidebar and delete it
- navigation will stay on the object and it will say "Object not available"
- loading spinner will start in top right trying to load object

![image](https://github.com/dxos/dxos/assets/27258/9d802e68-922a-442b-8b45-bb2f1346d53a)

## Expected Behavior

- navigate somewhere else to an object that exists - maybe to the root of the space?
- no loading spinner 😄

**Comment by wittjosiah** [comment]
@jessmartin I'm unable to repro this based on the steps you provided. FWIW we do attempt to handle the scenario you're describing here https://github.com/dxos/dxos/blob/main/packages/apps/plugins/plugin-space/src/components/PopoverRemoveObject.tsx#L27-L33 perhaps you found an edge case, but not clear right now what that edge case is.

**Comment by jessmartin** [comment]
> I'm unable to repro this based on the steps you provided

@wittjosiah It's when the item is in a folder! Added to repro instructions.

**Comment by wittjosiah** [comment]
Was able to repro and seems to be caused by the same issues as #5174 

> Object viewers is currently disconnected due to an issue w/ deepsignal. This should be resolved when we migrate to echo reactive objects for in-memory state.
