### ISSUE TITLE
[authoring] content failed to render

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5567]
hitting the readme on a new profile 
<img width="1728" alt="Screenshot 2024-02-06 at 8 49 07 PM" src="https://github.com/dxos/dxos/assets/3398896/cb6535c7-dbc2-478c-8a86-07741f47e2eb">

**Comment by wittjosiah** [comment]
@zhenyasav I think we're going to need more repro steps for this one. The error is helpful to see what's causing it to throw but not clear how to get into that state.

This doesn't seem like a new profile considering you have a bunch of other shared spaces?

Possibly related to #5429 but looks like a different error.
