### ISSUE TITLE
[shell] devices appear as undefined:undefined

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5569]
<img width="602" alt="Screenshot 2024-02-06 at 9 13 22 PM" src="https://github.com/dxos/dxos/assets/3398896/4bce8ba3-c87f-44d8-aab5-c1610a1a6538">

**Comment by wittjosiah** [comment]
@zhenyasav there's likely some sdk work involved in longer term solutions here, but in the mean time I understand we want to make this look less broken. Do you have preferences for a fallback value? "unknown" feels just a bad as "undefined" in this case. Generated names are confusing, but at least feel less bad than this in terms of a placeholder.
