### ISSUE TITLE
[docs] groom for vault topology terminology

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5574]
we resolved between "vault" and "vault topology" and now that we've merged with the app domain we should comb through docs for uses of words vault and ensure it's aligned.

**Comment by seagreen** [comment]
No mentions of "vault topology" at all in the repo.

The only mention of "topology" in the `./docs` folder is here, which I doubt is a problem: https://github.com/dxos/dxos/blob/main/docs/content/design/diagrams/archive/mesh-implementation.drawio.svg

The repo as a whole does use "topology" a lot, I don't know enough to tell the context on that.

**Comment by seagreen** [comment]
Based on https://github.com/dxos/dxos/pull/5471 it looks like we might want to get rid of the term "vault" altogether.

**Comment by seagreen** [comment]
> Based on #5471 it looks like we might want to get rid of the term "vault" altogether.

If this is what the issue originally meant and I misread it to mean we just want to get rid of "vault topology", please let me know=)

**Comment by seagreen** [comment]
Update: we definitely want to get rid of all uses of "vault".

**Comment by seagreen** [comment]
This hasn't been done yet btw, there are still a few "vault" mentions floating around.
