### ISSUE TITLE
[navtree] show actions menu on hover on desktop

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5578]
the current right-click affordance is a bit undiscoverable for web users

on desktop, let's experiment with the actions menu showing on hover?

**Comment by thure** [comment]
I can’t think of a precedent of good quality for invoking menus on hover, though of course I sympathize with the discoverability issue. There are other solutions I would recommend trying first:
- revert to three-dots invoker
- make sure equivalent menu is discoverable in the topbar

**Comment by thure** [comment]
If the proposal is just to restore the three-dots menu _invoker_, I’m amenable to that.
