### ISSUE TITLE
[comments] not visible inside code blocks

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5604]
comments are on:
- `const MyPlugin: Plugin<MyPluginProvides> = (context) => {`
- `intentDispatcher`

![Image](https://github.com/dxos/dxos/assets/4529818/5413cf0d-7b41-4219-9698-a1985d99e33c)

**Comment by thure** [comment]
This will be resolved by #5603.

**Comment by wittjosiah** [comment]
Not sure if it was that PR or another, but this is indeed resolved now.

![Image](https://github.com/dxos/dxos/assets/4529818/35462419-15c9-43bb-a27e-3b528ec1d515)
