### ISSUE TITLE
[comments] halo rings in comments not correct

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5605]
here i am clearly online, but my rings are grey

![Screenshot 2024-02-07 at 8 43 53 PM](https://github.com/dxos/dxos/assets/3398896/7b498ecf-1720-4a36-b2a3-caed127932c3)

**Comment by wittjosiah** [comment]
a thought on this one, repeating the same online/offline info every time an avatar is shown feels like it might be _a lot_. Might be nice to have a version of the avatar without the ring to use in some places?

**Comment by thure** [comment]
Good point — every plank will have a presence menu which can always show status… maybe it’s worth only using the rings there and using bare avatars elsewhere? That’s more consistent with e.g. Discord.
