### ISSUE TITLE
[docs] add docs on how to observe queries and objects

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5607]
`query.observe` and `effect` based observation

**Comment by wittjosiah** [comment]
old draft of reactivity docs https://github.com/dxos/dxos/pull/3737

**Comment by wittjosiah** [comment]
@zhenyasav @seagreen this says Pending Review, could you point me to what changes were added to document this?

**Comment by seagreen** [comment]
This would be the closest: https://github.com/dxos/dxos/pull/6892. It uses `effect` but not `observe` though so I'm not sure it's enough to close this issue.
