### ISSUE TITLE
[authoring] extra newline being inserted in bullet list

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5630]
Repro:
1. create a new doc
2. insert the following text
```
# Title

- notes
  - a
  - b

- TODO
  - [ ] a
  - [ ] b
 ```
3. place cursor at the end of the `notes` line
4. hit enter
5. see extra newline

Expected:
- At minimum no extra newline
- Ideally, if there's children beneath the bullet already then it should indent as well

**Comment by richburdon** [comment]
This is intended behavior (from @marijnh).

I.e., the extension supports non-tight lists with spaces between each line.
In this case it assumes you're creating a third non-tight bullet between notes and TODO.

**Comment by wittjosiah** [comment]
A document with only the following
```
- notes
  - a
  - b
```
does not behave the same way and the inconsistency makes it feel broken when I'm using it.

Generally when I hit enter at the end of a line in a list, if it has children already what I'm trying to do is add a child. Curious what @jessmartin thinks because it's possible this behaviour should be limited to an "outliner" extension.

**Comment by marijnh** [comment]
Upgrade to @codemirror/lang-markdown 6.2.4, it has the behavior you're asking for

**Comment by wittjosiah** [comment]
@marijnh looks like we're already using 6.2.4 https://github.com/dxos/dxos/blob/main/packages/ui/react-ui-editor/package.json#L21

**Comment by marijnh** [comment]
Ah, I see, you are in a bullet list with blank lines between the items. Yeah, then you get a blank line before the new item.

**Comment by wittjosiah** [comment]
Seems like the solution is just to not have a blank line between items, then it will not insert more blank lines. Something we may want to keep in mind if we ever write a markdown guide for composer though @jessmartin.
