### ISSUE TITLE
[composer] attention

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5698]
This is the second chunk of several chunks of work being tackled to move Composer towards [the proposed design](https://www.figma.com/file/w9HsmcQattO4slk9fLWjnh/Operating-system-v1?type=design&node-id=42-479&mode=design&t=GyxcgUrV9mUnrLUA-0). The chunks being layout ( #5237 ), attention (this) & deck ( #5148 ).

- reintroduce "presence" to the navtree as attention (both local and remote)
- there will be contention for right gutter of tree items, try putting the actions in a menu beneath the icon for the tree item
  - (precedent for icon in tree being a button: arc, notion)
- update the "plank" headers with improved breadcrumbs & attention

**Comment by thure** [comment]
Waiting for #5797 to merge to minimize churn in this PR.
