### ISSUE TITLE
[composer] kbd shortcuts on windows

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5709]
Chad is using composer as a primary tool on windows using Brave. 

- [ ] shortcuts are printed only with mac CMD icon
- [ ] shortcuts don't work on windows (check that Ctrl is implemented in place of Cmd?)

**Comment by wittjosiah** [comment]
We did add some support to theoretically for cross-platform shortcuts but haven't tried to hook any of them up yet. I don't have a Windows license, but I can at least test that on a Linux machine that the Mac shortcuts aren't used.

**Comment by chad** [comment]
I can help test.  I think linux won't be enough because some of the shortcuts listed appear to be built-in Windows shell shortcuts.

**Comment by wittjosiah** [comment]
@chad if you have any suggestions for Windows alternatives to shortcuts that are currently listed let us know and we can incorporate that.
