### ISSUE TITLE
[composer] chat steals focus

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5711]
stand-alone chat (thread) autoFocus steals focus from any input that is showing in the main screen (e.g., "value" text input in Chain prompt). after every key press in text input, chat box autofocuses.

**Comment by thure** [comment]
Reopening since it’s not quite fixed.

Repros (check means functioning):
- [x] Create a new comment thread in a document
- [x] Post a new chat in an existing chat thread
- [ ] Post a new comment in an existing thread on a document
