### ISSUE TITLE
[composer] thread plugin should be active by default

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5712]
the thread plugin is listed in default plugins in composer-app/main, but for new users is not on by default.

**Comment by wittjosiah** [comment]
@richburdon are you sure they were a new user? If they'd opened composer prior to threads being added to the defaults list then it would not be turned on for them just because we added it to the defaults list.

**Comment by zhenyasav** [comment]
confirmed threads are on by default for anon profile
