### ISSUE TITLE
[composer] Misc editor issues.

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5755]
## Smaller

- [x] Decorator bug with large code blocks.
  - https://github.com/dxos/dxos/issues/5701 
- [x] Do no remove decorations when traversing via up/down key until after delay.
- [x] Render images when scrolling through document.
- [ ] @Mention (selective autocomplete)
  - Auto-complete on typing if `@` otherwise require ctrl-space (e.g., to complete page link dialog)
  - Show "/" tooltip on blank line with popup menu.
- [ ] Smooth scroll into view; ideally able to position in the middle of the viewport.

## Larger

- [ ] Language extension for schema.
  -  Provide example for simple extension to JS language (e.g., https://effect-ts.github.io/schema/modules/Schema.ts.html)
- [ ] Hierarchical editor (e.g., similar to logseq to replace current OutlinerPlugin):
  - drag-and-drop rows (current `dxos/mosaic` lib allows DND across components -- e.g., to/from sidebar).

**Comment by richburdon** [comment]
Scrolling issues:
- don't expand links until delay
- images don't render until select
- jitters when scrolling

Uploading Screen Recording 2024-02-27 at 10.53.56 PM.mov…

**Comment by marijnh** [comment]
PR https://github.com/dxos/dxos/pull/5799 seems to help with the images loading late and flickering when scrolled into view.
