### ISSUE TITLE
[mesh] Peers do not reconnect after WiFi toggle

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#5759]
Repro:

1. Two composer peers on the same machiene with a shared doc
2. Ensure they are replicating with WiFi on
3. Turn off WiFi
4. Turn on WiFi
5. Peers do not reconnect

**Comment by jessmartin** [comment]
yes, please!

**Comment by nferch** [comment]
Is this the same as https://github.com/dxos/dxos/issues/5758? If they're on the same machine and they don't lose connectivity if WiFi is turned off (once that gets fixed), they wouldn't need to reconnect?

**Comment by nferch** [comment]
Can't reproduce, can you give me more details on the repro setup?

**Comment by dmaretskyi** [comment]
I think reconnecting is a separate issue, the connection might be dropped for a variaty of reasons: bad connection, network change, user closing the tab that's holding the active WebRTC session. MESH should be able to reliably recover those connections in a reasonable time.

I'll try to do a screen recording whith a repro for you.

**Comment by dmaretskyi** [comment]
https://github.com/dxos/dxos/assets/35851437/8679cff2-3f65-4c69-8608-1ec02327bed5

also reproes https://github.com/dxos/dxos/issues/5758
