### ISSUE TITLE
[composer] hamburger at the bottom?

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5784]
at least two counts of people finding the "hamburger at the bottom" counter-muscle-memory or "hamburger isn't a real hamburger"

**Comment by wittjosiah** [comment]
1. re "not real hamburger", could be solved by changing icon
2. re: "hamburger at the bottom", I'd caution against immediately changing it to avoid design whiplash. I'd like to see how people feel about it after a longer period of time.

**Comment by zhenyasav** [comment]
all were familiar composer users
