### ISSUE TITLE
[composer] remove personal space icon from nav tree

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5812]
this icon seems spurious, perhaps we can remove it plz? it makes the L0 items look out of alignment

![Screenshot 2024-02-28 at 8 22 02 PM](https://github.com/dxos/dxos/assets/3398896/a8d0ef0b-56e1-4e75-b9b8-4dd46cdf0975)

**Comment by thure** [comment]
Didn’t we add or remove this before? I’m getting déjà vu over here…
