### ISSUE TITLE
[composer] right-click to open context menu in sidebar

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#5816]
I'd like to be able to right-click on items in the sidebar to open the context menu. Much larger click target then having to hit the little triple-dot menu.

**Comment by jessmartin** [comment]
@richburdon I believe you wanted this as well

**Comment by zhenyasav** [comment]
promoting this to P1 based on repeated feedback

**Comment by thure** [comment]
Since this changed somewhat recently, I’ll do this last of the P1’s (as if this were “P1.5”) to avoid design oscillation from occupying too much bandwidth, but let me know if it should jump to a regular P1 position.
