### ISSUE TITLE
[authoring] quick add images to a markdown document

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#5826]
Need to be able to drag-n-drop images into a doc. Images in Obsidian are as easy as copy-paste or drag-n-drop. Need to support that in Composer markdown documents. Can still be a "markdown image" (the `![]()` syntax) but needs to auto-upload an image somewhere (IPFS, likely) and add the markdown image link automatically. 

We can implement this the simple way in the short-term by using our existing IPFS infrastructure and not get into any fancy blob-storage stuff yet.

**Comment by richburdon** [comment]
First pass complete via toolbar.
Drag and drop would be much more involved.
