### ISSUE TITLE
[dxosui] `Icon` component

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5887]
Add an `Icon` component to be used throughout Composer so that `app-graph` (among other things) can stop including `FC`s as properties and just include a serializable icon string as a property to be interpreted by the `Icon` component.

Initially this will likely support a very limited set of phosphor icons which we can use as defaults + emoji which will be used for customization.

## Out of scope

Custom icon sets are out of scope for this issue

**Comment by thure** [comment]
This is resolved.
