### ISSUE TITLE
[authoring] Pasting content into a document with comments throws off highlighting

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#5930]
## Repro

- Create a document and fill with some text
- Highlight some text and create a comment on it
- Paste some text above the commented text
- Note how the comment highlight gets shifted to an incorrect spot in the markup

Refreshing the page fixes it, so it's a rendering issue, not a data issue.

**Comment by richburdon** [comment]
In my testing refresh doesn't always fix the issue; may be data model corruption (i.e., cursors getting out of sync).

**Comment by wittjosiah** [comment]
repro:

https://github.com/user-attachments/assets/6c6d6a67-87a0-430f-bc35-1a6a5ed97ce8

**Comment by wittjosiah** [comment]
This may be related to #7466
