### ISSUE TITLE
[authoring] Cmd+D multiple cursors in conflict with search and replace

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#5950]
This was a key feature I would brag about and it mysteriously was broken today when I tried demoing this in office hours.

Two breaking symptoms I saw:
- in staging cmd+D doesn't do anything at all
- in dev earlier today, it brought up search&replace toolbar at the bottom of the editor that looked unstyled for dark mode

If there's a new feature here, it's in conflict with Cmd+D multiple cursors shortcut (same as vscode) and we cannot use that shortcut for find and replace - that should be Cmd+F or Cmd+Shift+F.

**Comment by richburdon** [comment]
See https://github.com/dxos/dxos/issues/5962
