### ISSUE TITLE
[composer] updates break shared workers

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6087]
we have a lock on the stored data which probably didn't allow the new worker to initiallize?

![image](https://github.com/dxos/dxos/assets/3398896/92a20b50-e4e7-451e-8a2f-ef1585e42b6c)

**Comment by zhenyasav** [comment]
this was also reported on prod
![image](https://github.com/dxos/dxos/assets/3398896/cabc65a9-d9b9-4de6-ae39-d914bd0b09e6)

**Comment by wittjosiah** [comment]
@dmaretskyi previously when we were using locks on storage for client, iirc we allowed those locks to be forcibly stolen. How would you feel about that as a solution here?

1. version 1 starts worker in tab 1
2. a new version of the app is published
3. version 2 starts worker in tab 2
4. new worker steals lock and old worker shuts down
5. in order for tab 1 to be used again, it would need to reload at which point it would connect to the new worker as well

**Comment by wittjosiah** [comment]
Related #6087
