### ISSUE TITLE
[organization] dragging document into stack from another space

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6097]
dragging a document from another space into a stack will duplicate the item in the originating space as opposed to moving/copying it into the target space.

**Comment by wittjosiah** [comment]
@zhenyasav would it be desirable for this to create a cross-space reference?

**Comment by wittjosiah** [comment]
#7003

**Comment by zhenyasav** [comment]
resolved:
- [ ] first lets just fix the bug so the default experience is cheapest and unbroken
- [ ] add space-reference option by default
- [ ] add user-choice infrastructure

**Comment by zhenyasav** [comment]
possible to just "disallow dragging from another space into a stack" as a cheaper solution for step 1 above
