### ISSUE TITLE
[sketch] migrate tldraw files from other tldraw versions

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6099]
## Motivation

A Composer user wants to import the tldraw files they've created using tldraw.com but they are failing to import.

## Finish Line

- The Sketch plugin should support importing tldraw files, regardless of the schema with which they were created.
- Update tldraw to the latest version, currently `2.0.2`
- Ensure we can migrate existing sketch objects created with the previous version of tldraw to the latest version.
- RELATED: to upgrade past `2.0.0.alpha-19`, we need to talk to the tldraw team about a [commercial license](https://tldraw.substack.com/i/139921257/the-new-license) (pricing is unclear)

**Comment by jessmartin** [comment]
Did some exploration on this today and here's some notes:
- Any sketch objects created with `2.0.0.alpha-19` will fail to load once we upgrade unless we manually migrate them.
- TLDraw provides migrations across versions, and it should be possible to run the migration code to get from `2.0.0.alpha-19` to `2.0.2`
   - Here's [an example of the migration with the tldraw-yjs integration](https://github.com/tldraw/tldraw-yjs-example/commit/cc348898065d7f532618f8a888d26a77bd89e429)
   - The migration works by calling [`migratePersistedRecord()`](https://tldraw.dev/reference/store/StoreSchema#migratePersistedRecord) and passing in the serialized schema.
- When a client running an older version of the sketch plugin tries to read a newer file, it's actually possible to do `down` migrations to migrate backwards.

Some open questions:
- How do we get the serialized schemas for `2.0.0.alpha-19` objects when we haven't been persisting it up to this point? Maybe we can deploy the serialized schema in code along with the upgrade and load it somehow?
- How does this interact, if at all, with the work we're doing on echo-schema?

**Comment by zhenyasav** [comment]
blocked on export issue #6490
