### ISSUE TITLE
[stack] show document title in collapsed section

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6166]
![image](https://github.com/dxos/dxos/assets/3398896/d35fa19e-9ac9-44a5-8e93-215037b72ef3)

![image](https://github.com/dxos/dxos/assets/3398896/9a560174-1742-40a1-b092-63f1335986aa)

**Comment by thure** [comment]
This is currently blocked by collections work which I believe @wittjosiah is undertaking.
