### ISSUE TITLE
[sketch] sketch export can't be opened on tldraw.com

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#6179]
We have an export of tldraw sketches that only exports the snapshot, omitting the schema. it's not a complete and valid `.tldraw` file and therefore can't be opened on tldraw.com and other places. Our export only works for us to re-import.

## Repro

- Create a new space
- Create a new sketch and put some stuff in it
- Go to Space: Save to Disk to export the sketch to a json file on disk
- Go to tldraw.com and go to File: Open and try to open the exported json file
- You'll get an error: doesn't look like a tldraw file

**Comment by wittjosiah** [comment]
From tldraw team:

> .com is likely to very regularly be ahead of even the very latest library - we use it as a sort of a testing ground for new library features. it's always at least a week ahead, but often likely a month or more.

https://discord.com/channels/859816885297741824/1238904242131963904/1260524958011097159

Given this, it is likely that we cannot maintain compatibility consistently at this point in time.
