### ISSUE TITLE
[comments] scroll to and flash the location of a comment when clicked

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6213]
we need an affordance on a comment to jump to the anchor location of the thread, and highlight it in a distinct way when attention is on the comment thread

**Comment by jessmartin** [comment]
ran into this again today in a larger document - very annoying!

**Comment by ZaymonFC** [comment]
I can't replicate this now. I did add a 'selected' color affordance to better indicate to the user which thread is selected in the document.
