### ISSUE TITLE
[navtree] scroll assistance jitter

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6275]
https://github.com/dxos/dxos/assets/3398896/10e7088b-e5fe-475f-ba3c-0bffcfbd74ab

**Comment by wittjosiah** [comment]
If this can't be solved without major changes to the navtree then I'd suggest grouping it with #5590

**Comment by thure** [comment]
This should be grouped with #5590, I can’t think of a meaningful solution to this that isn’t exactly that.
