### ISSUE TITLE
[table] support tables in stacks

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6321]
at the moment dragging a table section in a stack can cause the UI to lock up and freeze permanently

**Comment by ZaymonFC** [comment]
Okay the infinite recursion issue is fixed. But another problem has reared its head:

<img width="569" alt="image" src="https://github.com/dxos/dxos/assets/12402727/a3c5b3b6-31f8-4dfd-a8a4-9e3c0913f706">
