### ISSUE TITLE
[docs] upgrades

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6360]
## docs
- [x] #6383
- [ ] #6382
- [x] #6381
- [ ] #6369 
- [ ] #6370 
- [ ] #6375 
- [ ] #6372 
- [ ] #3852 
- [ ] #4644 
- [ ] #4619 
- [ ] #3404 
- [ ] #4348 
- [x] #4338 
- [ ] #2353 
- [ ] #2599 
- [ ] #3707 
- [ ] #5574 
- [ ] #5607 
- [x] #6482 

## samples
- [ ] #5133

**Comment by seagreen** [comment]
Fixed a one-liner (one-worder) to kick the tires: https://github.com/dxos/dxos/issues/6370

**Comment by seagreen** [comment]
Another simple issue: #6372

**Comment by seagreen** [comment]
Small API generation one: https://github.com/dxos/dxos/issues/6375

**Comment by seagreen** [comment]
https://github.com/dxos/dxos/issues/6404: collections of Ian's impressions while I still have a beginner's perspective
