### ISSUE TITLE
[docs] high level diagram

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6382]

**Comment by seagreen** [comment]
### What should the diagram represent?

A dependency graph of the components of DXOS, something like this (don't read too much into this, I just threw this together to start the conversation):

![image](https://github.com/dxos/dxos/assets/1310143/0462dcab-f551-410a-b974-bd368f280395)

Each node could have a linked title and a short description (like HALO does above).

We might want to make two of these, one with the descriptions and a shorter one without.

### What technology to use to make them? (GraphViz etc)

I don't have an opinion here at all. I'll do some research, in the meantime if anyone has suggestions let me know!

**Comment by seagreen** [comment]
Actually it might be better to use Mermaid for this because it works in both GitHub and the docs site without a build step. It will look a little different on both but that's no big deal:
![image](https://github.com/dxos/dxos/assets/1310143/45dc22e6-6b61-49e3-b422-5117f6886aff)

**Comment by seagreen** [comment]
It will look nicer than that though, changed the green background of the nodes to white:
![image](https://github.com/dxos/dxos/assets/1310143/134c8f6b-350b-4c49-8819-fd7c852f3780)

**Comment by seagreen** [comment]
Currently we have two, the syncing one and the SDK components one. The latter is a Mermaid diagram, the former is a PNG (along with a source SVG adjacent to it in the repo so it can be changed later).
