### ISSUE TITLE
[docs] document device join flow and API in typescript guide

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6482]
Right now we're missing documentation and guide about how to invite and receive invites to device join flows in the TypeScript
```[tasklist]
### Tasks
- [x] Document receiving a device-join invitation from typescript
- [ ] Document creating a device-join invitation from typescript
```

**Comment by ZaymonFC** [comment]
A good example for how to do a device share from typescript can be found here. 

https://github.com/dxos/dxos/blob/main/packages/devtools/cli/src/commands/halo/share.ts

This code also relies on the following logic:

https://github.com/dxos/dxos/blob/9c237b7993d58c442bef31a35b28918934ad74f8/packages/devtools/cli-base/src/util/invitations.ts#L24-L64

This is a lot for our API consumers to consider. I think the SDK or some core library should offer helpers here. The consumer doesn't care about the details of what it means to wait for an invitation or how to know if an invitation is accepted.
