### ISSUE TITLE
[composer] private beta user flows

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6491]
This covers work we have to do in composer to support all the private beta restrictions.

[Spec](https://composer.dxos.org/b96bd620e6a2d89506da7b625849cb9d701df457aa2216c6afa5e411d0420e97)

**Comment by jessmartin** [comment]
@zhenyasav which space is this doc in?

**Comment by zhenyasav** [comment]
closing as dupe of https://github.com/dxos/devrel/issues/72
