### ISSUE TITLE
[composer] ability to select editor section of stack

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#6493]
- [x] ENTER should focus the text editor text.
- [x] Pressing DOWN at the end of the document should NOT navigate to the next section (similar for UP).
- [ ] Need more x padding inside of blue selection box. (better to highlight entire section box, not just editor)?

![Image](https://github.com/dxos/dxos/assets/3523355/aa7f8276-d022-4aa0-94a6-96b9e816c1e3)

**Comment by zhenyasav** [comment]
> Pressing DOWN at the end of the document should NOT navigate to the next section (similar for UP).

why not? doesn't that seem counter to what we're trying to do with collections?

**Comment by zhenyasav** [comment]
too hard to deal with x-padding for now, given that you can navigate to-from the rail as well
