### ISSUE TITLE
[stack] wishlist

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6531]
Here is the prioritized list of work as a result of feedback, and the target demo scope for berlin:

P0
- [x] #6562
- [x] #6563
- [x] #6561

P1
- [x] #6571
- [ ] #6566
- [x] #6567
- [ ] #6572
- [ ] #6573
- [ ] #6574
- [x] #6321 
- [ ] #6576
- [ ] #4860 

P2
- [ ] #6596
- [ ] #6597
- [ ] #6564
- [ ] #6565
- [ ] #6598

**Comment by zhenyasav** [comment]
Here is the prioritized list of work as a result of feedback above, and taking into account the target demo scope for berlin:

P0
- [ ] [stack] section drag re-ordering broken
- [ ] [stack] stack section chrome alignment
- [ ] [stack] stack section highlight of drag handle when attended
- [ ] [stack] keyboard navigation to enter/exit the editor of a section isn't working
- [ ] [stack] slow/freezing when dragging the section (maybe it should be more placeholder?)
- [ ] [stack] better collapsed section display

P1
- [ ] [stack] comments on stacks by aggregating all threads from all sections into the sidebar
- [ ] [stack] one-click create content in an empty collection
- [ ] [stack] one click to navigate to a section item
- [ ] [stack] visual alignment of tldraw document sections with text sections in stacks
- [ ] [stack] one click to "add after"
- [ ] [stack] surface in a section state needs to know the "selection state" of that section
- [ ] [table] support tables as a stack section (should be more integrated, not like a rect in a rect in a void)

P2
- [ ] [stack] x-padding around the outline of the editor is too narrow, maybe the outline should go around the stack section?
- [ ] [stack] section height resizability
- [ ] [images] cover/contain for images in stacks

**Comment by zhenyasav** [comment]
Original feedback
- [ ] auto-create a document in a collection when it's created
- [ ] unclear "where the menu is" of a stack section
- [ ] dont want buttons at the bottom of the stack because they exist in each of the section menus
- [ ] collapsing a section should show a stylized first few lines, for drawings it may be the top of the drawing
- [ ] hard to tell what's going on when things are chromeless and there are two empty sections?
- [ ] keyboard navigation to enter/exit the editor of a section isn't working
- [ ] x-padding around the outline of the editor is too narrow, maybe the outline should go around the stack section?
- [ ] one click to navigate to a section item
- [ ] visual alignment of tldraw document sections with text sections in stacks
- [ ] dont think menu+drag button works as a combo
- [ ] freezes / slow when dragging the section (maybe it should be more placeholder?)
- [ ] dont think we should support "Add before"
- [ ] want one click to "add after"
- [ ] support tables as a stack section (should be more integrated, not like a rect in a rect in a void)
- [ ] for tables and images sections to be able to resize the height of the sections (all sections actually)
- [ ] maybe cover/contain for images? (P2/P3)
- [ ] drag/drop things from OS to the stack?
- [ ] comments on stacks by aggregating all threads from all sections into the sidebar
- [ ] surface in a section state needs to know the "selection state" of that section

**Comment by jessmartin** [comment]
@zhenyasav I think this can now be closed since you've created issues for all of the task items
