### ISSUE TITLE
[sdk] make this error less astonishing

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6533]
can we plz rephrase this error to be less confusing - what is hypergraph? where is registerEffectSchema?

![image](https://uploads.linear.app/f2a1cdbf-380a-41ea-bdb3-f0e521270420/af883382-9d92-44bd-bf9b-ad0aeb30144b/92a2485e-0566-4fb1-a090-f327ffb5380a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyYTFjZGJmLTM4MGEtNDFlYS1iZGIzLWYwZTUyMTI3MDQyMC9hZjg4MzM4Mi05ZDkyLTQ0YmQtYmY5Yi1hZDBhZWIzMDE0NGIvOTJhMjQ4NWUtMDU2Ni00ZmIxLWEwOTAtZjMyN2ZmYjUzODBhIiwiaWF0IjoxNzE1MTEyMTg0LCJleHAiOjMzMjg1NjcyMTg0fQ.cKoiCkB2U8bIH61SxRyL5NJnpI4-77GAJG8D1CmxZhA)

**Comment by zhenyasav** [comment]
`client.addSchema()`

**Comment by yarolegovich** [comment]
Not throwing since #6328
