### ISSUE TITLE
[agent] ensure users accept a TOS before agent beta

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6547]
add a checkbox to `AgentConfig` that must be checked before then "start agent" button is enabled.

should include label which links to TOS (link tbd, use https://dxos.org/tos as a placeholder)

**Comment by thure** [comment]
Instead of a checkbox, the state of which will be difficult to maintain in our app, I’ll instead provide a [clickwrap message](https://en.wikipedia.org/wiki/Clickwrap), with the TOS link, above the action for creating an agent.
