### ISSUE TITLE
[docs] page transition animations too slow

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#6548]
Need to speed them up or disable them.

Reported by @ZaymonFC

**Comment by ZaymonFC** [comment]
IME page transitions can interfere with search engine indexing too.

**Comment by seagreen** [comment]
Some details:

You can see the same issue at the VuePress Hope theme site: https://theme-hope.vuejs.press/guide/

There's a Pure Mode option to disable fancy animations, but it didn't have any effect on the page change animation when I tried it: https://theme-hope.vuejs.press/guide/interface/pure.html
