### ISSUE TITLE
[composer] Remove perfomance-intensive queries 

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#6560]
https://github.com/dxos/dxos/blob/286bbb6cdf33fb609190f4d7a0b82eb6c6062be5/packages/apps/plugins/plugin-space/src/util.tsx#L317

This query has an effect of querying ALL data inside echo (equivalent to `SELECT * FROM echo`).

we should query only the metadata typenames

**Comment by zhenyasav** [comment]
also doc that this is a slow query
