### ISSUE TITLE
[stack] one-click create content in an empty collection

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6566]
the original ask was about having a default text document in every new collection, but the proposal here is to:

make the "empty" UX of a collection have single-click actions to create new things in the middle of the screen - like a list or a grid of data types you can instantly create. This can be a good place to subtitle the content types with short descriptions of what they are.

**Comment by thure** [comment]
Pausing for now. I think best to resume after #6471 lands and we have a chance to plan next steps.
