### ISSUE TITLE
[beta] signup link has no auth token when manually admitted

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6568]
tried adding Ian from the hub dashboard and the email he received had no auth token in it:

```
https://composer.space/access?email=mail%40ianjeffries.net&access_token=null
```

**Comment by richburdon** [comment]
i wasn't able to repro this; can you pls try again.



---

We're very happy to enroll you in the Composer Beta.

Please visit the following access link to get started:

https://composer.space/access?email=rich%40dxos.org&access_token=d8931a6250e25779cc14c1153c4ebda5f3d8501a1014eb1278482919cbdcb86a
