### ISSUE TITLE
[stack] comments on stacks by showing comments for currently attended section

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6571]
the ask was to create a comments thread view for collections (stacks), with a concatenation of comment threads from sections.

The current proposal: comments sidebar fills with threads for the currently attended section in a stack. 

We found it hard to imagine the UX being good around all those threads in a big list together, several gaps occurred such as:
- where do the comments on the collections go? do they go at the top?
- how does scrolling work in both content and threads views?
- is there a way to submit a new comment without selecting something? where would that affordance be?

**Comment by zhenyasav** [comment]
let's finish the attention system for this

**Comment by thure** [comment]
Tightly related to the subtask in #6694 about using c11y sidebar exclusively for threads.

**Comment by zhenyasav** [comment]
Also ensure that the comp. sidebar always only shows threads (and you can't move them in/out of the sidebar/plank)

- [ ] constrain threads to right sidebar always
