### ISSUE TITLE
[sdk] resetting a storage may leave some tabs with zombie state

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6610]
saw this in Ian's machine just now where after resetting on composer/devtools and reloading the tab had no effect because he had other tabs open. it worked after closing all tabs and reloading.

**Comment by wittjosiah** [comment]
@zhenyasav can we confirm if this is still an issue. Reset should actually shut the worker down now so this shouldn't happen.

**Comment by seagreen** [comment]
Just tested: reset storage cleared the device's storage even though there was another composer tab open in the same browser.
