### ISSUE TITLE
[table] objects that match the schema for the table don't show up

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#6623]
table doesn't show objects that match the schema for which it was created. (For Berlin, we need to show objects created in Contacts app with the contacts schema as rows in the table).

**Comment by jessmartin** [comment]
P0 because needed for Berlin

**Comment by zhenyasav** [comment]
this had a workaround and we successfully delivered the demo for berlin. Time to double check what's remaining here @jessmartin and help zaymon close this. Merci!
