### ISSUE TITLE
[beta] signup on the website throws cloudflare login

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6679]
after hitting "Join the Beta":
![Screenshot 2024-05-15 at 12 58 39 AM](https://github.com/dxos/dxos/assets/3398896/15e49e99-3d0a-4550-8e37-653683f8f48e)

this shouldn't happen:

![Screenshot 2024-05-15 at 12 58 23 AM](https://github.com/dxos/dxos/assets/3398896/69386a8b-9f8f-4fc9-9ae6-a151f8dbd642)

**Comment by richburdon** [comment]
I inadvertently applied CF Access Protection to the signup API (was supposed to be limited to the Hub portal). Now removed.
