### ISSUE TITLE
[sdk] Composer reset does not clear level/idb data

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#6681]
Reset times out and doesn't reset data.
App is left in an inoperable state requiring manual reset (deleting stores via Application>Storage).

![Image](https://github.com/dxos/dxos/assets/3523355/d04192fb-088b-4c99-bbd5-a074955bac2e)

**Comment by wittjosiah** [comment]
@richburdon can you provide steps to reproduce? we have tests for this so it's working in at least some scenarios
