### ISSUE TITLE
[deck] feedback

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6694]
- [x] constrain tree to left sidebar always
- [x] new planks insert from the left
- [x] attention makes the current plank stand out (higher contrast, primary accents etc)
- [x] deck scrolls to the attended plank
- [x] visible divider affordances 
- [ ] how to make it easier to scroll sideways without a touchpad (traditional mouse input)

**Comment by thure** [comment]
Ensure #6571 comes at the same time as opening comments in the c11y sidebar.
