### ISSUE TITLE
[deck] don't create a plank for space nodes when clicked

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#6794]
As a temporary measure, don't create planks when opening a space because they just add noise to the deck. This is temporary because once #6471 lands spaces will be rendered as a deck.

**Comment by ZaymonFC** [comment]
@thure I think this is done already?

**Comment by thure** [comment]
It should be, though I seem to recall @jessmartin mentioned this as feedback recently, though I’m not able to find the Discord message… worth double-checking before closing I think.

**Comment by ZaymonFC** [comment]
Nothing happens when I click spaces in main. ¯\_(ツ)_/¯, I might be missing something.

**Comment by thure** [comment]
Come to think of it, I did do that recently. I think I’m misremembering Jess’s feedback, I think it was actually something about Threads, so not relevant to this.

Closing the issue.
