### ISSUE TITLE
[deck] comment sidebar toggling nonsense

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6871]
see video below:
- [ ] comments sidebar should not automatically show when selecting a section with comments - it should respect the user preference about whether it's showing or not, only the contents of it may change when user clicks on different things, but it may not toggle it's state
- [ ] comments sidebar does not appear when creating a new comment if it had been previously closed
- [ ] new comment button missing from stack section toolbars, requires navigation to create comments

https://github.com/dxos/dxos/assets/3398896/da4a084c-71fe-49c1-908a-fcb9f34f4be2

**Comment by thure** [comment]
- c11y sidebar only opens:
  - when you create a comment
  - when clicking on a commented range

**Comment by thure** [comment]
Resolved by #6877.
