### ISSUE TITLE
[presenter] when exiting a presentation composer navigates to nowhere

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#6872]
- when exiting a presentation (with deck enabled or not), it auto-navigates to nowhere rather than navigating to the Stack that was just presented. 
- in non-deck mode this is really annoying because it closes all your spaces and the main surface shows nothing

**Comment by thure** [comment]
I can’t reproduce this in Deck:

https://github.com/dxos/dxos/assets/855039/f1949967-1b80-4e74-bfd4-a468203c2c2a
