### ISSUE TITLE
[deck] clicking on a node already open in a plank will scroll to it but not attend it

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6875]
is this by design? seems like it should be ok to just focus and attend it, that seems to be the most probable intent behind "navigate to"

**Comment by zhenyasav** [comment]
correction, this is happening only to text documents

**Comment by thure** [comment]
This issue is probably specific to markdown documents, which signal to Deck that MarkdownPlugin will manage autofocus. That plugin needs to support `layout.scrollIntoView`.

**Comment by thure** [comment]
Closed by typo, reopening
