### ISSUE TITLE
[organization] two add to space actions in deck

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#6910]
> I get 2 add to space options If i open commands from a block that is in a deck

![image](https://github.com/dxos/dxos/assets/27258/b9d39748-b923-4d6e-8023-5f0b1be8ba5d)

**Comment by ZaymonFC** [comment]
No repro

**Comment by jessmartin** [comment]
Select an item inside a collection and you get double the "Add to space" buttons

**Comment by ZaymonFC** [comment]
@jessmartin I still can't repro this. Let's talk about it this week?
