### ISSUE TITLE
DXN spec

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#6953]
# DXN & Reference spec

DXN unambiguously names a resource like an ECHO object, schema definition, plugin, etc.
Each DXN starts with a `dxn` prefix, followed by a resource kind.
Colon Symbol `:` is used a delimiter between parts.
DXNs may contain slashes.
'@' in the place of the space id is used to denote that the DXN should be resolved in the local space.

```

dxn:echo:<space key>:<echo id>
dxn:echo:BA25QRC2FEWCSAMRP4RZL65LWJ7352CKE:01J00J9B45YHYSGZQTQMSKMGJ6
dxn:echo:@:01J00J9B45YHYSGZQTQMSKMGJ6
dxn:type:dxos.org/type/Calendar
dxn:plugin:dxos.org/agent/plugin/functions

```

## DXN encoding in ECHO documents

When DXNs appear in ECHO documents (both JSON encoding and in automerge documents), they are encoded in the IPLD style:

```json
{
  "@type": { "/": "dxn:type:dxos.org/type/Document" },
  "content": { "/": "dxn:echo:BA25QRC2FEWCSAMRP4RZL65LWJ7352CKE:01J00J9B45YHYSGZQTQMSKMGJ6" }
}
```

The example above shows both DXN as a reference to the schema and DXN as a reference to another ECHO object.

## ECHO object IDs

- ECHO IDs are generated in the ULID format: https://github.com/ulid/spec
- ECHO IDs are scoped to a space: different spaces can potentially have colliding IDs that should be treated as logically different.

Example: `01J00J9B45YHYSGZQTQMSKMGJ6`

## Space keys

- Space keys are generated by creating a keypair, and then taking the first 20 bytes of the SHA-256 hash of the public key and encoding them to multibase RFC4648 base-32 format (prefixed with `B`, see [Multibase Table](https://github.com/multiformats/multibase?tab=readme-ov-file#multibase-table)).
- Encoding inspired by how ethereum public keys are derived. 
- Space key encoding needs to be resistant to malicious actors trying to generate collisions without knowing the private key. 

Example: `BA25QRC2FEWCSAMRP4RZL65LWJ7352CKE`

## Open questions

- base32 vs base58 vs base62 for space keys / echo ids --- **base32**
- bytes of entropy for space key --- **first 20 bytes of sha256 (based on ethereum address generation)**
- only base32 works with subdomains
- Bigint Based Algorithm vs Variadic Length Encoding for base32 encoding

## References

- https://ethereum.stackexchange.com/questions/3542/how-are-ethereum-addresses-generated
- https://github.com/ipfs/kubo/issues/4143
- https://stackoverflow.com/questions/69832449/are-there-multiple-base62-encoding-algorithm/75000403#75000403

**Comment by richburdon** [comment]
nice. once locked down, this should end up as an MD file in our docs (with links and a regex for the format).

**Comment by zhenyasav** [comment]
idk what problems this is solving, we outlined a few in the call but i would expect specs to start with written problem statements.
