### ISSUE TITLE
[deck] deterministic scroll-to-plank on navigation

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6979]
right now we don't always or don't fully scroll to a navigated plank, this is apparently due to a problematic scrolling API

**Comment by thure** [comment]
The root cause has remained elusive after nearly half a day of searching. I will pause this for now and may return to it.

**Comment by thure** [comment]
This is most likely a reactivity issue which may resolve with improvements occurring now. We should try to reproduce the issue next week.

**Comment by thure** [comment]
Probably blocked by #7424.

**Comment by thure** [comment]
Blocking this as needing a new repro given recent changes to DeckLayout.
