### ISSUE TITLE
[sdk] external apps require `skipLibCheck` in tsconfig

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7065]
Ideally dxos packages should be packaged in such a way that typescript is happy when checking the published output

ref: https://discord.com/channels/837138313172353095/1254737101950554183/1254737101950554183

**Comment by michielbdejong** [comment]
Oops sorry for the issue reference spam, I was trying out my issue tracker data sync algorithm on live data and ran into some idempotency trouble!

**Comment by wittjosiah** [comment]
Duplicate of #3544
