### ISSUE TITLE
[authoring] `Invalid range` after deleting text that has a comment

### ISSUE THREAD

**Issue by ZaymonFC** [dxos/dxos#7133]
We should decide what to do when a an entire comment range get's deleted.

Should the comment be auto-resolved?

<img width="587" alt="image" src="https://github.com/dxos/dxos/assets/12402727/be768bc6-4a91-4f29-901d-918ec11c9fa1">

**Comment by wittjosiah** [comment]
> Should the comment be auto-resolved?

We made a choice initially that we'd like to continue to render these comment threads but in a "disconnected" state

This probably shouldn't warn but just swallow the error? It's likely a warning due to previous debugging.

**Comment by ZaymonFC** [comment]
> This probably shouldn't warn but just swallow the error? It's likely a warning due to previous debugging.

Ok if the comment range length is zero we should swallow the warning and leave the comment thread in the sidebar.
