### ISSUE TITLE
[authoring] urls that start with "www" don't render properly as links

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7331]
example: https://www.figma.com/blog/how-we-built-the-figma-plugin-system/

repro:
1. copy example url
2. paste into editor

result:

![Image](https://github.com/user-attachments/assets/158a915e-8bce-45cc-8fdf-44637b0d5582)

**Comment by ZaymonFC** [comment]
As far as I can tell these issues are upstream in the https://github.com/codemirror/lang-markdown library.


![Image](https://github.com/user-attachments/assets/483e32ff-b250-49ee-b66d-13da48a24fa4)

### Repro:

1. Go to https://codemirror.net/5/mode/gfm/index.html
2. Paste the following:


```markdown
## URL Issues

Leading `www` breaks formatting.
[www.inc.com](https://www.inc.com)

Trailing `.com/` breaks formatting.
[figma.com/](https://www.figma.com)

Ok.
[figma.com](https://www.figma.com)
[any other text](https://www.example.com)
```

For now, I might check for `www` prefix and trim that from the link text part on paste.

**Comment by ZaymonFC** [comment]
I've addressed this with a bandaid fix in #7340, but I think we should create an issue on the upstream package and see what @marijnh has to say there.

**Comment by ZaymonFC** [comment]
Upstream issue: https://github.com/codemirror/dev/issues/1417

**Comment by wittjosiah** [comment]
this appears to be resolved on `main` after some codemirror deps were bumped, I can't reproduce the issue anymore
