### ISSUE TITLE
Way to get a URL for a document?

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7380]
Currently URLs in Composer hold Deck state, eg `https://composer.space/sidebar-NavTree_main-BLFBW7O3BNXJV7B2SWTPX6P7DZYG3PMTR:01J4HWZ4RSR1ZTK1ATQJV6VXCP+BLFBW7O3BNXJV7B2SWTPX6P7DZYG3PMTR:01J4HWXZR9ND762MD835B2NNEP+BLFBW7O3BNXJV7B2SWTPX6P7DZYG3PMTR:01J3GETDJV9SGMVSGS90YV9653+BLFBW7O3BNXJV7B2SWTPX6P7DZYG3PMTR:01J3GESAYWSSC3993Z88X0ZCP4+BLFBW7O3BNXJV7B2SWTPX6P7DZYG3PMTR:01J4ME27QGNKXTRDJARBF8H9PG+BW2JLGLGMLJJQ7HFX64PTDAP7L3FPNFDX:01J4J4WASQG92EHEY1J8S632T4+BW2JLGLGMLJJQ7HFX64PTDAP7L3FPNFDX`.

I want a way to get a clean URL for two reasons:

- I want to make internal links between documents in Composer. Until we have a link autocompleter that means getting the URL and pasting it into the `[]()` Markdown.
- I want to be able to link to Composer documents on GitHub, Discord, etc.

**Comment by seagreen** [comment]
I wrote the above issue for documents specifically, but I'd really like to be able to get a URL for any object I can view-- sketches, collections, etc.

**Comment by wittjosiah** [comment]
this should be resolved by #7423 because in solo mode the urls should distinctly reference a single object
