### ISSUE TITLE
[shell] multi-use invitation shows red error state even when it succeeded

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7409]
Yaroslav: yeah, so that was a race with >1 hosts. 
I made hosts send offers to guests, because hosts sit subscribed to a topic and receive "peer joined" swarm events. 
when a guest joins, all hosts try to establish a connection. guest accepts all offers but keeps an "active flow lock".
when connection to a host acquires a lock it checks whether we were already admitted through another connection in which case it just cancels the flow. 
host on the other side treats this cancellation as a failed flow.
It's interesting that in the majority of cases (at least locally) the lag for one host-guest pair is long enough for other pair to go through the whole flow and for guest to leave the swarm before another host tries to connect with them.

proposed solution:
multi-use non-interactive (where you don't need to enter an auth code) invitations to have an error state on the host side. Like if it really fails for one guest, you anyway kind of transitioning to the "waiting for the next guest" state.

**Comment by yarolegovich** [comment]
https://github.com/dxos/dxos/pull/8159
