### ISSUE TITLE
[composer] standardize stack/collection language across the app

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7416]
- the language used in the app has not all kept up as we've evolved the interfaces and concepts in the app and needs an audit of how different terms are being presented and used
- proposal: remove `stack` from user-facing language, at this stage stack is just the component used to render a collection and so there's no need to introduce multiple terms

**Comment by seagreen** [comment]
I really like this.

I checked the docs [glossary](https://docs.dxos.org/guide/glossary.html), it doesn't have a `stack` entry, which is good.
