### ISSUE TITLE
[deck] persistent solo mode

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7423]
- The app can be toggled between Deck and Solo mode (via a button in the plank)
  - deck/solo mode is persisted in local storage
  - first run starts in solo mode with view of default space in a stack
- In Solo mode clicking an item in the navtree should change the current selection.
- When exiting Solo mode, if the currently visible item is not in the deck it is added to the deck (per deck insertion setting), otherwise scroll to that item
- When deck mode is active, clicking on a navtree item should toggle the visibility of the item in the deck
  - consider this vs scroll to plank behaviour, how else scroll to plank might be handled, and decide which is most useful/understandable behaviour (related to ui perf & navtree open state)
- when opening a child object, scroll to the section in the collection if the collection is already open
  - show currently attended object in navtree + share with peers (follow up)
- deck state is stored in local storage, url is either an fq object id (solo mode) or `/` (deck)
- plank sizes should be persisted with planks in localstorage
- when moving deck state out of url & into local storage state, remember that reset should clear that state so that the deck starts empty

**Comment by ZaymonFC** [comment]
> when opening a child object, scroll to the section in the collection if the collection is already open

This seems like something we could do as a followup

**Comment by wittjosiah** [comment]
@ZaymonFC it's definitely separable functionality, though I think that it will go a long way to help prevent the deck from becoming unruly so quickly

**Comment by wittjosiah** [comment]
feel free to break it out into another issue to address separately but I think it should still be done in this round of cleanup work
