### ISSUE TITLE
[deck] better handling of scroll positioning

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7514]
The particular jumpiness of the original videos appears to have been resolved but two related issues remain:

1) when navigating to an object it will scroll to the plank but it does not get attended
    - related #7686
2) when entering solo mode the scroll position of deck is lost
    - the ideal experience of entering & exiting solo mode is that the plank just grows and shrinks in place & does not remount
    - at present when exiting solo mode the deck always jumps back to the start

**Comment by thure** [comment]
Are these really P0? Jumping around when the user has initiated a state transition is definitely a perception-of-quality issue, but I’d argue it is not a usability issue if it occurs within ~400ms of the interaction.

**Comment by wittjosiah** [comment]
@thure Sorry, I missed this comment the other day. I think this is definitely a P0 the app feels super janky when the scroll position gets clobbered or it's jumping around.

What do you think about storing the scroll position of the deck so it can be restored when you exit solo mode?

**Comment by thure** [comment]
I would still assert “feels super janky” is not P0, but that can be a retro topic we discuss. Will treat this as P0 anyway for the time being.

**Comment by thure** [comment]
Blocking this as needing a new repro given recent changes to DeckLayout.
