### ISSUE TITLE
[collab] presence dot issues

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7531]
Two Composer issues.

### Missing hover text

Only for blue dots, not white ones.

Screenshot:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/11257ddc-b45a-4f8d-91f8-0d2110fb5755">

### White dot is hard to see

Screenshot:
![image](https://github.com/user-attachments/assets/8d724189-fbf1-41ae-8c29-2f42af5f38da)

**Comment by wittjosiah** [comment]
@thure I also noticed for this one that the `-` still shows on hover and can be removed now
