### ISSUE TITLE
npm  vulnerabilities warning (7 moderate, 38 high)

### ISSUE THREAD

**Issue by gut4** [dxos/dxos#7535]
npm install  @dxos/react-client returns this warnings
```
45 vulnerabilities (7 moderate, 38 high)
```

npm audit 
```
lodash.pick  >=4.0.0
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix --force`
Will install @dxos/react-client@0.1.55, which is a breaking change


lodash.set  *
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix --force`
Will install @dxos/react-client@0.1.55, which is a breaking change

micromatch  *
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
fix available via `npm audit fix --force`
Will install @dxos/react-client@0.1.55, which is a breaking change
```

**Comment by wittjosiah** [comment]
@gut4 which version are you trying to install? based on those logs it looks like 0.1.55? The latest version released yesterday is 0.6.6

**Comment by gut4** [comment]
I install latest version (@dxos/react-async@0.6.6)

**Comment by wittjosiah** [comment]
Ah I see, the message is saying that fix force will install the old version. Thanks for highlighting we'll take a look at this shortly.

**Comment by wittjosiah** [comment]
re: micromatch https://github.com/micromatch/micromatch/issues/249

looks like 4.0.8 was released 8 hours ago, hopefully that will resolve the issue with that package
