### ISSUE TITLE
[map] plugin design

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7571]
## Goals

1. Quickly make the map plugin useful to people
2. Do (1) in a way unlikely to require breaking changes later (thus we should have a long term idea for where the plugin is headed)

### Option 1: Query the parent Collection for tables with `latitude` and `longitude` columns

(or something similar like a single `location` column)

Then use those rows to populate the map. The result would look like this (not actually implemented yet):

![image](https://github.com/user-attachments/assets/50cd1f2a-4b5f-49a1-a0ac-30e010c69d75)

I think this is the favored plan, judging by this comment:

https://github.com/dxos/dxos/blob/6b2704bedef181e8d07d818f6b893c7f20711e2a/packages/apps/plugins/plugin-map/src/components/MapSection.tsx#L12

One question this brings up-- what data do we display if the map is viewed as a single object, not as part of the collection? Querying ECHO for all the collections it's part of might bring up multiple collections, which is awkward.

### Option 2: Explicitly link to a table

Have an "edit" mode for the app with some input fields, such as a link to the table to use, as well as what fields to find latitude and longitude in.

Straightforward, but more work for the user that Option 1.

Also, even with Option 1 above we might want to have an option to name what fields latitude and longitude should be found in.

## Question: should the plugin support saving viewport location and zoom level?

This might be useful. One alternative is to automatically put the viewport location in the middle of the displayed points.

**Comment by richburdon** [comment]
i really like the automatic search for tables in the stack. that would be a great default.
after that we might have some metadata editor for the map (@thure and i discussed using the aux sidebar for this) to specifically create an ECHO query.

**Comment by seagreen** [comment]
Sounds great, let's go with automatic search.

I like how that leads to a future where map creation defaults to as easy as possible, but then (if we write the query builder) is also fully controllable.

The only wrinkle is what to do when the map is viewed as a single object, without an enclosing collection. That doesn't seem too important though. Most of the time it will have one parent collection. We can query for that, autodetect the relevant rows, and display them.

If it actually has 2+ parent collections than we can either display a notice that it's an unusual situation, or we can auto-detect rows from both collections and combine them. Or both.

**Comment by seagreen** [comment]
> If it actually has 2+ parent collections than we can either display a notice that it's an unusual situation, or we can auto-detect rows from both collections and combine them. Or both.

I didn't realize being in multiple collections at once is disabled in the UI right now. That makes this not very important, we can revisit it if we re-enable having multiple collection parents.

**Comment by seagreen** [comment]
Added marker popups with titles on click:
![image](https://github.com/user-attachments/assets/bbc5e610-7fa9-4518-a105-b91a52cd3e45)

**Comment by seagreen** [comment]
Done in: https://github.com/dxos/dxos/pull/7583

There's lots of cool stuff we can do in the future with the map plugin, but this round of design seems complete. Let's open new issues for new stuff we want to add.
