### ISSUE TITLE
[sketch] grid disappears after plank resize

### ISSUE THREAD

**Issue by yarolegovich** [dxos/dxos#7578]
After resizing a sketch plank grid and controls disappear and reappear only after I click on the diagram. 

https://github.com/user-attachments/assets/d66d7e20-5aea-4b6c-83d5-fdfc52405dd1

**Comment by thure** [comment]
The bug is not by design but makes sense, by resizing the plank focus is moving away from the sketch.

I understand we want to maintain attention state within the plank even when its resize handle is used, so will look into it.
