### ISSUE TITLE
[threads] add generic object thread support

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#7590]
- for objects where thread anchoring can't be supported (or is being deferred) an object-level thread should be supported
- the single thread chat experience in the sidebar is different than the multi-thread comments experience, it exists experimentally already but needs to be solidified
- the previous experiment had one thread for the whole space that would be pulled up in the sidebar when not looking at a document, here the proposal is for a thread per object
- similar to documents & sheets, the optional thread should be added to the schemas of objects which support this (initially `SketchType` & `TableType`)

**Comment by ZaymonFC** [comment]
Partially resolved by:
- #7837

**Comment by ZaymonFC** [comment]
Resolved by:
- #7837 (Implement threads in Table / Sketch)
- #7589 (Generalize thread plugin)
