### ISSUE TITLE
[composer] universal grid control

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#7615]
# Motivation

We need a universal grid component that is shared between Tables and Sheets (and possibly other tabular data plugins). It should be fast and able to deal with large datasets.

## Features
- works with sparse data (e.g., sheets).
- works with dense typed row-based data (e.g., tables).
- frozen rows and columns
- frozen columns on left and right (e.g., delete button at end of table row).
- resizable rows and columns.
- draggable rows and columns (reorder).
- able to select rows, columns, ranges.
- editable cells via CM.

## Demo

<img width="1728" alt="Screenshot 2024-09-02 at 1 19 35 PM" src="https://github.com/user-attachments/assets/8ad24b43-7522-47c1-8c88-80aa944f7b9b">

## Prior art
- glide

**Comment by thure** [comment]
Resolved by #7900 and #7853.
