### ISSUE TITLE
Can't recover from fullscreen

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#7617]
- can't invoke fullscreen from shortcut.
- if you do invoke it from CMD-k then there is no way back.
- in general need a way to recover from bad routes since they are now stored. e.g., have path `/reset`.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by ZaymonFC** [comment]
Worth noting that you can recover by refreshing the page.
