### ISSUE TITLE
[navtree] drag-and-drop of object into empty collection doesn't work

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7625]
https://github.com/user-attachments/assets/1d929b3d-0330-4a52-bb95-1cde5c951653

EDIT: This only happens if it's an empty collection

**Comment by thure** [comment]
Dragging vertically and not horizontally will rearrange items — in order to drag an object _into_ a collection, it needs to be dropped below _and to the right_ of the collection in order to trigger that operation.

The position cycling is probably a bug of some kind, though.

**Comment by seagreen** [comment]
Closing because this is intentional (what you do to drop into the collection is move the mouse to the right).

Feel free to reopen if you want an issue for the cycling behavior, but it doesn't seem that important to me.
