### ISSUE TITLE
[composer] Solo-mode navigation issue

### ISSUE THREAD

**Issue by yarolegovich** [dxos/dxos#7644]
The first document in my deck-mode is always displayed when I'm navigating in solo mode.
You can also how "Reliable messaging document" was incorrectly positioned when expanded.

https://github.com/user-attachments/assets/5779e8fa-b83a-4489-862a-74fcbad91cf6

**Comment by wittjosiah** [comment]
@yarolegovich is this still happening on prod? there were a number of fixes made yesterday afternoon around this area
