### ISSUE TITLE
0.6.8 update

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#7663]
## Issues

- [ ] deck: close compl. sidebar if soloing unrelated plank
- [ ] deck: make plugin attended when selected from navtree
- [ ] deck: maintain attention when clicking open/close sidebars
- [ ] deck: avoid flicker (esp. sketch) when selected/toggling solo/deck
- [ ] script: make script dark when attended
- [ ] markdown: readonly (show caret, disable toolbar)
- [ ] markdown: focus-ring is eclipsed by markdown editor (see image)
- [ ] error dialog escapes the bounds; need to put react class in DOM in dev mode
- [ ] new space button

## Editor

![Image](https://github.com/user-attachments/assets/32f2c569-0d5f-411f-8f46-a94df0183fb4)

**Comment by wittjosiah** [comment]
>  make plugin attended when selected from navtree

I think this would fall into the scope of https://github.com/dxos/dxos/issues/7514 Will and I agreed that it made sense for him to pick up grid work for the rest of the week and then circle back to it once we had a chance to review which parts were still problems after all of the changes this week.

>  maintain attention when clicking open/close sidebars

Clicking on a button in the chrome seems like something that would meaningfully remove attention from a plank?

**Comment by richburdon** [comment]
- yeah, i mean plank
- re button -- not always -- i think it's like a toolbar; we restore focus when it's reasonable that the user's intent was to just get something out of the way.

**Comment by wittjosiah** [comment]
> we restore focus when it's reasonable that the user's intent was to just get something out of the way.

managing focus like that can be pretty perilous (read difficult to do without it feeling worse than not doing it a lot of the time)
