### ISSUE TITLE
[composer] tooltip background color makes text hard to read

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7749]
(Since the screenshot displays larger than the app it downplays the problem)

![image](https://github.com/user-attachments/assets/4a9aacfb-c2cc-44a5-aad8-4b7981f56fee)

**Comment by thure** [comment]
This is the Joyride tooltip, its text color should be white

**Comment by wittjosiah** [comment]
@thure it's white in dark mode so seems like the text colour for this is just using the default text colour right now

**Comment by thure** [comment]
There is a token for this situation, `--dx-inverse`, it should be applied to elements that aren't getting it.
