### ISSUE TITLE
[composer] icons missing from sidebar

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7752]
Includes the `...` graphic for item dropdown:

![image](https://github.com/user-attachments/assets/9a1251e5-f7ff-4c70-b4f2-19d6a86323ec)

**Comment by seagreen** [comment]
Hmm it's starting to pick up some icons:

![image](https://github.com/user-attachments/assets/9817f694-4bea-444a-9179-b74eda19e422)

**Comment by wittjosiah** [comment]
This should be fixed in 0.6.10
