### ISSUE TITLE
[authoring] RangeError: Decorations that replace line breaks may not be specified via plugins

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7779]
I don't know how to reproduce it yet, but about three times in the past week I've hit a bug where bullet points appear doubled up:

![image](https://github.com/user-attachments/assets/2224331a-29f7-4206-86cc-669094dc6385)

I'm not sure what triggers it exactly, but I was hitting backspace the last time it happened. This might be the cause or a red herring.

On refresh I got the error in the issue title, this is an inside document error that appears like this:

![image](https://github.com/user-attachments/assets/ee966471-7cbd-43c1-bf02-02304516ee02)

The error persists after subsequent refreshes.

**Comment by wittjosiah** [comment]
@seagreen I'm assuming this was on composer.space? This should be resolved by https://github.com/dxos/dxos/pull/7775 on `main`. We can probably release it next week.

**Comment by seagreen** [comment]
> I'm assuming this was on composer.space?

Sure was!

> We can probably release it next week.

Wow, now my bug reports are being fixed *before I even make them* =)

**Comment by seagreen** [comment]
I'll close this, looking forward to the release.
