### ISSUE TITLE
[shell] mobile doesn't show PIN entry field

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#7791]
![image](https://github.com/user-attachments/assets/c902791a-0ff1-4031-a1ea-2e598e0ca8e1)

If you touch the correct location the first number box will appear, but until then the field is blank.

Location: staging.

**Comment by seagreen** [comment]
Other details: iOS, Safari incognito window

**Comment by thure** [comment]
I can’t reproduce this:

https://github.com/user-attachments/assets/7e2f7774-cfc3-4df2-b6d3-8c49bfb502a4

**Comment by thure** [comment]
I think I see the issue, this was probably resolved by #7796.
