### ISSUE TITLE
[grid] rendering bug for frozen columns

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#8051]
https://github.com/user-attachments/assets/f19ff353-f150-46fe-9210-85275ecb4865

**Comment by thure** [comment]
I’m really struggling to reproduce this…

**Comment by wittjosiah** [comment]
@thure it specifically seemed to be happening when the grid lost attention while it was offscreen and then scrolled back to it afterwards.

**Comment by thure** [comment]
Trying that:

https://github.com/user-attachments/assets/fe00ce30-84ef-4e79-9bbc-9e14d974647a

Maybe a weird temporary quirk with your browser? Did you try turning it off and back on again? 😅

**Comment by wittjosiah** [comment]
I can't repro anymore either. Maybe your calculation changes yesterday fixed it.
