### ISSUE TITLE
Hyperswarm as an alternative transport layer?

### ISSUE THREAD

**Issue by saimon-moore** [dxos/dxos#8284]
Hi,

I just discovered dxos. Huge kudos for what looks like an amazing platform. I've been following the decentralized local-first space for a while and dxos is one of the few platforms that is getting very close to what I've been looking for to build these types of apps.

The only bit I wasn't very keen on is having to depend on webrtc signalling servers.

I wonder if you have looked into https://docs.pears.com/building-blocks/hyperdht and https://docs.pears.com/building-blocks/hyperswarm as an alternative transport layer?

FYI: The hyperstack provides it's own distributed storage system based on a append-only log ([hypercore](https://docs.pears.com/building-blocks/hypercore) but you can definitely use `hyperdht` and `hyperswarm` without having to use hypercore.

I wonder what exactly would need to be changed in dxos to allow support for a different transport layer like hyperswarm?

**Comment by wittjosiah** [comment]
The networking abstractions are here https://github.com/dxos/dxos/tree/main/packages/core/mesh. In theory I think you should be able to build a hyperswarm adapter for this. I've not kept up with where hyperswarm is at recently but the big reason that DXOS never built on it was that it didn't work in web browsers at the time. Also worth noting that, prior to migrating to Automerge, ECHO was built using hypercore and currently still uses it for managing control feeds for spaces. 

We've discussed with Socket Supply integrating their p2p networking as an alternative transport as well as we've been experimenting with using their runtime for a Composer native app. In terms of "official" transports, that's much more likely the direction we'll head in for pure p2p, but would be happy to see other third-party maintained transports pop up.

**Comment by saimon-moore** [comment]
@wittjosiah thanks for the quick response. Very interesting. 

Yeah, currently, it works in the browser but you do need at least a single [dht-relay](https://github.com/holepunchto/hyperswarm-dht-relay) node deployed somewhere (I forgot about that). It [works](https://github.com/holepunchto/bare-expo) in mobile devices as well, however, they've decided to use a new minimal js runtime ([bare](https://github.com/holepunchto/bare)) for mobile which makes integrating with it a bit more challenging (you can't just put together any npm package). (Maybe worth taking another look at recent developments though: https://docs.pears.com/)

I've been looking at it because it appeared hyperstack was closest to pure p2p that I've seen. The complexity of having to maintain web rtc in production (signalling & stun/turn servers) has always put me off.

What's the idea for propiety apps that are built on doxs (once it's "production ready") as far as the webrtc transport is concerned?

**Comment by wittjosiah** [comment]
Currently all DXOS would depend on webrtc & a signalling server. We have one which is freely available right now and in the configs of example apps and anyone building apps would be free to use. We've not discussed much what we'd do if the usage of that grew to the point it was too costly to offer for free, but presumably at least the TURN would be metered at some point (or self-host). As I mentioned, we're collaborating with https://socketsupply.co/ to hopefully alleviate the necessity of (or a least lower the cost of) that infrastructure at some point in the future though there's no timeline for that at this stage.

**Comment by saimon-moore** [comment]
ok cool. Thanks a lot Josiah
