### ISSUE TITLE
DXOS through cdn on a short lived webserver

### ISSUE THREAD

**Issue by fire17** [dxos/dxos#8322]
Hi guys hope you're well
I'm trying a bit of a hack (using github-pages as psuedo, short-lived web server)
the idea to spin up a frontend repo on github-pages, and also the backend on github-pages on a private repo with keys to the cloud db (upstash) - might be a bit ridiculous haha - but will make both the front and the server hosting completely free 

anyways i would love to finally check out dxos (been meaning to use this for ages)
i want to use dxos to make a server logs monitor for testing purposes
again the server lives on a live-per-request, and i cant install any deps

so i searched for examples but couldn't find anything working that does dxos coms through a CDN

the closest thing i've found is at: [https://www.jsdelivr.com/package/npm/@dxos/client-services?tab=stats](https://www.jsdelivr.com/package/npm/@dxos/client-services?tab=stats)
(Can anyone verify this source? is it legit? [security healthcheck](https://snyk.io/advisor/npm-package/@dxos/client-services) seems not great
the code it recommends is:
```
<script type="module">
import dxosclientServices from 'https://cdn.jsdelivr.net/npm/@dxos/client-services/+esm'
</script>
```

but couldnt get it to work

so if you can please help:
<h3> 1. Can anyone show a server/client example of XDOS imported in vanilla js through a CDN url ? </h3>
<h3> 2. Can anyone refer to a working github-pages with DXOS ? </h3>

Posted on discord aswell.. https://discord.com/channels/837138313172353095/837138313172353098/1311218545346088981
Thanks a lot and all the best!

**Comment by wittjosiah** [comment]
copying answer from discord:

> sounds interesting! unfortunately an unbundled CDN version is not something we’ve really tried before and not something within the scope of what we’re able to support right now. We’re certainly not against it though and in principle it should be possible but its just hard to know how many issues there are that will need to be resolved. So if you (or anyone else) wanted to keep digging we can answer any questions you have to try to unblock you.
