### ISSUE TITLE
WebGL on composer.space context could not be created on old devices and freeze on mobile 

### ISSUE THREAD

**Issue by drunkod** [dxos/dxos#8328]
App Commit e2cde42 
runtime.js:3139 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Could not create a WebGL context, VENDOR = 0x8086, DEVICE = 0x0046, GL_VENDOR = Google Inc. (Intel), GL_RENDERER = ANGLE (Intel, Mesa Intel(R) HD Graphics (ILK), OpenGL 2.1 Mesa 24.2.6), GL_VERSION = 24.2.6, Sandboxed = no, Optimus = yes, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .
Je @ runtime.js:3139
(anonymous) @ helpers.ts:98
oe @ runtime.js:3139
dw @ runtime.js:3139
vx @ runtime.js:6272
start @ runtime.js:7394
await in start
load @ runtime.js:7394
await in load
t @ react-spline.js:71
(anonymous) @ react-spline.js:76
Rj @ react-dom.production.min.js:244
Ik @ react-dom.production.min.js:286
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14Understand this errorAI
runtime.js:3139 THREE.WebGLRenderer: A WebGL context could not be created. Reason:  Failed to create a WebGL2 context.
Je @ runtime.js:3139
(anonymous) @ helpers.ts:98
oe @ runtime.js:3139
dw @ runtime.js:3139
vx @ runtime.js:6272
start @ runtime.js:7394
await in start
load @ runtime.js:7394
await in load
t @ react-spline.js:71
(anonymous) @ react-spline.js:76
Rj @ react-dom.production.min.js:244
Ik @ react-dom.production.min.js:286
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14Understand this errorAI
runtime.js:3139 WebGLRenderer: Floating point depth texture requires WebGL2.
ie @ runtime.js:3139
q @ runtime.js:3139
xe @ runtime.js:3139
de @ runtime.js:3139
Ce @ runtime.js:3139
setRenderTarget @ runtime.js:3139
render @ runtime.js:5706
render @ runtime.js:5706
render @ runtime.js:5866
renderSplineScene @ runtime.js:6272
Jv.render @ runtime.js:7394
start @ runtime.js:7394
await in start
load @ runtime.js:7394
await in load
t @ react-spline.js:71
(anonymous) @ react-spline.js:76
Rj @ react-dom.production.min.js:244
Ik @ react-dom.production.min.js:286
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14Understand this errorAI
runtime.js:3139 THREE.WebGLRenderer: Use UnsignedShortType or UnsignedIntType for DepthFormat DepthTexture.
ie @ runtime.js:3139
q @ runtime.js:3139
xe @ runtime.js:3139
de @ runtime.js:3139
Ce @ runtime.js:3139
setRenderTarget @ runtime.js:3139
render @ runtime.js:5706
render @ runtime.js:5706
render @ runtime.js:5866
renderSplineScene @ runtime.js:6272
Jv.render @ runtime.js:7394
start @ runtime.js:7394
await in start
load @ runtime.js:7394
await in load
t @ react-spline.js:71
(anonymous) @ react-spline.js:76
Rj @ react-dom.production.min.js:244
Ik @ react-dom.production.min.js:286
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:270
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14Understand this warningAI
react-dom.production.min.js:189 TypeError: l.clearBufferfv is not a function
    at rg.clear (runtime.js:6272:525)
    at Qm.render (runtime.js:5706:752)
    at Zm.render (runtime.js:5706:5794)
    at ig.render (runtime.js:5866:7342)
    at rg.renderSplineScene (runtime.js:6272:6813)
    at Jv.render (runtime.js:7394:19077)
    at Jv.start (runtime.js:7394:24295)
    at async Jv.load (runtime.js:7394:20581)
    at async t (react-spline.js:71:11)
Mi @ react-dom.production.min.js:189
t.callback @ react-dom.production.min.js:190
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:261
jk @ react-dom.production.min.js:260
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14Understand this errorAI
composer.space/:1 [.WebGL-0x38cc039e7800] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachments have inconsistent bit plane counts.

![image](https://github.com/user-attachments/assets/8fa46bd4-c247-4a9a-a819-536dac636dbe)

**Comment by wittjosiah** [comment]
@drunkod could you provide some more details? Device info, os, browser, etc. Reproduction steps at minimum. This above isn't enough information to take any action on.

**Comment by drunkod** [comment]
On mobile chrome, background animation freeze ui, and user input email not functioning.

Please disable animation on mobile devices.

**Comment by drunkod** [comment]
> @drunkod could you provide some more details? Device info, os, browser, etc. Reproduction steps at minimum. This above isn't enough information to take any action

From dev tools chrome https://developer.chrome.com/docs/devtools/recorder

[Recording 01.12.2024 at 12_04_28.JSON](https://github.com/user-attachments/files/17968098/Recording.01.12.2024.at.12_04_28.JSON)
 on.

[js.tar.gz](https://github.com/user-attachments/files/17968112/js.tar.gz)
