### ISSUE TITLE
[composer] update welcome screen to align with new website

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#8336]
Hopefully should also resolve https://github.com/dxos/dxos/issues/8328

**Comment by Raymmar** [comment]
Here are two examples of the Composer gate page to match the new website design. 

Composer - https://dxos-org.webflow.io/gate
DXOS - https://dxos-org.webflow.io/hex-gate

Prob need to review it to make sure it is what we want and then decide how to implement this.
