### ISSUE TITLE
Deploy to Github Pages?

### ISSUE THREAD

**Issue by fire17** [dxos/dxos#8451]
Hi there
would love to get into dxos

was wondering if it's possible to use dxos at all while running client side code only?

and specifically..
 is it possible to create some sort of simple example that uses
dxos p2p coms running on **github-pages only** ?

looked on github and online and could find it,
nor a way to import dxos from a cdn... #8322 

i wanna see dxos running from just the client side, with no backend per say 
Thanks a lot and all the best!

**Comment by wittjosiah** [comment]
Yes, most DXOS apps have no backend other than a configured signaling server. It does require a build step but it is a client-side library and is possible to deploy on Github pages or any other static site host.

The examples here https://docs.dxos.org/guide/samples.html are deployed with Cloudflare pages.

If you have further questions feel free to open a discussion post or chat with us on Discord.

**Comment by fire17** [comment]
The issue is about if its possible to run it on github pages - kindly reopen

there should be some way to workaround the build step
for example loading it using a cdn - open to other methods
so that dxos could be used easily with github pages

thanks for the reply, i hope you can help make this actually work , could be gamechanger imo
all the best :)

**Comment by wittjosiah** [comment]
Github Pages supports build steps https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages so it's already possible to host DXOS apps on Github if you want

**Comment by fire17** [comment]
thanks! is there any existing repo example you can share ? i cant be the first one to do this (but couldnt find any)
